### ISSUE TITLE
emsdk.bat does not find python.exe

### ISSUE THREAD

**Issue by aportale** [emscripten-core/emsdk#1009]
emsdk.bat looks for **python\3.9.2-1_64bit\python.exe**. But python.exe is now here **python\3.9.2-nuget_64bit\python.exe**. It is the nuget package, now. As a result, emsk_env.bat fails with:

```
C:\Users\aportale\emsdk-3.1.6>emsdk_env.bat
'python' is not recognized as an internal or external command, operable program or batch file.
```

I have emsdk 3.1.6 installed and activated.

**Comment by sbc100** [comment]
Ooo.. thats not good.  I wonder how that got past our CI.

**Comment by sbc100** [comment]
It should be fine to fall back to the primordial python that you used to bootstrap emsdk though.     How didn't you install emsdk in the first place without `python.exe` in your path?

**Comment by aportale** [comment]
Thanks for the fast fix.
> How didn't you install emsdk in the first place without `python.exe` in your path?
I temporarily added an installed python to PATH for the installation/activation.
