### ISSUE TITLE
emsdk_env.bat does not add path to em++ to PATH (on Windows)

### ISSUE THREAD

**Issue by aportale** [emscripten-core/emsdk#1012]
I am on Windows. With my emsdk 2.0.14 installation (emsdk/e82ac4ec1febaa7bc6938685a0558bae569c1541), I can call em++ after I run emsdk_env.bat:

```
C:\emsdk-2.0.14>emsdk_env.bat
Adding directories to PATH:
PATH += C:\emsdk-2.0.14
PATH += C:\emsdk-2.0.14\upstream\emscripten
PATH += C:\emsdk-2.0.14\node\14.15.5_64bit\bin

Setting environment variables:
[...]

C:\emsdk-2.0.14>em++
em++: error: no input files
```

But with my emsdk 3.1.6 installation (emsdk/497595e8306f63702d3d734e420f771ac83ea6bf), emsdk_env.bat does not add the *upstream\emscripten* subdirectory to PATH, so that calling em++ fails:
```
C:\emsdk-3.1.6>emsdk_env.bat
Adding directories to PATH:
PATH += C:\emsdk-3.1.6

Setting environment variables:
[...]

C:\Users\alportal\dev\emsdk-3.1.6>em++
'em++' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by sbc100** [comment]
Did you run the `install` and `activate` command within emsdk-3.1.6? 

BTW, you don't need to (and indeed should not) checkout particular versions of emsdk to access the different versions, you can just checkout `origin/main` and then `emsdk install 2.0.14` or `emsdk install 3.1.6` from tip of tree.

**Comment by aportale** [comment]
Oops.. I did indeed forget the activate step for my 3.1.6 installation...

Sorry for the noise. It works now:
```
C:\emsdk-3.1.6>emsdk_env.bat
Adding directories to PATH:
PATH += C:\emsdk-3.1.6
PATH += C:\emsdk-3.1.6\upstream\emscripten
PATH += C:\emsdk-3.1.6\node\14.18.2_64bit\bin

Setting environment variables:
[...]

C:\Users\alportal\dev\emsdk-3.1.6>em++
shared:INFO: (Emscripten: Running sanity checks)
em++: error: no input files
```

> BTW, you don't need to (and indeed should not) checkout particular versions of emsdk to access the different versions, you can just checkout origin/main and then emsdk install 2.0.14 or emsdk install 3.1.6 from tip of tree.

I usually do that. It is just that my 2.0.14 installation was already a bit older, thus had an older emsdk checkout.
