### ISSUE TITLE
Installation Error！！

### ISSUE THREAD

**Issue by djinnnn** [emscripten-core/emsdk#1019]
when I run the command ``` ./emsdk install latest ```  met Error and the message is here
HTTP Error 404: Not Found
and my system is arrch64 ubuntu 20.04.4
<img width="1022" alt="截屏2022-04-01 17 27 07" src="https://user-images.githubusercontent.com/68310597/161236158-5e9f19a6-e989-453d-a8b7-8841ba7f6118.png">

**Comment by sbc100** [comment]
linux/arm64 support currently has very limited support.   3.1.8 is now uploaded but expect new releases to see the same delays since we don't officially support that platform yet.

See #547

**Comment by sbc100** [comment]
Closing this since 3.1.8 for arm64 should now be uploaded/working.
