### ISSUE TITLE
Docker / emcmake / Github Actions: Error in parsing wasm input

### ISSUE THREAD

**Issue by nick-thompson** [emscripten-core/emsdk#1034]
Hey, I'm using the official Docker container `emscripten/emsdk` to build my project with something just like the documentation suggestions: `docker run -v $(pwd):/src -u $(id -u):$(id -g) ... emcmake cmake ...`.

Locally (MacOS 11.5) this works perfectly, never have issues and I've been using it regularly in my workflow for months. However, I've just updated my Github Actions CI to automatically run the same step, and I'm getting very odd errors:

```
[parse exception: expected more elements in list]Fatal: error in parsing wasm input
em++: error: '/emsdk/upstream/bin/wasm-metadce --graph-file=/tmp/tmpfv8uwzab.txt elementary-wasm.wasm -o elementary-wasm.wasm --mvp-features' failed (returned 1)
```

My Github action runs on `ubuntu-latest` (Ubuntu 20.04) and fails consistently with this output. I'm not sure how to track this down; what might be the issue here?

Thanks

**Comment by sbc100** [comment]
That is very odd indeed,  it looks like the wasm file that is being generated by the linker is not able to be parsed by `wasm-metadce` (which is a tool that is per of binaryen.

Can you run the build with `-v` (or better still with EMCC_DEBUG=1 set) and include the full output?   Does it work if you don't reduce the optimization level such that metadce is not run?

@kripken

**Comment by nick-thompson** [comment]
Thanks for the quick reply @sbc100.

Here's what I get from the same run on github actions with EMCC_DEBUG=1:

```
Traceback (most recent call last):
  File "/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/emsdk/upstream/emscripten/emcc.py", line 1107, in run
    phase_post_link(options, state, wasm_target, wasm_target, target)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/emsdk/upstream/emscripten/emcc.py", line 2542, in phase_post_link
    phase_binaryen(target, options, wasm_target)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/emsdk/upstream/emscripten/emcc.py", line 3172, in phase_binaryen
    run_closure_compiler()
  File "/emsdk/upstream/emscripten/emcc.py", line 3169, in run_closure_compiler
    save_intermediate_with_wasm('closure', wasm_target)
  File "/emsdk/upstream/emscripten/emcc.py", line 173, in save_intermediate_with_wasm
    building.save_intermediate(wasm_binary, name + '.wasm')
  File "/emsdk/upstream/emscripten/tools/building.py", line 1467, in save_intermediate
    shutil.copyfile(src, dst)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'elementary-wasm.wasm'
```

There's a ton of output; I've highlighted the piece that I think is interesting but of course please tell me what else I can provide (I can attach the whole log if you want)

Interestingly, if I scroll up I can find log lines suggesting a successful generation of that file:

```
shared:DEBUG: successfully executed /emsdk/upstream/bin/wasm-emscripten-finalize --minimize-wasm-changes --dyncalls-i64 elementary-wasm.wasm -o elementary-wasm.wasm --detect-features
```

**Comment by sbc100** [comment]
Sounds like some kind of strange quirk of how you are using docker..  can you share the full command you are using, not just the emcc command but the docker command you are using to run it?   Where is the `-o` output being written?  Is it inside the docker container somewhere?  Does it work if you redirect the `-o` output to somewhere else in the container other than the place where the source file lives (which I assume is somehow mounted/injected into the container)?

**Comment by nick-thompson** [comment]
Yup, I have a build script `build.sh` that looks like this:

```
    mkdir -p "$ROOT_DIR/build/wasm/"
    pushd "$ROOT_DIR/build/wasm/"

    if [ -z "$EM_FLAGS" ]; then
        echo "Error: Missing EM_FLAGS in Docker context; what do I build with?"
        exit 1
    fi

    EMCC_DEBUG=1 emcmake cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DONLY_BUILD_WASM=ON \
        -DCMAKE_CXX_FLAGS="$EM_FLAGS" \
        ../..

    EMCC_DEBUG=1 emmake make

    popd
```

and I invoke that script with docker via

```
        docker run \
          --rm \
          -v $(pwd):/src \
          -u $(id -u):$(id -g) \
          --env EM_FLAGS="$EM_FLAGS" \
          emscripten/emsdk:2.0.30 \
          ./scripts/build.sh

        cp $ROOT_DIR/build/wasm/wasm/elementary-wasm.js $OUTPUT_FILENAME
```

**Comment by sbc100** [comment]
Can you show the full failing command ?  It should be shown near the top of the ` EMCC_DEBUG=1` output.  In fact it might be best just to attach the full output. 

This seems like some kind of docker issue, and it might be easier for you to debug since you have the failure locally.   Its hard to it would be possible for that file not to exist when save_intermediate is called.

**Comment by nick-thompson** [comment]
I think maybe this is the command you're looking for?

```
emcc:WARNING: invocation: /emsdk/upstream/emscripten/em++.py @CMakeFiles/elementary-wasm.dir/includes_CXX.rsp -O3 --bind --closure 1 -s ASSERTIONS=0 -s WASM=1 -s WASM_ASYNC_COMPILATION=0 -s MODULARIZE=1 -s SINGLE_FILE=1 -s ALLOW_MEMORY_GROWTH=1 -O3 -DNDEBUG -std=gnu++17 -o CMakeFiles/elementary-wasm.dir/Main.cpp.o -c /src/wasm/Main.cpp (in /src/build/wasm/wasm)
```

I've attached the log below; I agree it sounds like a docker issue but it's odd because i'm running the same docker command locally with no problem. So it's somehow a docker + github actions runner issue I think?

[Log.txt](https://github.com/emscripten-core/emsdk/files/8490939/Log.txt)

**Comment by nick-thompson** [comment]
Update: Ah, interesting, this seems like it could be related– https://docs.github.com/en/enterprise-server@3.3/actions/creating-actions/dockerfile-support-for-github-actions#workdir

**Comment by nick-thompson** [comment]
I just spent some additional time ensuring that my build happens outside of the mounted folder in the container and that seems to neatly resolve the issue. Closing here, thanks for your help @sbc100 !
