### ISSUE TITLE
"emsdk activate tot" installs a very old npm version

### ISSUE THREAD

**Issue by shlomif** [emscripten-core/emsdk#1048]
```
shlomif[fcs]:$trunk/fc-solve/source$ emsdk activate tot
Setting the following tools as active:
   node-14.18.2-64bit
   releases-upstream-8500263d4e0974bf29c9d02ed7bcf2720c1c3995-64bit

Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /home/shlomif/Download/unpack/prog/llvm-to-js/emsdk
    /home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/node/14.18.2_64bit/bin
    /home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/upstream/emscripten
- This can be done for the current shell by running:
    source "/home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/emsdk_env.sh"
- Configure emsdk in your shell startup scripts by running:
    echo 'source "/home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/emsdk_env.sh"' >> $HOME/.zprofile
shlomif[fcs]:$trunk/fc-solve/source$ which npm
/home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/node/14.15.5_64bit/bin/npm
shlomif[fcs]:$trunk/fc-solve/source$ npm -v
6.14.11
shlomif[fcs]:$trunk/fc-solve/source$ /usr/bin/npm -v
8.3.1
shlomif[fcs]:$trunk/fc-solve/source$

```

**Comment by sbc100** [comment]
When you activative emsdk it we put our own specific version of node (and npm) in your `$PATH`.

There have been some discussions of adding a way to avoid this.  See https://github.com/emscripten-core/emsdk/pull/714 and https://github.com/emscripten-core/emscripten/issues/4848.

So the short answer is that this is working as indented, at least as of today.   Do you have a specific problem with this behaviour?

**Comment by shlomif** [comment]
@sbc100 : I'd like emsdk to provide a more recent version of npm.

**Comment by sbc100** [comment]
Can you explain exactly why you need a newer version?    Also, specifically do you need the newer version available at the same time as the emscripten tools.   When emsdk tools are not active your own version should still be the one that is found in the PATH so I think the problem only exists when you want to use emsdk tools *and* your own version of npm/node?

**Comment by sbc100** [comment]
I'm thinking of adding some kind of option to emsdk activate to avoid injecting our version of node into the path.. so hopefully that should solve your issue.

**Comment by shlomif** [comment]
> I'm thinking of adding some kind of option to emsdk activate to avoid injecting our version of node into the path.. so hopefully that should solve your issue.

:+1: ; sounds good.

**Comment by shlomif** [comment]
You can find a  preliminary version of a patch for that here - https://paste.centos.org/view/2cf1d44e

**Comment by sbc100** [comment]
Can we close this in favor or https://github.com/emscripten-core/emsdk/issues/1142?  They seems to the same right?
