### ISSUE TITLE
mismatch for the compiler version between your conan profile

### ISSUE THREAD

**Issue by levon-vardevanyan-solarwinds** [emscripten-core/emsdk#1085]
Hey guys I wonder if anyone can help me to understand this weird error I see.

I'm using conan for my c++ dependency management and surprisingly on both Linux and Mac with clang13 and apple-clang13 I'm seeing this weird issue after running

```
mkdir build_emscripten && cd build_emscripten
conan install --build=missing ..
emcmake cmake ..
```

It complains with

```
CMake Error at build_emscripten/conanbuildinfo.cmake:733 (message):
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 13

  Compiler version detected in CMake: 15.0

  Please check your conan profile settings (conan profile show
  [default|your_profile_name])

  P.S.  You may set CONAN_DISABLE_CHECK_COMPILER CMake variable in order to
  disable this check.
Call Stack (most recent call first):
  build_emscripten/conanbuildinfo.cmake:839 (conan_error_compiler_version)
  build_emscripten/conanbuildinfo.cmake:924 (check_compiler_version)
  build_emscripten/conanbuildinfo.cmake:472 (conan_check_compiler)
  CMakeLists.txt:28 (conan_basic_setup)
```

./CMakeFiles/3.23.2/CMakeCXXCompiler.cmake indeed has version 15 in there:

```
set(CMAKE_CXX_COMPILER_ID "Clang")
set(CMAKE_CXX_COMPILER_VERSION "15.0.0")
```

Setting up CONAN_DISABLE_CHECK_COMPILER to True helps and everything works fine...

Any idea where exactly this "Compiler version detected in CMake" happens? There were no traces of clang 15 on both machines obviously, it is still in dev and unstable.

**Comment by sbc100** [comment]
I don't know what conan is, but we ship llvm 15, and it seems to expect 13.  Your workaround of passing `CONAN_DISABLE_CHECK_COMPILER` seem correct, although you might want to check with the conan project about how safe that is?

**Comment by levon-vardevanyan-solarwinds** [comment]
I didn't realise that you guys actually ship llvm 16 alongside with emsdk, my bad! That means that the proper solution would be to create a conan profile that will be referring to your toolchain. It probably should looks something like this

```
[settings]
...
compiler=clang
compiler.version=16
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
CC=/root/emsdk/upstream/bin/clang
CXX=/root/emsdk/upstream/bin/clang++

```

at the moment conan doesn't support clang 16 but it will be fixed in a couple of hours I think ([boom](https://github.com/conan-io/conan/pull/11780)) meanwhile one could just add "16" to clang version array in .conan/settings.yml manually. After that all the conan libraries should be build with the same toolchain as the main project, cheers
