### ISSUE TITLE
Could not make proto path relative in protobuf generation

### ISSUE THREAD

**Issue by foreverlms** [emscripten-core/emsdk#1086]
### Question

In my C++ project, I use protobuf to generate some files with calling `protobuf_generate_cpp` cmake macro.  The generate make file is like:

```
cd /Users/bob/code/cmake-build-debug/tools/converter/src && /Users/bob/code/cmake-build-debug/_deps/protobuf-build/protoc -I/Users/bob/cmake-build-debug/tools/converter/src --cpp_out=./ /Users/bob/code/cmake-build-debug/tools/converter/src/module/a.proto
```

This works and the file hierarchy is:
```
cmake-build-debug/toos/converter/src/module/a.proto
```

When I use `emcmake` and `emmake` to build this same project, I got generated make files:

```
/Users/bob/code/emsdk/node/14.18.2_64bit/bin/node --experimental-wasm-threads /Users/bob/code/cmake-build-debug/_deps/protobuf-build/protoc.js -I/Users/bob/code/cmake-build-debug/pnn/tools/converter/src --cpp_out=./ /Users/bob/code/cmake-build-debug/tools/converter/src/module/a.proto
```

But I got error:

```
Users/bob/code/cmake-build-debug/tools/converter/src: warning: directory does not exist.
Could not make proto path relative: module/a.proto: No such file or directory

```

But why? I have googled a lot. Thanks for your reply.

**Comment by sbc100** [comment]
You probably want to be using your native/host build of protoc to compile your protos.

If you really want to use the node/emscripten version of protoc, then you would need to somehow expose host host fileystem (where your input files like to the emscripten-generated code which has its own filesystem internally).  The simplest way to do this is probably to build protoc with `-sNODERAWFS`.   However, building protoc as a host binary sounds like a better way to to go

**Comment by foreverlms** [comment]
Yes. I remember this is what I did to solve this.
