### ISSUE TITLE
Add wasi-sdk as a tool

### ISSUE THREAD

**Issue by rajsite** [emscripten-core/emsdk#1093]
Seems like the evolving de-facto expectation for WebAssembly-compiled languages and libraries is to offer both Browser builds using the emscripten toolchain and WASI builds using wasi-sdk. 

As someone who has already integrated the emscripten toolchain into projects and leverages emsdk for managing tools, it would be very handy if it could also help fetch and manage wasi-sdk.

I think it would be a useful incremental step to enable just managing versions and fetching the tooling today. Longer term I could even see emcc having flags to swap to the wasi-sdk toolchain and root (i.e. depending on the long-term vision of emscripten `WASM_STANDALONE`).

I think the emscripten and wasi toolchains complement each other and maybe will even more so as WASM components and interface types evolve.

**Comment by sbc100** [comment]
emsdk is specifically about installing emscripten and its dependencies.   I'm not sure it makes sense to add wasi-sdk there.

Also wasi-sdk, unlike emscripten, is relatively dependency free (it doesn't need python, or node, or binaryen) and its already available pre-built for mac, linux and windows directly from github releases.

**Comment by rajsite** [comment]
Fair enough. And doesn't seem like any others have chimed in to express interest so no need to keep it open. Thanks for the feedback.

**Comment by briancullinan2** [comment]
I like this idea because it also goes along with Binaryen which has wasm-opt which makes wasms smaller. It would be useful to put them all in the same ~/emsdk directory.
