### ISSUE TITLE
Installation of 2.0.20 and older fails with HTTP Error 404

### ISSUE THREAD

**Issue by ricardperez** [emscripten-core/emsdk#1126]
Hello people,

A project I am working on is meant to use version `2.0.15`. However, when I try to install it I get this error:
```
Resolving SDK version '2.0.15' to 'sdk-releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit'
Installing SDK 'sdk-releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Skipped installing python-3.9.2-64bit, already installed.
Installing tool 'releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
error: installation failed!
```

Effectively, if I try to fetch [such URL](https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries-arm64.tbz2) in the browser, I do get a `NoSuchKey` error.

It seems the first available version is `2.0.21`.

I tried with version one, and I was able to install `1.38.3`, but not `1.40.1`. So I am unsure what is the pattern here. I would assume only a specific amount of artefacts are kept alive, but then why is `1.38.3` still there?

Any idea how to solve this? Maybe an alternative mirror?

Thanks!

**Comment by ricardperez** [comment]
My first search for similar issues didn't get me anything. Now I found [this one](https://github.com/emscripten-core/emsdk/issues/1089).

I guess this is it. No support for arm64 on this specific versions.

Any idea how to prebuilt it and get it uploaded?

**Comment by sbc100** [comment]
We only starting shipping arm64 builds for mac at a certain point in time.  I imagine that trying to go back in time and re-built old version for new architecture would not be successful (or at least would not be easy).

I think we should probably just disallow installation of arm binaries on macOS for older SDK versions, and instead install the x86_64 binaries (which should work fine in emulation mode).

Can you see if this works for you by installing 2.01.5 with `EMSDK_ARCH=x86_64` in the environment?

**Comment by ricardperez** [comment]
That worked like a charm. Thanks a lot.
```
EMSDK_ARCH=x86_64 emsdk install 2.0.15
```
