### ISSUE TITLE
How to set the installation directory ?

### ISSUE THREAD

**Issue by mgautierfr** [emscripten-core/emsdk#1127]
I haven't found an option to install the sdk/tool in a specific directory.

It seems `./emsdk install latest`  always install in the root directory (where `emsdk` is).
From what I understand, the sdk path come from https://github.com/emscripten-core/emsdk/blob/main/emsdk.py#L194-L195

Is it possible to add a command line option to change the installation path ?
Can I patch the `emsdk_path` function to return the path I want and it will work or installation has to be done in root directory ?

**Comment by sbc100** [comment]
No, there is no way to this today.  I'm not sure we would want to add that kind of complexity either.   The actual installations paths should really be though of as implementation details of emsdk.    

Maybe you could explain a little more about your use case?

**Comment by mgautierfr** [comment]
I have a "meta" build system which compile different projects and their dependencies on different platforms. I'm currently targeting emscripten.

The idea of the build system is to download sources in one directory and install/compile everything in a directory by targeted platform. I can workaround the lack of installation path option by copying the source in the install directory of the sdk and install it from there but it seems a bit overkill to me.

**Comment by sbc100** [comment]
I think if you want different versions of emsdk in different places that simplest thing to do is install emsdk itself in each location.  

The size of emsdk itself is absolutely tiny compared to the things it installed (i.e. llvm) so it shouldn't add much overhead.

**Comment by mgautierfr** [comment]
Yes, it is what I've done at the end. It was just in case I missed something or it was easy to fix. Thanks anyway.
