### ISSUE TITLE
Unable to build project after fresh emscripten install

### ISSUE THREAD

**Issue by xReveres** [emscripten-core/emsdk#1128]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.21 (f9e81472f1ce541eddece1d27c3632e148e9031a)
clang version 16.0.0 (https://github.com/llvm/llvm-project a4a29438f451370ed241dde30bfcaab0fdf2ab71)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line in full:**
```
[build] em++: error: '/emsdk/upstream/bin/wasm-ld -o bin/game.wasm --shared-memory --no-check-features ...C/CPP FILES... vendor/miniz/libminiz.a -L/emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten /emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libboost_headers.a /emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libz.a /emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/crtbegin.o --whole-archive -lfetch-mt -lembind-rtti --no-whole-archive -lGL-mt-webgl2-full_es3 -lal -lhtml5 -lstubs -lnoexit -lc-mt -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpjct4twon.undefined --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export=__cxa_is_pointer_type --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)
```

**Full link command and output with `-v` appended:**
```
[build] wasm-ld: error: /emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt-mt.a(stack_limits.o): undefined symbol: __stack_high
[build] wasm-ld: error: /emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt-mt.a(stack_limits.o): undefined symbol: __stack_low
```

Maybe it is problem with emscripten version, but I can't update to latest version.
Command:
```
./emsdk install 3.1.24
```
Output:
```
Resolving SDK version '3.1.24' to 'sdk-releases-upstream-54217a0950bb1dafe8808cc6207d378e323f9d74-64bit'
Installing SDK 'sdk-releases-upstream-54217a0950bb1dafe8808cc6207d378e323f9d74-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Installing tool 'releases-upstream-54217a0950bb1dafe8808cc6207d378e323f9d74-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/54217a0950bb1dafe8808cc6207d378e323f9d74/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
error: installation failed!
```
System:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```
Arch: ARM

**Comment by sbc100** [comment]
If you want to install on arm64 linux you are better of using `./emsdk install latest`.  This is because not all versions of the SDK have binaries for arm64 linux.  See https://github.com/emscripten-core/emsdk/blob/e41b8c68a248da5f18ebd03bd0420953945d52ff/emscripten-releases-tags.json#L5

**Comment by xReveres** [comment]
@sbc100 any changes? or tell me how I can downgrade/fix it?

**Comment by sbc100** [comment]
Sorry,  I meant to write `./emsdk install latest-arm64-linux`...  that should give you the correct version.

**Comment by xReveres** [comment]
Still problem

**Comment by sbc100** [comment]
What problem is persisting?  Does `./emsdk install latest-arm64-linux` work for you?

Did you also run `./emsdk activate latest`?

I wonder why `emsdk/emscripten/main/` is showing up in your command?  Do you have `emscripten-main-64bit` installed perhaps?   If you just want to use the bundled version of emscipten then I suggest you remove the `emsdk/emscripten` directory completely.  (That directory is for if you want to install a separate version of emscripten directly from git).

**Comment by xReveres** [comment]
> What problem is persisting? Does ./emsdk install latest-arm64-linux work for you?
> Did you also run ./emsdk activate latest?

Yes, I have latest.
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.21 (f9e81472f1ce541eddece1d27c3632e148e9031a)
clang version 16.0.0 (https://github.com/llvm/llvm-project a4a29438f451370ed241dde30bfcaab0fdf2ab71)
Target: wasm32-unknown-emscripten
Thread model: posix
```
> I wonder why emsdk/emscripten/main/ is showing up in your command? Do you have emscripten-main-64bit installed perhaps? If you just want to use the bundled version of emscipten then I suggest you remove the emsdk/emscripten directory completely. (That directory is for if you want to install a separate version of emscripten directly from git).

Yes, I have installed:
```
All recent (non-legacy) installable versions are:

         3.1.21    INSTALLED

The following precompiled tool packages are available for download:

    (*)    node-14.18.2-64bit           INSTALLED

The following tools can be compiled from source:
           llvm-git-main-64bit          INSTALLED
           emscripten-main-64bit        INSTALLED
           binaryen-main-64bit          INSTALLED
```
Reason, why I have installed `emscripten-main-64bit` is that I'm using CMake with toolchain from `emsdk/emscripten/main/cmake/Modules/Platform/Emscripten.cmake`.

I not mentioned it earlier, but my project worked fine before upgrading to the latest. Previously I had an `emsdk` install from june/july

**Comment by sbc100** [comment]
The problem is that you are mixing the emsdk  3.1.21 version of emscripten with the "main" version of emscripten (which means the main branch in git).

emsdk 3.1.21 comes with its own copy of emscripten in `upstream/emscripten` so you can find `cmake/Modules/Platform/Emscripten.cmake` there.  

Ideally your project could run `which emcc` to find out where emscripten lives rather than relying on a fixed path inside of emsdk directory.

Either way you should probably remove llvm-git-main-64bit,  emscripten-main-64bit and binaryen-main-64bit.  Those tools are all bundled in within 3.1.21.

**Comment by xReveres** [comment]
It works, thanks.

My last questions is: 
Why ARM version `latest-arm64-linux` is not set to "latest"?

**Comment by sbc100** [comment]
Because out build infrastructure for arm64-linux is limited, and not as automated.   Over time, as demand increased we can try to improve the situation.   I'm curious what your use case of linux-arm64 is?   Where are you running emsdk?

**Comment by xReveres** [comment]
I'm running emsdk (and another dev projects) on free Oracle ARM Cloud:
https://www.oracle.com/cloud/free/
Check it out. If you have any questions, write. I'm happy to help.
And thanks for help.
