### ISSUE TITLE
removeRunDependency is called before addRunDependency in generated js

### ISSUE THREAD

**Issue by eugeneko** [emscripten-core/emsdk#1132]
So, I have this snippet of code in generated JS module (I formatted it a bit):

```js
var Module;
if(typeof Module==='undefined')
  Module=eval('(function(){try{return Module||{}}catch(e){return{}}})()');
var s=document.createElement('script');
s.src='Resources.js';
document.body.appendChild(s);
Module['preRun'].push(function(){
  Module['addRunDependency']('Resources.js.loader')
});
s.onload=function(){
  if (Module.finishedDataFileDownloads < Module.expectedDataFileDownloads)
    setTimeout(s.onload, 100);
  else
    Module['removeRunDependency']('Resources.js.loader')
};
```

`preRun` is delayed due to having other dependencies, so `addRunDependency` is not called in time. Page is loaded and `removeRunDependency` is called, asserting.

What I am doing wrong?
How it's normally supposed to work?

PS: I use `FORCE_FILESYSTEM=1` if that matters

**Comment by sbc100** [comment]
Can you explain the desired outcome here?   How is it different to what is happening?

**Comment by eugeneko** [comment]
> Can you explain the desired outcome here? 

The desired outcome is Web page not crashing with assert, I guess?

This problem is present only in debug builds.
I debugged debug and release builds and I noticed that `removeRunDependency('Resources.js.loader')` is always called before `addRunDependency('Resources.js.loader')`. The only thing different is that Release build doesn't have asserts in `removeRunDependency`.

My guess is that generated JS code is always incorrect and it just luckily works.

This snippet is present only in debug version of `removeRunDependency` and it always asserts for me:
```js
  if (id) {
    assert(runDependencyTracking[id]);
    delete runDependencyTracking[id];
  } else {
    err('warning: run dependency removed without ID');
  }
```

**Comment by sbc100** [comment]
Why about if you just make the call to `removeRunDependency` conditional on weather you added it in the first place.

```
var runtimeDependencyAdded = false;
..
Module['preRun'].push(function(){
  if (Module.finishedDataFileDownloads != Module.expectedDataFileDownloads) {
    // If we have more files to download when preRun is called then we need to delay running.
    Module['addRunDependency']('Resources.js.loader')
  }
});
..
s.onload=function(){
  if (Module.finishedDataFileDownloads < Module.expectedDataFileDownloads)
    setTimeout(s.onload, 100);
  elif (runtimeDependencyAdded) 
    // If the runtime Dependency was never added we don't need to remove it here.
    Module['removeRunDependency']('Resources.js.loader')
};
```

**Comment by eugeneko** [comment]
> Why about if you just make the call to removeRunDependency conditional on weather you added it in the first place.

I cannot touch this snippet of code because it's generated by emcc compiler/linker.

**Comment by sbc100** [comment]
Can you give the full link line you are using to build your code?   Do you know what `Resources.js.loader` relates to?

**Comment by sbc100** [comment]
Are you sure that is part of the generated code?  I don't see `finishedDataFileDownloads` anywhere in the emscripten source code.

**Comment by eugeneko** [comment]
@sbc100 ah, you are right, I am sorry for confusion.

The project is huge and this snippet of code was generated somewhere inside our build system, while I assumed it's part of compiler output.

Thank you for help!
