### ISSUE TITLE
Unable to build with -reproducer

### ISSUE THREAD

**Issue by alshamma** [emscripten-core/emsdk#1136]
I created a reproducer.tar file using the --reproduce link flag. When I try to use it by running `cd <archive_root> && /path/to/emcc @response.txt`, I get this error:

```
emcc: error: main: No such file or directory ("main" was expected to be an input file, based on the commandline arguments provided)
```

I'm wondering if there is a problem with absolute paths in the reproducer tarfile.

**Comment by sbc100** [comment]
I guess perhaps there are some pathnames with spaces in there that are not being correctly escaped.  Is there some way you could send me the response file and/or the whole tar archive so I can take a look?  (I imagine sending it to me directly would be best).

**Comment by sbc100** [comment]
Sorry for the very late reply here.   The response file you send me looks like it was created by the linker (wasm-ld) and not the compiler (emcc).  So to run it you would do `wasm-ld @response.txt`.    

For a compiler reproducer you would do `emcc --reproduce=my.tar`.   For a wasm-ld reproducer you would do `emcc -Wl,--preproduce=my.tar`

With a few tweaks I was able to run the response file you send me with  `wasm-ld @response.txt`.

**Comment by alshamma** [comment]
Ah, mystery solved. Thank you!
