### ISSUE TITLE
Build with Wno-enum-constexpr-conversion

### ISSUE THREAD

**Issue by pinguin999** [emscripten-core/emsdk#1154]
Hi 

I build my game (via emsdk docker) with -Wno-enum-constexpr-conversion but it looks like the emsdk does not support this warning option.

```
error: unknown warning option '-Wno-enum-constexpr-conversion' [-Werror,-Wunknown-warning-option]
```

**Comment by sbc100** [comment]
Which version of emsdk are you using?  The current version of emcc does support this flag.

**Comment by pinguin999** [comment]
I'm using it via the latest docker image.

**Comment by sbc100** [comment]
What does `emcc --version` say?

**Comment by pinguin999** [comment]
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28 (f11d6196dd4e8748a726f19895c859b40ff6a4f3)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

But if it's in there it'S OK for me. I have disabled the warnings in the web build.

**Comment by sbc100** [comment]
Odd, that seems work work fine for me:

```
$ ./emsdk install 3.1.28
$ ./emsdk activate 3.1.28
$ . emsdk_env.sh
$ emcc -Wno-enum-constexpr-conversion ~/test/hello.c -Wall
```

No warning..

**Comment by sbc100** [comment]
I do see the warning on older versions of emsdk so it looks like this is a warning that was introduced relatively recently.

Looks like the oldest version that supports this flags is 3.1.19.. any version before that and clang doesn't support this warning.

**Comment by pinguin999** [comment]
Thanks @sbc100 for your time. Not sure what I messed up in my setup.
