### ISSUE TITLE
the instruction on the website does not work 

### ISSUE THREAD

**Issue by ShaneYokota72** [emscripten-core/emsdk#1157]
when I do "./emsdk activate latest"
it gives me an error 
Resolving SDK version '3.1.28' to 'sdk-releases-upstream-30b9e46ddcea66e91530559379089002d8b692cf-64bit'
error: error: tool is not installed and therefore cannot be activated: 'releases-upstream-30b9e46ddcea66e91530559379089002d8b692cf-64bit'

**Comment by sbc100** [comment]
What platform are you on?

**Comment by ShaneYokota72** [comment]
Im currently on mac

**Comment by ShaneYokota72** [comment]
i just did 
"./emsdk install sdk-releases-upstream-30b9e46ddcea66e91530559379089002d8b692cf-64bit" and it is currently downloading, so I will see how this goes.

**Comment by sbc100** [comment]
Oh I see.. yes you need to do `./emsdk install latest` before your do `./emsdk activate latest`. 

If that solves your problem can we close this issue?

**Comment by ShaneYokota72** [comment]
Just to update on the situation, I solved the problem. 
I did "./emsdk install latest" before running the "activate latest" command, so I do not think that is the issue. Running "./emsdk install sdk-releases-upstream-30b9e46ddcea66e91530559379089002d8b692cf-64bit" then configuring the emsdk in my shell startup scripts solved the issue for me.
