### ISSUE TITLE
Calling compiled C++ function from javaScript

### ISSUE THREAD

**Issue by ShaneYokota72** [emscripten-core/emsdk#1158]
On the website, it does not talk about calling a C++ function that has .txt or .in as an argument. I am currently working on a project that requires a .txt file to be one of the argument, but I cannot figure out how to solve that problem due to the website not having any information about file input argument. Could you please help me with this issue?

`document.getElementById("mybutton").addEventListener("click", () => {
  alert("check console");
  const result = Module.ccall(
    "myFunction", // name of C function
    null, // return type
    null, // argument types
    null // arguments
  );
});`

This is what the website tells us and few more examples, but no cases when a file is the input.

**Comment by ShaneYokota72** [comment]
I've tried other ways i could think of, but none of them worked. So I changed my C++ code to get a string instead of a file, but even when i did that, the format does not seem to work. Are the things that go into argument types and arguments supposed to be considered argv[1] and argv[2] in terms of C++ code? Becuase I tried this, and it did not work for me.

**Comment by sbc100** [comment]
There are several different ways to pass arguments / information to and from JavaScript and C++.  They are documented here:  https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html. 

If you are using the `ccall` and you want to pass a filename then you would want to specify its type as `"string"` and on the C/C++ it would show up as a `const char*` argument.

**Comment by ShaneYokota72** [comment]
So in  the JavaScript file, I would do
`var result = Module.ccall('runmaze', // name of C function
  'null', // return type
  ['string'], // argument types
  [myfile.txt]); // arguments
`

and if my C++ file looks something like
`#include ...
..
..
..
int main(){
return 0;
}

EXTERN EMSCRIPTEN_KEEPALIVE int runmaze(int argc, char* argv[]) {
..
..
ifstream ifile(argv[1]);

// do something with the file

cout << .... << endl;
cout << .... << endl;
return 0;
}`

Then it should work as the same as the myfile.txt being the first command line argument?

**Comment by sbc100** [comment]
> So in the JavaScript file, I would do `var result = Module.ccall('runmaze', // name of C function 'null', // return type ['string'], // argument types [myfile.txt]); // arguments `

I assume you know that `//` comments don't work in the middle of a single line like that?   So you would need to remove the comments or split onto multiple lines.

> 
> and if my C++ file looks something like `#include ... .. .. .. int main(){ return 0; }
> 
> EXTERN EMSCRIPTEN_KEEPALIVE int runmaze(int argc, char* argv[]) { .. .. ifstream ifile(argv[1]);
> 
> // do something with the file
> 
> cout << .... << endl; cout << .... << endl; return 0; }`
> 
> Then it should work as the same as the myfile.txt being the first command line argument?

No, if your function take just a string it would like `EXTERN EMSCRIPTEN_KEEPALIVE int runmaze(const char* filename)  ...`

The argc/argv thing is specific to the `main` function.

Also, once you have sucessfully passed the name of the file to your function you would also need to make sure that the file with that name exists in the emscripten filesystem: https://emscripten.org/docs/api_reference/Filesystem-API.html

**Comment by ShaneYokota72** [comment]
Yes, I do understand that // will not work in the middl eof a sinle line. Sorry about that.

Also, another question to your responce.
`EXTERN EMSCRIPTEN_KEEPALIVE int runmaze(const string filename)  ...`
Would this code work? I believe that chat* and string in C++ is essentially works the same way, so I am just curious if both syntax will work.

**Comment by sbc100** [comment]
No, the "string" type argument in ccall is for `const char*`.   Its trivial to turn that into a C++ once you get it though.

If you want to pass more advanced types such as C++ classes you need to looks a more complex binding solution such as embind.

**Comment by ShaneYokota72** [comment]
Cool. Thank you so much!
