### ISSUE TITLE
'emcc' is not recognized as an internal or external command, executable program or batch file

### ISSUE THREAD

**Issue by iLoveDiep** [emscripten-core/emsdk#1159]
![螢幕擷取畫面 2022-12-29 235548](https://user-images.githubusercontent.com/114549411/209977950-a179f39d-2aa7-4247-bf6c-4450b15551fd.png)

what happens?

**Comment by sbc100** [comment]
that is odd... do you know why non of those emsdk commands seem to have any output?  Command such as `emsdk install latest` should output information.

What does `where emsdk` and `where emcc` output?

**Comment by iLoveDiep** [comment]
I don't know ☹️☹️☹️ It is so amazing. 🤣

(windows 11 laptop)

**Comment by sbc100** [comment]
Can you run `git status`, `dir` and `which emsdk` in the `d:\emsdk-main\emsdk-main` directory and share the output?

**Comment by iLoveDiep** [comment]
Yes I  can  but I gonna sleep 😴
It's midnight now

Good night

**Comment by iLoveDiep** [comment]
![螢幕擷取畫面 2023-01-02 202503](https://user-images.githubusercontent.com/114549411/210231115-e6b1b055-607a-4fd4-ab4e-3e9d78822ca1.png)
D:\emsdk>dir
  Disk in volume D is new volume
  Volume number: D888-A873

  D:\emsdk directory

2023/01/02 at 08:23 PM <DIR> .
2023/01/02 08:23 PM <DIR>.circleci
2023/01/02 pm 08:23 425 .dockerignore
2023/01/02 pm 08:23 441 .flake8
2023/01/02 08:23 PM <DIR>.github
2023/01/02 08:23 PM 505 .gitignore
2023/01/02 08:23 PM <DIR> bazel
2023/01/02 08:23 PM <DIR> docker
2023/01/02 pm 08:23 26 emcmdprompt.bat
2023/01/02 08:23 PM 9,162 emscripten-releases-tags.json
2023/01/02 08:23 pm 1,688 emsdk
2023/01/02 08:23 PM 1,564 emsdk.bat
2023/01/02 08:23 PM 1,436 emsdk.ps1
2023/01/02 08:23 PM 129,918 emsdk.py
2023/01/02 pm 08:23 34 emsdk_env.bat
2023/01/02 pm 08:23 596 emsdk_env.csh
2023/01/02 08:23 pm 316 emsdk_env.fish
2023/01/02 08:23 PM 100 emsdk_env.ps1
2023/01/02 08:23 pm 2,050 emsdk_env.sh
2023/01/02 08:23 PM 32,847 emsdk_manifest.json
2023/01/02 08:23 pm 744 legacy-binaryen-tags.txt
2023/01/02 08:23 PM 1,348 legacy-emscripten-tags.txt
2023/01/02 08:23 PM 1,353 LICENSE
2023/01/02 08:23 PM 2,455 llvm-tags-64bit.txt
2023/01/02 08:23 pm 12,694 README.md
2023/01/02 08:23 PM <DIR> scripts
2023/01/02 08:23 PM <DIR> test
               20 files 199,702 bytes
                7 directories 261,106,601,984 bytes available

D:\emsdk>
(I translate Chinese to English)

**Comment by sbc100** [comment]
What does `where emsdk` report?  What does `where python` report?

Can you try `emsdk install latest` again?  I seems very odd that nothing would be printed at all when you type that.

**Comment by sbc100** [comment]
Have you perhaps not install python?

**Comment by iLoveDiep** [comment]
![螢幕擷取畫面 2023-01-02 204809](https://user-images.githubusercontent.com/114549411/210233432-3e0b0721-c687-408e-9d40-2db87dd0d73a.png)

I think i have installed Python 3.11.1(64-bit),the most files are at D:\Python\

**Comment by sbc100** [comment]
can you try typing `python emsdk.py`?

**Comment by iLoveDiep** [comment]
![螢幕擷取畫面 2023-01-02 205714](https://user-images.githubusercontent.com/114549411/210234412-961c8a7d-51ed-47e7-a805-fc3448c3ecc8.png)

**Comment by sbc100** [comment]
How about `python --version`?

**Comment by iLoveDiep** [comment]
![螢幕擷取畫面 2023-01-02 213013](https://user-images.githubusercontent.com/114549411/210237999-5042be8e-939a-41db-9fce-0dc1ee880530.png)

**Comment by sbc100** [comment]
Its seems you don' t have a working copy of python on your system.  Once you fix that emsdk should work.

**Comment by iLoveDiep** [comment]
:(

Can i get the working copy of python on my system?

**Comment by sbc100** [comment]
I would just google "installing python on windows" and follow the steps.

**Comment by sbc100** [comment]
See https://docs.python.org/3/using/windows.html#using-python-on-windows

**Comment by iLoveDiep** [comment]
![螢幕擷取畫面 2023-01-04 194937](https://user-images.githubusercontent.com/114549411/210548934-bcaccb24-9783-4354-b404-a255b7d69952.png)

Success??😮

**Comment by sbc100** [comment]
yup, looks good.
