### ISSUE TITLE
Create Docker container

### ISSUE THREAD

**Issue by ximet** [emscripten-core/emsdk#116]
I think for this feature need create docker container. But I have some problem with creating:
1) when I call RUN source ../usr/local/emsdk-portable/emsdk_env.sh in Dockerfile, this method update PATH
2) When I run docker, I don't have emcc command and I again run command above, and after everything OK. 

Q: How execute this command source ../usr/local/emsdk-portable/emsdk_env.sh in dockerfile not after start docker

**Comment by saschanaz** [comment]
Not 100% sure, but you may do `ENV PATH="$PATH"` to lock the value after RUN.

**Comment by caian-gums** [comment]
Hey! I'm writing some boilerplate to start using WebAssembly.
Are you interested in some help with this?

**Comment by ximet** [comment]
@caian-gums I had already written docker container in my one repository

**Comment by caian-gums** [comment]
@ximet how you solve this problem? The repository is public?

**Comment by sbc100** [comment]
We not have an official dockerfile in this repo in docker/Dockerfile, which get automatically published to https://hub.docker.com/r/emscripten/emsdk.   You can see who it sets up the environment.
