### ISSUE TITLE
Emscripten 3.1.12 (used by Mono-WASM Net 7.0) increments function pointers on assignment to variables

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [emscripten-core/emsdk#1162]
Hi we have code logically similar to this
```cpp
class MyClass
{
public:
  using FunctionPtrT = void (*)(void);
  static set(FunctionPtrT func);

  static FunctionPtrT static_pFunc;
};

extern "C"
{
void set(FunctionPtrT func)
{
  static_pFunc = func;

  printf("%p\n",func);
  // calls function properly
  func(); 
  // always prints a value +1 relative to `func
  printf("%p\n",static_pFunc);
  // crashes with RuntimeError nullfunction or signature mismatch
  static_pFunc(); 
}
}
```

We DLLImport `set` from C++ into C#.

We print out "START IN C#" and call the `set` with `MonoPInvokeCallback` which is just a static void function not taking any arguments. 

The PInvokeCallback prints "BACK IN C#"

This is what we get in the console
```
START IN C#
2
BACK IN C#
3
RuntimeError: null function or signature mismatch
```

The most hilarious part is that we get the +1 even when we do
```cpp
reinterpret_cast<ptrdiff_t&>(static_pFunc) = reinterpret_cast<const ptrdiff_t&>(func);
```

**Comment by sbc100** [comment]
Are you able to reproduce this purely in C/C++?    If you could make test case that was pure C/C++ that would would be more easier to reproduce.

BTW, is this a regression?  did it used to work in previous version of emscripten?  Perhaps you can bisect to find out exactly when it broke:  https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by sbc100** [comment]
Since `static_pFunc` is global static data,  my only thought is that perhaps you have some kind of memory corruption happening during the call to `func()`?

**Comment by devshgraphicsprogramming** [comment]
> Are you able to reproduce this purely in C/C++? If you could make test case that was pure C/C++ that would would be more easier to reproduce.
> 
> BTW, is this a regression? did it used to work in previous version of emscripten? Perhaps you can bisect to find out exactly when it broke: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

I can't, it only seems to happen on _some_ functions for Directors generated by SWIG.

Also I can't upgrade Net 7.0 to use newer emscripten easily.

The thing that might break it is `--allow-undefined` that NEt 7.0 always emits when linking `dotnet.wasm` with my static libs

**Comment by devshgraphicsprogramming** [comment]
> Since `static_pFunc` is global static data, my only thought is that perhaps you have some kind of memory corruption happening during the call to `func()`?

no it all works, calling `func` is okay

If i perform a `reinterpret_cast<ptrdiff_t&>(static_pFunc)--` I can then use the pointer somehow

I have many suspicions:
- `static_pFunc` getting lost as the code where its defined is part of a `-fpic` `.a` that gets linked with C# runtime
- `static_pFunc` getting mapped to some other global (aliasing)
etc.

I can provide assembly

**Comment by devshgraphicsprogramming** [comment]
> Are you able to reproduce this purely in C/C++? If you could make test case that was pure C/C++ that would would be more easier to reproduce.
> 
> BTW, is this a regression? did it used to work in previous version of emscripten? Perhaps you can bisect to find out exactly when it broke: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

MonoAOT produces a C-language `mono_wasm_to_native_` function for every single `MonoPInvokeCallback`.

the value of `func` printed matches the value of `mono_wasm_to_native_${C# Assembly Name}_${Method Name}` generated for the `MonoPInvokeCallback`

So this is a purely C/C++ case ;)

**Comment by Hazardu** [comment]
It turns out that the issue appears when trying to assign an uninitialized global variable. 

Changing 
```
 static FunctionPtrT static_pFunc;
 ```
 to 
 ```
  static inline FunctionPtrT static_pFunc = nullptr;
  ```
  solves this issue. We found this solution by coincidence, as trying to assign the uninitialized global with the same variable twice also solves the problem of incremented pointer, as the bug happens only on first assignment

**Comment by Hazardu** [comment]
The reason behind this was a use of an uninitialized global variable `static_pFunc`. The value was wrong when we wrote to it for the first time, but if we were to use the assignment operator `static_pFunc = func;` twice, it would work as intended.
The solution was to provide an initial value for the variable 
```
  inline static FunctionPtrT static_pFunc = nullptr;
  ```
  This problem arose, as @devshgraphicsprogramming suspected, because the wasm linker used by dotnet always uses  `--allow-undefined` that suppresses an error that should appear there.
