### ISSUE TITLE
[feature] Upgrade to Node.js 20(LTS)

### ISSUE THREAD

**Issue by DreamOfIce** [emscripten-core/emsdk#1173]
As written in https://github.com/nodejs/release#release-schedule, support for node.js 16 was end in September 2023.
Therefore, it is recommended to upgrade to node.js 20.
Also, many of the features in node.js 20 are enabled by default, such as `--experimental-wasm-threads` and `--experimental-wasm-bulk-memory`.

**Comment by sbc100** [comment]
Moved to `emsdk` since its the emsdk version of node we are talking about upgrading (emscripten itself already supports newer versions).

**Comment by DreamOfIce** [comment]
> Moved to `emsdk` since its the emsdk version of node we are talking about upgrading (emscripten itself already supports newer versions).

Are there any impediments to updating ci's version of Ubuntu? After all, the five-year free support period for Ubuntu 18 is almost up

**Comment by sbc100** [comment]
Yes, there were impediments.  We don't have direct control over the VM.   But I think we have now overcome those.

BTW, according to https://wiki.ubuntu.com/Releases ubunut/bionic 18.04 LTS is supported until April 2028.

The issue of what version of node we use internally in emsdk should really be an implementation detail though.    I think the real issue is that we are putting our internal version of node in the emsdk user's path, and we should focus on fixing that.  Even if/when we update to node v18 that will also be wrong version for many users who have already installed their own.

**Comment by DreamOfIce** [comment]
I agree with this, forcing the specified version of node into path is a very bad idea. We should at least provide an option to use the system node.

Considering that the lifecycle of node.js14 is coming to an end, updating the bundled node version is unavoidable, even if only for security reasons

BTW, the free LTS period for Ubuntu 18 will end in April and paid commercial support for the next five years

**Comment by sbc100** [comment]
> Considering that the lifecycle of node.js14 is coming to an end, updating the bundled node version is unavoidable, even if only for security reasons

I think unavoidable might be too strong a word there.  Perhaps inadvisable.

**Comment by sbc100** [comment]
> Considering that the lifecycle of node.js14 is coming to an end, updating the bundled node version is unavoidable, even if only for security reasons
> 

Emscripten's use of node is as part of the compiler toolchain and as such it does not process untrusted code.   There is no protection at all against hostile user input in emscripten, regardless of node version.  For example `--library-js=foo.js` executes `foo.js` with full user permissions at build time.

**Comment by DreamOfIce** [comment]
> > Considering that the lifecycle of node.js14 is coming to an end, updating the bundled node version is unavoidable, even if only for security reasons
> 
> I think unavoidable might be too strong a word there. Perhaps inadvisable.

You're right, this is indeed a bit too absolute

**Comment by DreamOfIce** [comment]
> Yes, there were impediments. We don't have direct control over the VM. But I think we have now overcome those.
> 
> BTW, according to https://wiki.ubuntu.com/Releases ubunut/bionic 18.04 LTS is supported until April 2028.
> 
> The issue of what version of node we use internally in emsdk should really be an implementation detail though. I think the real issue is that we are putting our internal version of node in the emsdk user's path, and we should focus on fixing that. Even if/when we update to node v18 that will also be wrong version for many users who have already installed their own.

After some changes, I successfully upgrade Ubuntu to 22.04LTS in .circleci/config.yml.The only change is the removal of running flake with python2 and only keeping python3, as installing both pip versions at the same time would report an error. Of course, it's easy to add python2 back if necessary.
Commit and CI status: https://github.com/DreamOfIce/emsdk/commit/d9f78acc974f458936e06e0eb9fa60017d6f81d7

**Comment by zowers** [comment]
Active LTS is 20 already, so probably 18 should be changed to 20 in issue's title

**Comment by sbc100** [comment]
@juj, you mentioned in https://github.com/emscripten-core/emsdk/pull/1183#issuecomment-1422597451 that you still need Ubuntu/Bionic support.  Is this still true?  Any idea when that might come to and end?

**Comment by ab-unity** [comment]
> @juj, you mentioned in [#1183 (comment)](https://github.com/emscripten-core/emsdk/pull/1183#issuecomment-1422597451) that you still need Ubuntu/Bionic support. Is this still true? Any idea when that might come to and end?
Our min-spec is now Ubuntu/Jammy going forward.

**Comment by sbc100** [comment]
> > @juj, you mentioned in [#1183 (comment)](https://github.com/emscripten-core/emsdk/pull/1183#issuecomment-1422597451) that you still need Ubuntu/Bionic support. Is this still true? Any idea when that might come to and end?
> > Our min-spec is now Ubuntu/Jammy going forward.

Sorry I've not seen this account before.. is this jukka?  Or someone else at unity maybe?

**Comment by ab-unity** [comment]
Sorry, I'm Anthony (Eng Manager) from Unity.

**Comment by sbc100** [comment]
Awesome!  Thats great news.   I guess we are free to drop Trusty support and upgrade to node v18+ !

**Comment by juj** [comment]
Hey, thanks for pinging.

Currently Unity's Web CI infrastructure runs on Ubuntu 20.04 LTS Focal Fossa. That should be new enough to run Node v18.

We do no longer need Ubuntu 18.04 LTS Bionic Beaver support, so can happily drop that.
