### ISSUE TITLE
Doesn't install versions of emscripten 1.*

### ISSUE THREAD

**Issue by dy** [emscripten-core/emsdk#1175]
`emsdk install 1.39.10` fails with error:

```
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/65d33d604d3fa0ebe03548378b898fc6608e9cb8/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
error: installation failed!
```

**Comment by sbc100** [comment]
That release was made before we starting building emsdk for arm64 macOS.

You can try running with `EMSDK_ARCH=x86_64` which should force it to download the x86 binaries.

**Comment by dy** [comment]
It helped, thanks!
