### ISSUE TITLE
Is there a particular reason why flake is run in CI with both python2 and python3? 

### ISSUE THREAD

**Issue by DreamOfIce** [emscripten-core/emsdk#1182]
The code is located here: 
https://github.com/emscripten-core/emsdk/blob/main/.circleci/config.yml#L20 

As far as I know, python2 has been out of maintenance for a long time now, is this a historical legacy or is there a special reason?
Can this py2 code be removed?
I recently had problems installing both py2 and 3 pip using apt when trying to update CI to Ubuntu 22.04LTS (removing one first and then installing the other one works fine)

**Comment by sbc100** [comment]
You don't need to install both versions on your machine, but we do test on both for max compatibility. 

IIRC the reason for the continued python2 support is to support macOS users where (until recently) python2 ships with the OS.   If it can be shown that there are vanishing small numbers of such macOS users we could consider removing the python2 support.   But also its just one python script so its not much of big deal for us to support both in this limited context.

Emscripten itself is python3 only.

**Comment by DreamOfIce** [comment]
> You don't need to install both versions on your machine, but we do test on both for max compatibility.
> 
> IIRC the reason for the continued python2 support is to support macOS users where (until recently) python2 ships with the OS. If it can be shown that there are vanishing small numbers of such macOS users we could consider removing the python2 support. But also its just one python script so its not much of big deal for us to support both in this limited context.
> 
> Emscripten itself is python3 only.

Got it, I tried to add python2 after it
