### ISSUE TITLE
installation failed on mac m1

### ISSUE THREAD

**Issue by abuvanth** [emscripten-core/emsdk#1184]
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/665121d026cafc46c29b30d6d4c45ed73eedbb7e/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
error: installation failed!

**Comment by abuvanth** [comment]
<img width="682" alt="Screenshot 2023-02-09 at 11 06 59 AM" src="https://user-images.githubusercontent.com/20999104/217727273-259c7be4-333c-467f-a437-db26d73038aa.png">

**Comment by sbc100** [comment]
That version of the SDK predates out M1 mac builds.   You can try installing the x86_64 binaries by settings `EMSDK_ARCH=x86_64` when you run emsdk.   Or you could use a more recent version of emsdk.. is there some reason you need to use that old version?

**Comment by abuvanth** [comment]
I followed some tutorials thats why i try to install that version.
working fine with latest. 
hence closed
