### ISSUE TITLE
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-win-x64.zip': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again. error: installation failed!

### ISSUE THREAD

**Issue by SirFalc0n** [emscripten-core/emsdk#1185]
When running `emsdk install latest` I get this
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-win-x64.zip': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
error: installation failed!

I have installed python 3.11 and ran the `pip install certifi` command. I still get the same error. 
How do I get around this?

**Comment by sbc100** [comment]
What does `where python` and `where python3` report?

**Comment by SirFalc0n** [comment]
I don't know what that means. The key was to uninstall garbage known as python, reinstall it for all users, then update the pip with the link in the error, then add the roaming python script directory to the system path. 
...AppData\Roaming\Python\Python311\Scripts
That fixed the SSL issue and I was able to finish the install

**Comment by sbc100** [comment]
Glad you found a fix.   In future we should try to make this process even more hermetic so we won't depend on system python at all.

**Comment by SirFalc0n** [comment]
@sbc100 That would be epic.

**Comment by easybakelovin** [comment]
reinstalled python and it worked. Also took the opportunity to clean up old python installs..
