### ISSUE TITLE
What libcxx version does emsdk use?

### ISSUE THREAD

**Issue by Guyutongxue** [emscripten-core/emsdk#1192]
I want to use some C++20 feature in emsdk. Here is my code:

```cpp
#include <algorithm>
int main() {
  int a[3]{}, b[3]{};
  std::ranges::copy(a, b);
}
```
While `em++ -std=c++20 a.cpp` got errors:

```
a.cpp:4:15: error: no member named 'copy' in namespace 'std::ranges'
        std::ranges::copy(a, b);
        ~~~~~~~~~~~~~^
1 error generated.
em++: error: '/home/guyutongxue/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/home/guyutongxue/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -std=c++20 a.cpp -c -o /tmp/emscripten_temp_gy6zgg3w/a_0.o' failed (returned 1)
```

Seems that Clang 17.0 is using behind (`em++ -v`):
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.33-git (5763b39315edb54507b3e923a2aa99460fa52917)
clang version 17.0.0 (https://github.com/llvm/llvm-project 639fc00b2ddcb32dd9d67a4f4471dbe92b697223)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/guyutongxue/emsdk/upstream/bin
```

But [godbolt.org](https://godbolt.org/z/qGKebf8dx) shows that Clang 15.0 is OK with this code. Maybe emsdk is using an older version of libcxx? Anyway to update it?

**Comment by sbc100** [comment]
emscripten uses the current stable llvm release for libcxx and libcxxabi and compiler-rt.  See https://github.com/emscripten-core/emscripten/blob/5763b39315edb54507b3e923a2aa99460fa52917/system/lib/libcxx/readme.txt#L4.

Right now llvm stable is version 15, but version 16 is due to be released soon IIUC:  https://releases.llvm.org/

**Comment by Guyutongxue** [comment]
Wait, seems that "Rangify algorithm" is [supported](https://libcxx.llvm.org/Status/Cxx20.html) since libcxx 15.0...

The godbolt link above is also Clang 15.0.

The latest emscripten uses 15.0.7, which means the code should compiles under it. But actually it does not.

**Comment by sbc100** [comment]
If you add `-stdlib=libc++` you get the same error on godbolt as with emscripten.

**Comment by sbc100** [comment]
(I guess godbolt clang used libstdc++ by default?)

**Comment by Guyutongxue** [comment]
Oops, found that libcxx needs `-fexperimental-library` flag to enable ranges library. Problem solved.
