### ISSUE TITLE
pkg-config isn't finding pc files

### ISSUE THREAD

**Issue by flatmax** [emscripten-core/emsdk#1193]
I installed latest          3.1.32             INSTALLED

I've been installing packages, such as fftw and emscripten can't seem to find the pc files.
I look at the emsdk/upstream/emscripten/system/lib/pkgconfig and I can see the pc files :
# ls fftw3f.pc
fftw3f.pc

But the autotools configure script can't find it. If I try to run the following :
$ emconfigure pkg-config --cflags fftw3f
No package 'fftw3f' found

Previously this problem wasn't happening with version 2.0.12 which was the last known good for me.

**Comment by sbc100** [comment]
emscripten is going to be looking for pkg-config files inside the sysroot.  So that would be in `emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig`.

**Comment by sbc100** [comment]
The files in `system/lib/pkgconfig` get installed into the sysroot when it gets build (just like the headers in `system/include` get installed into `sysroot/include`).

**Comment by flatmax** [comment]
Any ideas why an autotools package would fail to find the pc files in the right location ? Any ideas for ways to check where the autotools paths to look for pc files ?

**Comment by flatmax** [comment]
ok - I have done some more tests. It seems that the "emscripten make install" command only lands the pc files in :
upstream/emscripten/system/lib/pkgconfig
They don't appear in 
upstream/emscripten/system/lib/pkgconfig

Is there a command to run to make this copy to cache happen ?

Below are example find commands ...

For the emscriptend make install process, the fftw3.pc file is only landing 
flatmax@dev:emsdk$ find . -name 'fftw3.pc'
./upstream/emscripten/system/lib/pkgconfig/fftw3.pc

flatmax@dev:emsdk$ find . -name 'egl.pc'
./upstream/emscripten/system/lib/pkgconfig/egl.pc
./upstream/emscripten/cache/sysroot/lib/pkgconfig/egl.pc

**Comment by flatmax** [comment]
When I configure the package for building I do the following :
```
export EMSCRIPTEN=$EMSDK/upstream/emscripten
emconfigure ./configure --prefix=$EMSCRIPTEN/system
```

Is there a better way to configure with the path pointing at cache/sysroot ?
Are there any bad points to installing directly to sysroot rather then system ?

**Comment by flatmax** [comment]
all good now.
