### ISSUE TITLE
3.1.30 linux/arm64 is missing wasm-binaries-arm64.tbz2

### ISSUE THREAD

**Issue by radekdoulik** [emscripten-core/emsdk#1202]
I tried to use emscripten 3.1.30 on linux/arm64 and it looks like the binaries are missing. I tried other versions and it looks like 3.1.21 is the last working.

```
Installing tool 'releases-dc1fdcfd3f5b9d29cb1ebdf15e6e845bef9b0cc1-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/dc1fdcfd3f5b9d29cb1ebdf15e6e845bef9b0cc1/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
error: installation failed!
```

**Comment by sbc100** [comment]
Indeed,  the process for updating the arm binaries is not yet automatic or smooth.

You can use `./emsdk install latest-arm64-linux` to get the latest binaries.  See https://github.com/emscripten-core/emsdk/blob/60cd167fbf4599efd1cca4c8fd9348e2e8c1df3f/emscripten-releases-tags.json#L5

**Comment by radekdoulik** [comment]
I see, thanks for the information.

I needed specific version for our benchmarks, as we switched dotnet/runtime to emscripten 3.1.30 recently and I didn't noticed linux/arm64 version is not available. I solved it meanwhile by building it from source on our measurement machine.
