### ISSUE TITLE
Docker image for ARM64 (Apple Silicon)

### ISSUE THREAD

**Issue by CodeWitchBella** [emscripten-core/emsdk#1206]
I discovered that official docker images at [emscripten/emsdk](https://hub.docker.com/r/emscripten/emsdk) only have AMD64 builds of emscripten. So while they work on apple's M1/M2, they are much slower than native. There are ARM64 builds of emsdk available (#547), so it shouldn't be hard at this point to produce docker images. I tried running `make version=3.1.33` in `docker` directory of this repo on my macbook and it produced an image which is ARM64. I did not yet have time to test if it works.

#1000 is closed as duplicate of #547, but it is not solved yet. It was more like a prerequisite than a solution.

While I can build the image myself, it would be much more convenient, if there was a prebuilt image of emscripten readily available. Could we get the community build bot to also push docker images?

**Comment by CodeWitchBella** [comment]
According to [this](https://docs.docker.com/build/building/multi-platform/), it should be enough to specify `--platform linux/arm64` with the docker build command and push that. That assumes that you have working QEMU platform emulation (true for docker desktop but not necessarily for docker installed from Linux packages, I think). Then I assume that you can just push that to the registry and it will add new platform to the existing image, but I never actually tried this.

Anyway, thanks for the quick response. Much appreciated 🙂

**Comment by lesomnus** [comment]
```
docker buidx build --platform linux/amd64,linux/arm64 --push ...
```
will build both _amd64_ and _arm64_ image in a single manifest and it will push automatically after build finished.
Im looking forward to get _arm64_ `emscripten/emsdk` on DockerHub soon.
Thanks for your work.
