### ISSUE TITLE
M1 Macbook Pro __APPLE__ is 0

### ISSUE THREAD

**Issue by xiaoxiaojx** [emscripten-core/emsdk#1228]
Recently, when I compiled a C program into wasm, the compilation reported a lot of errors that the type could not be found, and the compilation was successful using make directly. I found that the `__APPLE__` macro has a value of 0 and `__unix__` has a value of 1 when compiling with emmake. When using make directly, the value of the `__APPLE__` macro is 1

I am a beginner in C language,  thanks for answer  :) 
![image](https://github.com/emscripten-core/emsdk/assets/23253540/df3c7f91-7759-46e6-88a1-d327d68a0152)

**Comment by xiaoxiaojx** [comment]
@sbc100 ❤️  Thank you for your patient answer, I seem to understand!  Below is the code for a library I'm trying to compile, unless the program also adds support for `__unix__`, I won't be able to compile it will it?

```c
#ifndef CCAT_TYPEDEF_H
#define CCAT_TYPEDEF_H

#if defined WIN32

typedef unsigned char u_char;
typedef unsigned char u_int8;
typedef unsigned short u_int16;
typedef unsigned int u_int32;
typedef unsigned __int64 u_int64;
typedef signed char int8;
typedef signed short int16;
typedef signed int int32;
typedef signed __int64 int64;

#elif defined __linux__ || defined __APPLE__

typedef unsigned char u_char;
typedef unsigned char u_int8;
typedef unsigned short u_int16;
typedef unsigned int u_int32;
typedef unsigned long long u_int64;
typedef signed char int8;
typedef signed short int16;
typedef signed int int32;
typedef long long int64;

#endif

#endif //CCAT_TYPEDEF_H
```

**Comment by sbc100** [comment]
You would need to add `|| defined __EMSCRIPTEN__` to the `elif` clause.. or simply replace it with `#else`.

**Comment by xiaoxiaojx** [comment]
@sbc100 I understand, thanks again ❤️
