### ISSUE TITLE
sdk-fastcomp-tag-1.38.21-64bit

### ISSUE THREAD

**Issue by jChavezCac** [emscripten-core/emsdk#1252]
Hi, 
I am trying to run "emsdk install sdk-fastcomp-tag-1.38.21-64bit", but I get this error: 
"the fastcomp backend is no longer supported. Please use an older version of emsdk (for example 3.1.29) if you want to install the old fastcomp-based SDK ."
I tried to install the suggested version but it is not available either. My project needs the version sdk-fastcomp-tag-1.38.21-64bit. Could you please provide me with the tag or release from where I can install it? 

Thank you!

**Comment by sbc100** [comment]
If you do `git checkout 3.1.29` in your emsdk directory you should then be able to do `emsdk install sdk-fastcomp-tag-1.38.21-64bit`.  I just tried it and it worked for me.
