### ISSUE TITLE
The v16 of Node.js is end of support, any plan?

### ISSUE THREAD

**Issue by lovebaihezi** [emscripten-core/emsdk#1278]
With the OpenSSL 1.1.1 is end of support on Sep 11th, 2023 [OpenSSL blog](https://www.openssl.org/policies/releasestrat.html), Node.js v16, which relay on OpenSSL 1.1.1, also end of support [NodeJS Blog](https://nodejs.org/en/blog/announcements/nodejs16-eol). 
Is there any plan for Node.JS updating?

**Comment by sbc100** [comment]
emscripten itself will continue to support outputing code that runs on older versions of node for quite a while.  We currently support node versions as old as 10.19.0 in this context.

The version of node we ship as part of emsdk should really be seen as more of an internal implementation detail of emsdk.  We pick the version based on maximizing the number of places that emsdk can be installed.   IIRC node v18 dropped support for the version of glibc used in ubuntu/bionic, so there would have to be a compelling reason to update which would justify dropping support for those users.

Is there some particular reason you care about the version of node we use internally in emsdk?  Are you using to run your own code/tests perhaps?

**Comment by sbc100** [comment]
See https://github.com/emscripten-core/emsdk/issues/1173 for more on this

**Comment by sbc100** [comment]
Actually we can probably close this as a dup of #1173?
