### ISSUE TITLE
Resume failed install from source after missing dependency without recompiling everything

### ISSUE THREAD

**Issue by Akinetopsia1** [emscripten-core/emsdk#1283]
I couldn't find a discussion section, so posting here even though this is more of a question.

precompiled installs are not available on raspberry pi and takes 6-7 hours to compile, only to fail at the end because of missing dependencies that aren't tested for at the beginning.

Fixing those and reissuing the emsdk install command **_recompiles everything_** that was already compiled successfully, again.

I am now at my 3rd attempt, using older commits closer to my Buster release (I can't really upgrade for that project). Short of setting up a cross compiler to make things faster (but that's its own can of worms) Is there any way to resume the install from what was already done ? 99% of it was successful

I glanced at the code for command switches but it doesn't appear to have anything that would allow resume - it wants to redo everything

*******************************

Edit: i found all the output files in /emscripten/main/, managed to get those running, ~~but now i have the issue that clang / llvm is very outdated (LLVM version for clang executable "/usr/bin/clang" appears incorrect (seeing "7.0", expected "18"))~~
nm, llvm is also compiled. That was from the default config. In short things were compiled but not installed so i have to point to the specific bin folders in my source folder, as the install is not complete.

I'm trying to compile stellarium-web for an astronomy project, trying to do so I get ```emcc: error: linker setting ignored during compilation: 'MODULARIZE'``` 

Googling, it may rely on version 1.40.1 so i'll have to start over anyway.

I think i'm just going to call it a day.

**Comment by sbc100** [comment]
Is there some reason you can't use the pre-compiled arm64/linux binaries?   We don't provide them for all releases but we update them from time to time.  You can install the latest binaries that we ship using `emsdk install latest-arm64-linux`, and you can see what version they correspond to here: https://github.com/emscripten-core/emsdk/blob/d42c740aa51b961d6e18b649754d2cae8807a277/emscripten-releases-tags.json#L5

Out of interest why are you interested in running the build on a raspberry pi?  Do you not have a more powerful laptop or desktop to run on, or is there some other reason?

**Comment by Akinetopsia1** [comment]
I'm using a 32bit 3rd-party raspberry image geared for astronomy, and the precompiled versions are not provided. I thought i mentioned it but i might've edited out by mistake.

As for why i was trying to comple on the pi from source, i then needed to compile stellarium-web-engine, which requires it to then build some native components from what i gathered.

In the end i opted to try stellarium-web first on an ubuntu vm, turns out it compiles but has a bunch of errors itself (blocked CORS requests and reliance on outdated VueJS making their examples non-functional. 

At that point i gave up, found a vamilla javascript library (virtualSky) that took 30 seconds to setup and get running.
