### ISSUE TITLE
fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by juj** [emscripten-core/emsdk#13]
On Windows, git may fail with an error message `fatal: Unable to find remote helper for 'https'` when cloning a repository with `https://` url. 

This appears to be due to the portable git installation that emsdk ships with isn't built with https support enabled.

As a workaround, installing Git for Windows from http://msysgit.github.io and uninstalling git from emsdk allows emsdk to clone https URLs.

**Comment by arumuganainar73** [comment]
× Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):


        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t
        https://github.com/danwilson/google-analytics-plugin.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\.....\AppData\Roaming\npm-cache\_logs\2017-09-08T09_16_04_983Z-debug.log

**Comment by juj** [comment]
This could be #5346

**Comment by richdenis86** [comment]
try to use another "git.exe"  in  cmd directory! 
it worked for me!
