### ISSUE TITLE
Prompt when executing the emcc command: ImportError: No module named tools.toolchain_profiler

### ISSUE THREAD

**Issue by Jsnows** [emscripten-core/emsdk#130]
I install it according to the official installation method, and the following is my Installation Tips:
```js
$ git clone https://github.com/juj/emsdk.git
$ cd emsdk
$ ./emsdk install latest

Installing SDK 'sdk-1.37.28-64bit'..
Installing tool 'clang-e1.37.28-64bit'..
The contents of file 'llvm/tag/osx_64bit/emscripten-llvm-e1.37.28.tar.gz' already exist in destination '/Users/cuiqiongxue/Desktop/emsdk/clang/e1.37.28_64bit', skipping.
Done installing tool 'clang-e1.37.28-64bit'.
Installing tool 'node-8.9.1-64bit'..
The contents of file 'node-v8.9.1-darwin-x64.tar.gz' already exist in destination '/Users/cuiqiongxue/Desktop/emsdk/node/8.9.1_64bit', skipping.
Done installing tool 'node-8.9.1-64bit'.
Installing tool 'emscripten-1.37.28'..
The contents of file 'https://github.com/kripken/emscripten/archive/1.37.28.tar.gz' already exist in destination '/Users/cuiqiongxue/Desktop/emsdk/emscripten/1.37.28', skipping.
Done installing tool 'emscripten-1.37.28'.
Done installing SDK 'sdk-1.37.28-64bit'.

$ ./emsdk activate latest

Writing .emscripten configuration file to user home directory /Users/cuiqiongxue/
The Emscripten configuration file /Users/cuiqiongxue/.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='/Users/cuiqiongxue/Desktop/emsdk/clang/e1.37.28_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/cuiqiongxue/Desktop/emsdk/clang/e1.37.28_64bit/optimizer'
BINARYEN_ROOT='/Users/cuiqiongxue/Desktop/emsdk/clang/e1.37.28_64bit/binaryen'
NODE_JS='/Users/cuiqiongxue/Desktop/emsdk/node/8.9.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/cuiqiongxue/Desktop/emsdk/emscripten/1.37.28'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/var/folders/h3/4x2_gss17wzdv15khvvx16_r0000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

/Users/cuiqiongxue/Desktop/emsdk:/Users/cuiqiongxue/Desktop/emsdk/clang/e1.37.28_64bit:/Users/cuiqiongxue/Desktop/emsdk/node/8.9.1_64bit/bin:/Users/cuiqiongxue/Desktop/emsdk/emscripten/1.37.28
Set the following tools as active:
   clang-e1.37.28-64bit
   node-8.9.1-64bit
   emscripten-1.37.28

$ source ./emsdk_env.sh --build=Release

Setting environment variables:
EMSDK = /Users/cuiqiongxue/Desktop/emsdk

$ emcc
Traceback (most recent call last):
  File "/Users/cuiqiongxue/Desktop/emsdk/emscripten/1.37.28/emcc", line 5, in <module>
    from tools.toolchain_profiler import ToolchainProfiler
ImportError: No module named tools.toolchain_profiler
```
`Python v-2.7.10`
This is all the information at the time of installation

**Comment by Kelier** [comment]
i also met the problem yesterday

**Comment by juj** [comment]
Hmm, I recall in the past that someone was getting this kind of profiler error when for some reason unzipping the `emscripten` directory had failed. If you don't have any custom changes to the directory, you can try just `rm -rf emscripten` in the emsdk installation directory and reissue `emsdk install latest`.

Does the file `/Users/cuiqiongxue/Desktop/emsdk/emscripten/1.37.28/tools/toolchain_profiler.py` exist and look ok? That has the contents of the module `tools.toolchain_profiler`.

Also,  when using `emsdk activate latest`, passing `--build=Release` in `source ./emsdk_env.sh --build=Release` is not needed, so you could try just `source ./emsdk_env.sh` there, although I don't know if that makes any difference (would be a bug if it did)

**Comment by chemlynx** [comment]
I can confirm that when I had the issue removing the emscripten directory and re-installing solved it for me.

**Comment by Y0QIN** [comment]
@juj 
 I had the issue removing the emscripten directory and re-installing solved it.
Then another exception occurred:
Traceback (most recent call last):
File "/root/emsdk/emscripten/1.38.31/tools/jsrun.py", line 160, in 
from . import shared
ImportError: cannot import name 'shared'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/emsdk/emscripten/1.38.31/emcc.py", line 41, in 
from tools import shared, system_libs, client_mods, js_optimizer, jsrun
File "/root/emsdk/emscripten/1.38.31/tools/shared.py", line 31, in 
from . import jsrun, cache, tempfiles, colored_logger
File "/root/emsdk/emscripten/1.38.31/tools/jsrun.py", line 163, in 
import shared
ImportError: No module named 'shared'

**Comment by shirofuji** [comment]
I am having the jsrun issue as well. any updates on this?

**Comment by sbc100** [comment]
What version of emscripten are you trying to run?  jsrun.py no longer exists in recent versions of emscripten

**Comment by shirofuji** [comment]
For me I am running it from HTML5Setup.sh of UE4-4.24-HTML5, which downloads emsdk-1.39.18

**Comment by eatcosmos** [comment]
reinstall seems ok
# Get the emsdk repo
git clone https://github.com/emscripten-core/emsdk.git $HOME/OneDrive/Code/apps/emsdk

# Enter that directory
cd $HOME/OneDrive/Code/apps/emsdk

# Fetch the latest version of the emsdk (not needed the first time you clone)
git pull

# Download and install the latest SDK tools.
$HOME/OneDrive/Code/apps/emsdk/emsdk install latest

# Make the "latest" SDK "active" for the current user. (writes .emscripten file)
$HOME/OneDrive/Code/apps/emsdk/emsdk activate latest

# Activate PATH and other environment variables in the current terminal
source $HOME/OneDrive/Code/apps/emsdk/emsdk_env.sh
