### ISSUE TITLE
Fresh Install Fails on Node v16.20 tar.xz

### ISSUE THREAD

**Issue by JVGA8837** [emscripten-core/emsdk#1304]
Upon performing a fresh install when using the command: ./emsdk install latest it fails and outputs:
```
./emsdk install latest
Resolving SDK alias 'latest' to '3.1.49'
Resolving SDK version '3.1.49' to 'sdk-releases-bd0a2e230466dadb36efc71aa7271f17c6c35420-64bit'
Installing SDK 'sdk-releases-bd0a2e230466dadb36efc71aa7271f17c6c35420-64bit'..
Installing tool 'node-16.20.0-64bit'..
Downloading: /home/jvga/emsdk/downloads/node-v16.20.0-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v16.20.0-linux-x64.tar.xz, 22559772 Bytes
Unpacking '/home/jvga/emsdk/downloads/node-v16.20.0-linux-x64.tar.xz' to '/home/jvga/emsdk/node/16.20.0_64bit'
xz: (stdin): Unexpected end of input
tar: Child returned status 1
tar: Error is not recoverable: exiting now
['tar', '-xf', '/home/jvga/emsdk/downloads/node-v16.20.0-linux-x64.tar.xz', '--strip', '1'] failed with error code 2!
error: installation failed!
```
Not sure what else to add to this issue, also happens with ./emsdk install tot.
Any help is appreciated!

**Comment by JVGA8837** [comment]
Running tar xf ./node-v16.20.0-linux-x64.tar.xz results in:
```
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
Checking the sha1sum results in:
`
7c2aa0d2ba7001cbeb5155f5e5f5f3dd3c2649d5  ./node-v16.20.0-linux-x64.tar.xz`

**Comment by sbc100** [comment]
Somehow that file has become corrupt or was not downloaded correctly.

Can you try `./emsdk install latest` again?  Does it repeatedly fail in the same way?

If you run `wget https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v16.20.0-linux-x64.tar.xz` do you get the correct checksum (2803b14612f1bb59fcc9e7ce2a1ef9000745c733)?

**Comment by JoyBinY** [comment]
apt install xz-utils
