### ISSUE TITLE
Uncaught (in promise) TypeError: import object field 'wasi_snapshot_preview1' is not an Object

### ISSUE THREAD

**Issue by vault-thirteen** [emscripten-core/emsdk#1321]
I have built a *.wasm file as a stand-alone WASM without an entry function. The `--no-entry` argument is passed to the tool. But for some reason, when I try to load this WASM file into a web browser, I have an error:
`Uncaught (in promise) TypeError: import object field 'wasi_snapshot_preview1' is not an Object`

How I compiled the file.
```
emcmake cmake . -B "_BUILD_" -G "MinGW Makefiles"
emmake cmake --build _BUILD_
cd _BUILD_
emcc libargon2.a -o argon2.wasm --no-entry -s EXPORTED_FUNCTIONS=["_argon2_ctx","_argon2_encodedlen","_argon2_error_message","_argon2_hash","_argon2_type2string","_argon2_verify","_argon2_verify_ctx","_argon2d_ctx","_argon2d_hash_encoded","_argon2d_hash_raw","_argon2d_verify","_argon2d_verify_ctx","_argon2i_ctx","_argon2i_hash_encoded","_argon2i_hash_raw","_argon2i_verify","_argon2i_verify_ctx","_argon2id_ctx","_argon2id_hash_encoded","_argon2id_hash_raw","_argon2id_verify","_argon2id_verify_ctx"]
```

The source code is here: https://github.com/vault-thirteen/argon2
The JS loader is located here: https://github.com/vault-thirteen/argon2/tree/main/wasm
It is super simple, just a loader and nothing else.

It looks like the WASM file was compiled for a WASI runtime environment according to the error.
But I compiled it for a web browser. What is wrong ? 
Thank you.

**Comment by sbc100** [comment]
If you want to see which imports your progam needs you can inspect the imports section using a tools such as `wasm-dis` (from binaryen) or wasm2wat (from wabt).   The fact that wasi_snapshot_preview1 is being imported means you program depends on at least one WASI system call.

**Comment by sbc100** [comment]
The more complex a program, and the more part of libc it depends on the more likely it is to end up depending on import from the outside world.

**Comment by vault-thirteen** [comment]
Thank you.
