### ISSUE TITLE
how to install sdl2,boost_header when i offline

### ISSUE THREAD

**Issue by deloverzeus** [emscripten-core/emsdk#1348]
When i use flag -s USE_SDL=2 or -s USE_BOOST_HEADER=1，it will download sdl2 or boost_header.But sometime my internet doesn't work.
So I have download sdl2 and boost_header in  my local disk, how to install them offline when i execute -s USE_SDL=2

**Comment by sbc100** [comment]
You can use `embuilder` to download and build any libraries you might need.   e.g. `./embuilder build sdl2`

**Comment by deloverzeus** [comment]
> You can use `embuilder` to download and build any libraries you might need. e.g. `./embuilder build sdl2`

thx
