### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by Awerty16** [emscripten-core/emsdk#1349]
Resolving SDK version '3.1.53' to 'sdk-releases-e5523d57a0e0dcf80f3b101bbc23613fcc3101aa-64bit'
error: error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'

**Comment by sbc100** [comment]
What command are you typing int to get that error?

What platform (OS and architecture) are you running on?

**Comment by Awerty16** [comment]
> What command are you typing int to get that error?
> It is a script that adds html 5 packaging to unreal engine
> What platform (OS and architecture) are you running on?
Windows 11 64-bit

**Comment by sbc100** [comment]
If its a unity issue then perhaps @juj has some clue.

I can't think why node would not be installed as part of the SDK.   Did you include the full output?

**Comment by Awerty16** [comment]
Here is the full output:Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch:19: trailing whitespace.

Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch:29: trailing whitespace.

Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch:260: trailing whitespace.
                "Lumin",
Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch:428: trailing whitespace.

Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch:448: trailing whitespace.
#include "WebSocketNetworkingSettings.h"
warning: squelched 114 whitespace errors
warning: 119 lines add whitespace errors.
/c/Users/Aiden/Documents/UE4 Source/Engine/Platforms/HTML5
Resolving SDK version '3.1.53' to 'sdk-releases-e5523d57a0e0dcf80f3b101bbc23613fcc3101aa-64bit'
error: error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'

**Comment by GabrielWitte** [comment]
Hi, I'm also having this problem. Do you have any news about it?

**Comment by juj** [comment]
> error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'

> It is a script that adds html 5 packaging to unreal engine

Maybe that script has a missing `emsdk install node-16.20.0-64bit` line, or something along those lines? You can try running that command manually.

**Comment by Awerty16** [comment]
When I run that it says: Skipped installing node-16.20.0-64bit, already installed.

**Comment by juj** [comment]
Hmm, if you then manually then run `emsdk activate node-16.20.0-64bit`, does it give that same error `error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'`?

**Comment by Awerty16** [comment]
it's giving me the same error as before

**Comment by Awerty16** [comment]
When I look at the environment variables it doesn't look like emsdk isn't there though.

**Comment by juj** [comment]
If `emsdk install node-16.20.0-64bit` gives an error
```
Skipped installing node-16.20.0-64bit, already installed.
```
but then `emsdk activate node-16.20.0-64bit` gives
```
error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'
```
then that does suggest some kind of problem with emsdk.

I see the path name is of form `/c/Users/Aiden`, so this is inside WSL, MinGW or Cygwin shell? I wonder if that might be part of the trouble that Emsdk is having (such environments are not tested by the CI).

What do you have under the `emsdk/node/16.20.0_64bit` subdirectory in your installation?

The expected contents should look something like
```
C:\emsdk\node>dir
 Volume in drive C has no label.
 Volume Serial Number is 8847-8E7D

 Directory of C:\emsdk\node

03/06/2024  11:47 AM    <DIR>          .
03/06/2024  11:47 AM    <DIR>          ..
11/27/2023  02:33 PM    <DIR>          16.20.0_64bit
               0 File(s)              0 bytes
               3 Dir(s)  211,437,101,056 bytes free

C:\emsdk\node>cd 16.20.0_64bit

C:\emsdk\node\16.20.0_64bit>dir
 Volume in drive C has no label.
 Volume Serial Number is 8847-8E7D

 Directory of C:\emsdk\node\16.20.0_64bit

11/27/2023  02:33 PM    <DIR>          .
11/27/2023  02:33 PM    <DIR>          ..
11/27/2023  02:33 PM                20 .emsdk_version
11/27/2023  02:33 PM    <DIR>          bin
               1 File(s)             20 bytes
               3 Dir(s)  211,392,344,064 bytes free

C:\emsdk\node\16.20.0_64bit>type .emsdk_version
node-16.20.0-64bit

C:\emsdk\node\16.20.0_64bit>cd bin

C:\emsdk\node\16.20.0_64bit\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 8847-8E7D

 Directory of C:\emsdk\node\16.20.0_64bit\bin

11/27/2023  02:33 PM    <DIR>          .
11/27/2023  02:33 PM    <DIR>          ..
11/27/2023  02:33 PM            56,760 CHANGELOG.md
11/27/2023  02:33 PM               334 corepack
11/27/2023  02:33 PM               218 corepack.cmd
11/27/2023  02:33 PM             3,033 install_tools.bat
11/27/2023  02:33 PM            94,619 LICENSE
11/27/2023  02:33 PM        62,704,248 node.exe
11/27/2023  02:33 PM               702 nodevars.bat
11/27/2023  02:33 PM            10,630 node_etw_provider.man
11/27/2023  02:33 PM    <DIR>          node_modules
11/27/2023  02:33 PM             1,365 npm
11/27/2023  02:33 PM               483 npm.cmd
11/27/2023  02:33 PM             1,567 npx
11/27/2023  02:33 PM               539 npx.cmd
11/27/2023  02:33 PM            36,154 README.md
              13 File(s)     62,910,652 bytes
               3 Dir(s)  211,386,060,800 bytes free
```

If that subdirectory might be partially installed for some reason, one thing you can try is to manually delete that subdirectory and retry with the emsdk install step again, followed by the emsdk activate step.

**Comment by Awerty16** [comment]
Yeah, mine shows the same thing but I'll try reinstalling.

`Microsoft Windows [Version 10.0.22631.3007]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Aiden>cd C:\emsdk\node

C:\emsdk\node>dir
 Volume in drive C has no label.
 Volume Serial Number is A8D3-796A

 Directory of C:\emsdk\node

03/05/2024  07:50 PM    <DIR>          .
03/05/2024  07:51 PM    <DIR>          ..
03/05/2024  07:50 PM    <DIR>          16.20.0_64bit
               0 File(s)              0 bytes
               3 Dir(s)  859,610,902,528 bytes free

C:\emsdk\node>cd 16.20.0_64bit

C:\emsdk\node\16.20.0_64bit>dir
 Volume in drive C has no label.
 Volume Serial Number is A8D3-796A

 Directory of C:\emsdk\node\16.20.0_64bit

03/05/2024  07:50 PM    <DIR>          .
03/05/2024  07:50 PM    <DIR>          ..
03/05/2024  07:50 PM                20 .emsdk_version
03/05/2024  07:50 PM    <DIR>          bin
               1 File(s)             20 bytes
               3 Dir(s)  859,610,894,336 bytes free

C:\emsdk\node\16.20.0_64bit>type .emsdk_version
node-16.20.0-64bit

C:\emsdk\node\16.20.0_64bit>cd bin

C:\emsdk\node\16.20.0_64bit\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is A8D3-796A

 Directory of C:\emsdk\node\16.20.0_64bit\bin

03/05/2024  07:50 PM    <DIR>          .
03/05/2024  07:50 PM    <DIR>          ..
03/05/2024  07:50 PM            56,760 CHANGELOG.md
03/05/2024  07:50 PM               334 corepack
03/05/2024  07:50 PM               218 corepack.cmd
03/05/2024  07:50 PM             3,033 install_tools.bat
03/05/2024  07:50 PM            94,619 LICENSE
03/05/2024  07:50 PM        62,704,248 node.exe
03/05/2024  07:50 PM               702 nodevars.bat
03/05/2024  07:50 PM            10,630 node_etw_provider.man
03/05/2024  07:50 PM    <DIR>          node_modules
03/05/2024  07:50 PM             1,365 npm
03/05/2024  07:50 PM               483 npm.cmd
03/05/2024  07:50 PM             1,567 npx
03/05/2024  07:50 PM               539 npx.cmd
03/05/2024  07:50 PM            36,154 README.md
              13 File(s)     62,910,652 bytes
               3 Dir(s)  859,611,164,672 bytes free

C:\emsdk\node\16.20.0_64bit\bin>C:\emsdk\node`

**Comment by Awerty16** [comment]
I tried reinstalling by deleting the node folder and still the same error:error: tool is not installed and therefore cannot be activated: 'node-16.20.0-64bit'

**Comment by sbc100** [comment]
I think @juj is right and `/c/Users/Aiden/` is the key clue here, and cynwin/mingw/wsl is likely the issue here.   Are you running some / or of these command in one of these environments?   Can you try using the normal windows shell to see if that fixes the issue?

**Comment by Awerty16** [comment]
Yeah I am using Git Bash and typing in ./HTML5Setup.sh to run the file. How would I run a sh file on normal windows shell?

**Comment by Awerty16** [comment]
I think Git Bash is the only way to do it

**Comment by sbc100** [comment]
I imagine that `HTML5Setup.sh` is not designed for use on windows.  There is most likely another way to setup on windows.   @juj can confirm,

**Comment by Awerty16** [comment]
This Person does it in a tutorial at 6:30 :https://www.youtube.com/watch?v=vCfXeYRll_E&t=590s
I can try doing this on my mac though.

**Comment by GabrielWitte** [comment]
I managed to solve this problem by doing everything using Git. 

I know this isn't the topic for this. But I'm having problems compiling in Visual Studio, after completing all these steps.

PS: I'm from Brazil so my VS is returning in PT-BR.

Gravidade Código Descrição Projeto Arquivo Linha Estado de Supressão Detalhes
Erro CS0006 Arquivo de origem "C:\Users\User\Desktop\EU4Web\ue-4.27-html5-es3\Engine\Binaries\DotNET\AutomationScripts\HoloLens\HoloLens.Automation.dll" não pode ser encontrado AutomationTool C:\Users\User\Desktop\EU4Web\ue-4.27-html5-es3\Engine\Source\Programs\AutomationTool\CSC 1 Ativo

**Comment by sbc100** [comment]
Closing this out as this seems like more of unity issue, and it looks like you solved the original issue now.

Feel free to re-open if you think there is more to resolve here.

**Comment by juj** [comment]
> as this seems like more of unity issue

(this was a Unreal Engine 4 problem, e.g. `It is a script that adds html 5 packaging to unreal engine` and  `UE4 Source/Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch`. Unreal is a competitor to Unity)

**Comment by sbc100** [comment]
> > as this seems like more of unity issue
> 
> (this was a Unreal Engine 4 problem, e.g. `It is a script that adds html 5 packaging to unreal engine` and `UE4 Source/Engine/Platforms/HTML5/Build/PatchFiles/4.27.2.engine.patch`. Unreal is a competitor to Unity)

Oops, sorry @juj.. of course I know that.. my bad.

**Comment by Deadpeel** [comment]
Hey, for me it worked to navigate to './Build/emsdk/emsdk-3.1.53'  and there run the commands './emsdk install 3.1.53' then './emsdk activate 3.1.53' then also  './emsdk install mingw-7.1.0-64bit' but you might not need this last one.
After these are installed go back to 'Engine/Platforms/HTML5' and run HTML5Setup.

**Comment by HustLion** [comment]
> Hey, for me it worked to navigate to './Build/emsdk/emsdk-3.1.53' and there run the commands './emsdk install 3.1.53' then './emsdk activate 3.1.53' then also './emsdk install mingw-7.1.0-64bit' but you might not need this last one. After these are installed go back to 'Engine/Platforms/HTML5' and run HTML5Setup.
> 
> This link also helped me a lot: [ufna/UE-HTML5#32](https://github.com/ufna/UE-HTML5/issues/32)

@Deadpeel  Thank you for the info!

As of 2024.4.11,  the script uses 3.1.56.

I did these steps and now the cmake process is running.

```bash
# in the Engine/Platforms/HTML5 directory
cd ./Build/emsdk/emsdk-3.1.56
./emsdk install 3.1.56
./emsdk activate 3.1.56
./emsdk install mingw-7.1.0-64bit
./emsdk activate mingw-7.1.0-64bit

# made sure all above has no errors and go back to Engine/Platforms/HTML5
./HTML5Setup.sh
```
