### ISSUE TITLE
Encounter 404 Error when Installing Emscripten SDK Version 1.38.45

### ISSUE THREAD

**Issue by 4-1-1** [emscripten-core/emsdk#1352]
I encountered a 404 error when trying to install Emscripten SDK version 1.38.45 using emsdk. I have attempted multiple times, but have been unable to download this version of the SDK. I have confirmed the version number is correct and have tried waiting for some time before attempting again, but the problem persists.

Steps to Reproduce:

Use the emsdk install command to install Emscripten SDK version 1.38.45.
Observe the 404 error during the download process.
Expected Behavior:
Expected to successfully download and install the specified version of the SDK.

Actual Behavior:
Download fails with a 404 error.

Environment:

Operating System: [ubuntu 20]
emsdk Version: [latest]

```shell
./emsdk install 1.38.45
Resolving SDK version '1.38.45' to 'sdk-releases-f3030d9fffcc9e1287cb6b8e72982e94ece31d71-64bit'
WARNING: arm64-linux binaries are not available for all releases.
See https://github.com/emscripten-core/emsdk/issues/547
Installing SDK 'sdk-releases-f3030d9fffcc9e1287cb6b8e72982e94ece31d71-64bit'..
Skipped installing node-16.20.0-64bit, already installed.
Installing tool 'releases-f3030d9fffcc9e1287cb6b8e72982e94ece31d71-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/f3030d9fffcc9e1287cb6b8e72982e94ece31d71/wasm-binaries-arm64.tar.xz': HTTP Error 404: Not Found
error: installation failed!

```

**Comment by sbc100** [comment]
The problem is that you are trying to install the linux arm64 version of the SDK. 

We don't have binaries available for very version for linux arm64.    Yo u can use `emsdk install latest-arm64-linux` to get the latest possible version for linux arm64.   Currently it looks like that is 3.1.47.

**Comment by sbc100** [comment]
Can I ask what linux arm64 machine are you have that you want to install emsdk on?

**Comment by 4-1-1** [comment]
ok, thanks.
