### ISSUE TITLE
Emscripten installation fails with Python 3 on macOS

### ISSUE THREAD

**Issue by immakermatty** [emscripten-core/emsdk#1356]
I encountered an issue while trying to install Emscripten using the `./emsdk install latest` command. The installation failed with the following error message:

Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-14.18.2-64bit.tar.xz'..

I tried running the command again, but the issue persisted. I then tried installing an older version of Emscripten using the `./emsdk install <version>` command, but I encountered the same issue.

I was able to resolve the issue by installing Python 2 and running the `./emsdk install latest` command using Python 2.

I'm using macOS version 13.0.1 (22A400), and I have the latest version of Python 3.11.1 installed.

**Comment by sbc100** [comment]
Fixed in #1355
