### ISSUE TITLE
emscripten installation failure

### ISSUE THREAD

**Issue by wetbadger** [emscripten-core/emsdk#1358]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Command 'emcc' not found, but can be installed with:
sudo apt install emscripten

(Problem with installation)

**Failing command line in full:**

Trying to install from git-clone:

./emsdk install latest -v
Resolving SDK alias 'latest' to '3.1.32'
Resolving SDK version '3.1.32' to 'sdk-releases-29ad1037cd6b99e5d8a1bd75bc188c1e9a6fda8d-64bit'
Installing SDK 'sdk-releases-29ad1037cd6b99e5d8a1bd75bc188c1e9a6fda8d-64bit'..
Installing tool 'node-14.18.2-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-x64.tar.xz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
error: installation failed!

Trying to install from apt:

sudo apt install node-acorn
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 node-acorn : Depends: nodejs:any or
                       nodejs (< 12.22.5~dfsg-4~) but 18.14.2-deb-1nodesource1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by sbc100** [comment]
Fixed in #1355
