### ISSUE TITLE
3.1.61 Docker image not published

### ISSUE THREAD

**Issue by jeswr** [emscripten-core/emsdk#1395]
It looks like the CI for the docker release of 3.1.61 has failed (https://github.com/emscripten-core/emsdk/runs/25678246996).

I discovered this [in my CI downstream](https://github.com/SWI-Prolog/npm-swipl-wasm/pull/628) which opens up a PR when a new emsdk version is released, but then failed to build because the docker image for 3.1.61 was not available.

**Comment by sbc100** [comment]
Fixed by updating circleci credentials.
