### ISSUE TITLE
The compilation speed is too slow. 

### ISSUE THREAD

**Issue by sxstd001** [emscripten-core/emsdk#1396]
The compilation speed is too slow. 
Developing a game client, the compilation speed is a nightmare. This is extremely important!!!

**Comment by sbc100** [comment]
Are you referring to compilation time of link time?

For compilation time we should be almost identical to bare clang, so I would hope that we would only really differ in link time.  Is that your experience, or are you seeing the compilation time being slow too?   If so how is your experience of using clang on other platforms?
