### ISSUE TITLE
[bazel] Example to Bind Packages with Non-Standard Libraries

### ISSUE THREAD

**Issue by wrangelvid** [emscripten-core/emsdk#1431]
I have been really enjoying working with embind and Bazel so far and am curious about linking external [libraries](https://emscripten.org/docs/compiling/Building-Projects.html#using-libraries) with the Emscripten toolchain.
According to the standard Emscripten documentation, the typical approach involves building the libraries to object files or archives and then linking them with the main program to emit JavaScript and WebAssembly.

Are there existing best practices or examples out there on how to include dependencies automatically with the Emscripten toolchain and Bazel? If not, could we expand the examples to include this scenario?

**Comment by sbc100** [comment]
I imagine the answer is exactly the same as using external libraries with bazel in general.  I don't think emscripten is differs from other bazel toolchains in how to do this.  @walkingeyerobot might know more.

**Comment by wrangelvid** [comment]
Thank you @sbc100 for the quick response! Turns out it was a red herring. I was using a third party library with a rule to include additional dependencies which did not play well with bazelmods. My cc_tests were passing while linking it to wasm didn't find the dependency, which I ended up fixing.
