### ISSUE TITLE
simple demo does not work on android chrome

### ISSUE THREAD

**Issue by xianjimli** [emscripten-core/emsdk#1495]
* write a simple hello.c

```c
#include <stdio.h>

int main() {
    printf("Hello, WebAssembly!\n");
    return 0;
}
```

* build it

```
emcc hello.c -o hello.html
```

it generates the following files

```
-rw-r--r--  1 jim  staff     87 11 30 07:13 hello.c
-rw-r--r--  1 jim  staff  22038 11 30 07:14 hello.html
-rw-r--r--  1 jim  staff  54974 11 30 07:14 hello.js
-rwxr-xr-x  1 jim  staff  14453 11 30 07:14 hello.wasm
```

start a web server and visit hello.html with an android chrome, there are some errors:

<img width="1920" alt="android_chrome" src="https://github.com/user-attachments/assets/06b2889c-da73-47ff-a2a8-68fa19248641">

**Comment by sbc100** [comment]
Can you share what is on those lines that contain the errors?

I imagine it is nullish coalescing?   In which case perhaps you are running on an old browser that doesn't support those that JS feature?  See  https://caniuse.com/mdn-javascript_operators_nullish_coalescing.  What browser version are you running on?

**Comment by xianjimli** [comment]
[demo.zip](https://github.com/user-attachments/files/17987137/demo.zip)

Thank you for your reply. The attachment are the demo files.

**Comment by sbc100** [comment]
Yup it looks like the `??=` is not supported by your browser.  What browser version are you using?   You can use the `-sMIN_CHROME_VERSION=xxx` setting if necessary to remove those modern ES6 features.

**Comment by xianjimli** [comment]
-sMIN_CHROME_VERSION=78 works well. thank you very much.

**Comment by sbc100** [comment]
Can I ask how/why you are targettting such an old chrome version?

**Comment by xianjimli** [comment]
An [AWTK](https://github.com/zlgopen/awtk/) user told me that [AWTK-Web](https://github.com/zlgopen/awtk-web) is not working on Android browser. I tested it on an Android phone and found that it also doesn’t work. Many older Android phones are still in use, the compatibility is crucial.

Thank you for your help.

**Comment by sbc100** [comment]
> Many older Android phones are still in use, the compatibility is crucial.

My understanding is that android phones automatically update the version of chrome they ship so the vast majority of android devices should have a modern version of chrome.    Do you know any particular makes or models of phones that you know of that run chrome 78 still?   That would be pretty dangerous I would imagine.

**Comment by xianjimli** [comment]
> android phones automatically update the version of chrome
No, android users can not visit google play from China mainland，they can not upgrade brower to latest version.

**Comment by xianjimli** [comment]
My android phone is Nokia G50. I just use it to do some test work.
