### ISSUE TITLE
Installation halts at 99.97% 

### ISSUE THREAD

**Issue by KarimWalidFawzy** [emscripten-core/emsdk#1507]

**Comment by sbc100** [comment]
Can you share the full command you typed along with the full output?   Does it happen consistently?

**Comment by sbc100** [comment]
Interesting.   I don't think we have ever seen that before. 
 If you copy that last URL are you able to fetch it using curl or wget?   Are you able to download it in a browser?

**Comment by KarimWalidFawzy** [comment]
Yes but if I try installing it independently using google chrome and placing the file in the downloads folder, the cmd would register the file as uninstalled and therefore if i try to activate it, the cmd would tell me that i need to install the software first

**Comment by sbc100** [comment]
So that means it's not a network issue I guess.  In that case I have no idea what could cause this!
