### ISSUE TITLE
Please transfer the repo to emscripten-core

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emsdk#208]
We've transferred the emscripten, fastcomp, and clang repos so far, and things look good:

https://github.com/emscripten-core/

@juj I think only you can transfer this one. Please do it whenever you can. After that there will be some doc changes we need to do, but github redirects will keep things working in the meantime, so should be nothing to worry about.

**Comment by juj** [comment]
Sounds good. According to https://help.github.com/articles/transferring-a-repository/ seems really easy - I was about to click on that, but let me confirm before I do that if that's the right path? Will clicking in Danger Zone -> Transfer Ownership retain the link redirects, and that is what I should do?

**Comment by kripken** [comment]
Yes, it's in the "danger zone" area. And yes, it will keep links working (issues, wiki, the git repo itself even).

**Comment by juj** [comment]
Alrighto, now we're rocking.

**Comment by kripken** [comment]
Great, thanks! I'll write up PRs to update the doc locations (but it should work in the meanwhile too, github redirects everything).
