### ISSUE TITLE
global name 'win32api' is not defined. module imported in one function, used in another

### ISSUE THREAD

**Issue by elHamil** [emscripten-core/emsdk#210]
I'm trying a very recent version of emsdk, I'm on commit [ea5d631](https://github.com/emscripten-core/emsdk/commit/ea5d631a5446632e195765d89a53ead71cd6de45)
I'm on Windows and using the bundled Python version, `/emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe`

When I run the command `emsdk activate --global sdk-incoming-64bit`, I get a bunch of normal output, and then an exception that says `global name 'win32api' is not defined`

It's coming from the function `win_set_environment_variable_direct` in the file `emsdk`. To be precise, the line that starts with `folder = win32api.RegOpenKeyEx` throws the exception.

I see that this code was changed in commit [7a0e274](https://github.com/emscripten-core/emsdk/commit/7a0e27441eda6cb0e3f1210e6837cae4b080ab4c) on Oct 23, 2018 to fix issue #177 

I see that the `win32api` module is imported in the other function `import_pywin32()`. I'm not a Python expert, but isn't it wrong to `import win32api` in one function and try to use it in another function? I thought imports were scoped in Python? See for example https://docs.python.org/2.7/reference/simple_stmts.html#the-import-statement which says
"define a name or names in the local namespace (of the scope where the import statement occurs)."

If I simply inline the call to `import_pywin32()`, the error goes away.

(Side note: To see the real exception, I had to change the line
```
if e[0] == 5 or e[2] == 'Access is denied.':
```
to
```
if len(e.args) >= 3 and (e[0] == 5 or e[2] == 'Access is denied.'):
```
to avoid the error `tuple index out of range`)

**Comment by ldm0** [comment]
Pretty useful!
After inlining the call to import `pywin32`, though error still pops out(Failed to read env...), the environment variables are set properly.

**Comment by elHamil** [comment]
Why I made an issue and not a pull request? Well, because I'm not 100% sure that it's correct to simply inline the function. Maybe @juj had a good reason for it, which I don't understand with my limited Python & emsdk experience?
