### ISSUE TITLE
Is there a way to build with emscripten inside web browser?

### ISSUE THREAD

**Issue by kornerr** [emscripten-core/emsdk#229]
Hi.

My goal is to build my software for web with emscripten inside a web browser.

I've seen JSLinux ( https://bellard.org/jslinux/ ) solution and contacted its author. However, the author couldn't provide me with any specifics.

Does anyone here know how to build with emscripten inside a web browser?

Thanks.

**Comment by kripken** [comment]
Most of emscripten's pieces have web ports, e.g. clang in clang-in-browser: https://tbfleming.github.io/cib/

Emscripten depends on python and node.js though, and code run in those (as well as optionally on closure compiler which requires java). Porting those as a whole would take more work, and no one has done it yet to my knowledge.

Running in jslinux or such might be an option, without porting, but as a CPU emulator it would not be as fast.
