### ISSUE TITLE
Using own Node, Java and Python with EMSDK?

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emsdk#236]
I read that issue where a user said he wanted to use his own newer version of Node and Juj said to delete the .emscripten configuration file and try again.  As a related question, I want to ask if it's possible to use my own Node, Java and Python with the EMSDK without specifying the respective paths to them in the configuration file.  

If not, then I want to ask how I can get EMSDK to use the Node, Python and Java I already have.  I installed the latest upstream SDK on my WSL (I have Bionic Beaver installed on it) by running the `emsdk install latest-upstream` and it installed Node, Java and Python as well.  But I don't want to use the ones that came with the SDK.  

Note: I'm going to be using the WSL for now because I want to use the Wasm Backend which currently seems to only work on Linux distributions and seems to be broken on Windows.  I hope it gets fixed soon.  

There's a problem with the gen_struct_info.py stuff and Node's output being empty with a non-zero result value when I try to use the Wasm Backend with Emscripten.  I've already mentioned this in the Emscripten GitHub as well.

**Comment by kripken** [comment]
> I want to ask if it's possible to use my own Node, Java and Python with the EMSDK without specifying the respective paths to them in the configuration file.

No - that is the purpose of the configuration file. You can specify paths to your own versions of those tools there.
