### ISSUE TITLE
dict_values' object does not support indexing

### ISSUE THREAD

**Issue by ajit3259** [emscripten-core/emsdk#240]
./emsdk install latest
Traceback (most recent call last):
File "./emsdk", line 2605, in 
sys.exit(main())
File "./emsdk", line 2369, in main
load_sdk_manifest()
File "./emsdk", line 1977, in load_sdk_manifest
elif '%releases-tag%' in t.version: expand_category_param('%releases-tag%', releases_tags, t, is_sdk=False)
File "./emsdk", line 1933, in expand_category_param
ver = category_list[i]
TypeError: 'dict_values' object does not support indexing

**Comment by kripken** [comment]
Thanks @ajit3259! Looks like I broke this, that last PR works in python2 but in 3 `dict.values()` behaves differently. Fixed in https://github.com/emscripten-core/emsdk/pull/241 (as a workaround you can use `python2 emsdk` for now)
