### ISSUE TITLE
`emsdk activate --global` fails with Python 3 on Windows due to different KeyError behaviour

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emsdk#298]
Steps to reproduce:

1. Install Python 3 and add it to PATH:
```
> python --version
Python 3.7.3
```
2. Start as a usual user (not Administrator) at `C:\`
3. `git clone https://github.com/emscripten-core/emsdk.git` (HEAD is at 49652605051d9faca2dcb781918a028bdfbc2703 at the moment)
4. `cd emsdk`
5. `emsdk install latest-upstream`
6. Open an Administrator terminal
7. `cd C:\emsdk`
8. `emsdk activate --global latest-upstream`

Expected: successful activation.

Got:
```
Microsoft Windows [Version 10.0.18362.175]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd c:\emsdk

c:\emsdk>emsdk activate --global latest-upstream
Registering active Emscripten environment globally for all users.

Writing .emscripten configuration file to user home directory C:\Users\esuvorov/
Backing up old Emscripten configuration file in C:\Users\esuvorov\.emscripten.old
The Emscripten configuration file C:\Users\esuvorov\.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT = 'c:/emsdk/upstream/bin'
BINARYEN_ROOT = 'c:/emsdk/upstream'
NODE_JS = 'c:/emsdk/node/8.9.1_64bit/bin/node.exe'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'C:/Users/esuvorov/AppData/Local/Temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += c:\emsdk
PATH += c:\emsdk\upstream\emscripten
PATH += c:\emsdk\node\8.9.1_64bit\bin

Setting environment variables:
EMSDK = c:/emsdk
EM_CONFIG = C:\Users\esuvorov\.emscripten
EMSDK_NODE = c:\emsdk\node\8.9.1_64bit\bin\node.exe

Traceback (most recent call last):
  File "c:\emsdk\\emsdk", line 286, in win_get_environment_variable
    return os.environ[key]
  File "C:\Users\esuvorov\AppData\Local\Programs\Python\Python37-32\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'EMSDK_NODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\emsdk\\emsdk", line 2697, in <module>
    sys.exit(main())
  File "c:\emsdk\\emsdk", line 2636, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate=arg_global)
  File "c:\emsdk\\emsdk", line 2129, in set_active_tools
    tool.win_activate_env_vars(permanently_activate=True)
  File "c:\emsdk\\emsdk", line 1495, in win_activate_env_vars
    win_delete_environment_variable(key, False) # If there is an env var for the LOCAL USER with same name, it will hide the system var, so must remove that first.
  File "c:\emsdk\\emsdk", line 354, in win_delete_environment_variable
    win_set_environment_variable(key, None, system)
  File "c:\emsdk\\emsdk", line 316, in win_set_environment_variable
    previous_value = win_get_environment_variable(key, system)
  File "c:\emsdk\\emsdk", line 288, in win_get_environment_variable
    if e[0] != 2: # 'The system cannot find the file specified.'
TypeError: 'KeyError' object is not subscriptable

c:\emsdk>
```

Looks like the problem is in [`win_get_environment_variable`](https://github.com/emscripten-core/emsdk/blob/49652605051d9faca2dcb781918a028bdfbc2703/emsdk#L283-L288) at the very least. Python 3 does not have `pywin32` by default, so the first `try` fails, then `os.environ[key]` throws `KeyError` for non-existent variable, it is caught by the second `except` and everything fails when the code tries to access `[0]` of `KeyError`. It's ok for some reason in Python 2 (`[0]` simply returns the key of `KeyError`), but fails in Python 3, hence the error above.

**Comment by yeputons** [comment]
Extra info: that's a somewhat known incompatibility between Python 2 and Python 3, see [here](https://bugs.python.org/issue30238).

Workarounds:
1. Install `latest` first, which will install supported version of Python to `c:\emsdk\python` and then `emsdk.bat` will pick it up.
2. Use Python 2
3. Explicitly specify that Python 3 is unsupported.

Quick fix: replace `e[0]` with `e.args[0]` (similarly in `win_set_environment_variable_direct`).

Full fix: rewrite the logic so it does not rely on `KeyError` and `win32api.error` having `[0]`.

**Comment by kripken** [comment]
Thanks @yeputons! Please take a look at #300 which I opened now, does that fix the problem for you?

(I'm still not totally happy with the error handling there, but at least it should work in all python versions with that...)
