### ISSUE TITLE
Non-wasm intrinsics headers are installed with upstream

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emsdk#309]
These are coming in with the installation of clang, for example `emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h`. These should not be installed because they lead to user confusion about what kind of SIMD intrinsics emscripten supports: https://groups.google.com/d/msg/emscripten-discuss/bp_iubXU3BE/vI4opCduCQAJ

**Comment by kripken** [comment]
@sbc100 do you know how those work? I'm not sure where they come from.

**Comment by sbc100** [comment]
I believe this header tree is shared between all targets, they are llvm core headers.  

Similar errors will occur if one tries to include this header on arm for example.  

On my desktop I get:

```clang --target=arm  test.c
test.c:2:4: error: use of unknown builtin '__builtin_ia32_emms' [-Wimplicit-function-declaration]
   __builtin_ia32_emms();
   ^
1 error generated.
```

**Comment by sbc100** [comment]
I think this is a wontfix.  Please reopen if you disagree
