### ISSUE TITLE
NO_DYNAMIC_EXECUTION disallows embind

### ISSUE THREAD

**Issue by allrightzhu** [emscripten-core/emsdk#313]
when I used the setting NO_DYNAMIC_EXECUTION = 1,there was an AssertionError: NO_DYNAMIC_EXECUTION disallows embind

**Comment by kripken** [comment]
I think this was fixed - what version is that on?

**Comment by allrightzhu** [comment]
> I think this was fixed - what version is that on?

I installed emsdk-1.35.0-full-64bit.exe, so the latest version is ok?

**Comment by kripken** [comment]
Yes, it looks like it's fixed on the latest version (your 1.35.0 is quite old, almost 4 years, so worth upgrading anyhow).

**Comment by allrightzhu** [comment]
> Yes, it looks like it's fixed on the latest version (your 1.35.0 is quite old, almost 4 years, so worth upgrading anyhow).

ok, thank you!
