### ISSUE TITLE
emsdk output module js not loading wasm in devtools source

### ISSUE THREAD

**Issue by awptimus** [emscripten-core/emsdk#318]
The module.js that is output by emsdk does not allow chrome devtools to load the wasm for debugging in the Source tab. If I were to take a wasm and manually load it via WebAssembly, devtools loads it in the Source tab
![Untitled](https://user-images.githubusercontent.com/12189126/62840593-0309b080-bc6b-11e9-9bb7-a01015f4af06.png)

**Comment by kripken** [comment]
Is this with or without source maps? Do you have a full testcase showing the issue?

**Comment by awptimus** [comment]
Easiest way to duplicate.

**create a simple helloworld.c**
`#include <stdio.h>

int main(){
    printf("%s","Hello World!\n");
}`

**build**

emcc -v -g4 -Os \
-s "EXPORTED_FUNCTIONS=['_main']" \
-s ERROR_ON_UNDEFINED_SYMBOLS=0 \
-o helloworld.html HelloWorld.c

**run in chrome or chromium**

emrun helloworld.html

![image](https://user-images.githubusercontent.com/12189126/62904014-ad98d680-bd32-11e9-9835-be7d5a19b533.png)

a similar wasm can be loaded "manually" with no trouble
![image](https://user-images.githubusercontent.com/12189126/62904200-5e9f7100-bd33-11e9-9fd6-f1bc9db14d7b.png)
![image](https://user-images.githubusercontent.com/12189126/62904231-770f8b80-bd33-11e9-80a2-ade3af4c0ee0.png)

**Comment by kripken** [comment]
That could be a devtools bug, I'm not sure... in general I think when a source map is present it will show the original source, `HelloWorld.c` here, which it does properly. That may intentionally replace the wasm. It's best to open a bug on the chromium devtools to find out.

**Comment by awptimus** [comment]
I fried a few things.

Compiled with the options above, emcc outputs a .wast and .map file (obviously). If I delete the wast (which I don't believe is used by chrome/chromium in any way) and the .map file, chromium still has the message "source map detected" as above. Which makes sense since g4 adds references for the map file to use. But with the map file missing, obviously I don't have my .c references.

However, if I compile with g4 and then recompile without it, keeping the .map file on disk, it _does_ load the wasm correctly in devtools.

And I can manually add the .map file through the devtools gui to load the .c file.

However, obviously, I don't have a full map from the .c to the .wasm because this time it was compiled without g4.

I can't imagine this is intended. But whatever I'll take that up with the chromium guys.
