### ISSUE TITLE
Running emsdk no longer works for both powershell and bash

### ISSUE THREAD

**Issue by Morilli** [emscripten-core/emsdk#336]
On powershell, I get this:
![image](https://user-images.githubusercontent.com/35152647/63820879-3e82cb00-c94b-11e9-906a-52f20d7a2e7a.png)

On bash, I get this:
![image](https://user-images.githubusercontent.com/35152647/63820892-493d6000-c94b-11e9-9b2e-a6901ba2fe99.png)

It works fine on cmd though.

Very likely caused by a562ff7bda8a6517c86b858207551039b06889c1.

**Comment by kripken** [comment]
cc @sbc100 who wrote that commit

**Comment by sbc100** [comment]
Hmm.. that its strange both the old and the new versions of "emsdk" start with "#!/bin/sh"... do you know what powershell is trying to run it under?  I looks like of like python.. why would PowerShell try to use python to run "./emsdk"?

Regarding bash, again its hard for me to tell what its trying to run emsdk under.   I will see if I can repro.

**Comment by Morilli** [comment]
Hm, I found the issue regarding running under bash. The file has windows line endings for me, which bash doesn't like. Converting the file to linux line endings makes it work. Not yet sure whether this is a local issue or git-related.

**Comment by sbc100** [comment]
Presumably the default on windows is to check things out with windows line endings?  I assume thats what we do and what we continue to do. 

Also, emsdk would have had the same line endings before and after a562ff7 so it seems unlikely that would be the problem. 

I'm curious can you try without the line endings fix but with my .ps1 fix?  Does that also fix the problem?

Did my change the .ps1 file also fix the problem?

**Comment by Morilli** [comment]
Powershell uses the .ps1 only, and that works. Bash on the other hand uses the ``emsdk`` file, which in fact has also never worked for me in the past.

**Comment by sbc100** [comment]
OK, that at least solves the mystery.  Unless its big problem that bash on windows doesn't work with windows git checkout I suggest we leave this closed.

Presumably if you ran linux git from WSL then it would have the correct line endings?

**Comment by Morilli** [comment]
running ``git`` from wsl does work, yes. The main issue is gonna be the automatic conversion done by git, which probably sadly can't be resolved properly.

**Comment by Morilli** [comment]
Actually I think there is a solution for this issue that is git-independant. See https://git-scm.com/docs/gitattributes#_end_of_line_conversion for more information.
Basically, I believe a ``.gitattributes`` files with the following contents should be enough:

```
*.sh text eol=lf
```
