### ISSUE TITLE
WASM Backend on Windows - is it working yet?

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emsdk#350]
I have the WASM Backend working on WSL on Windows, but I wanted to know if it's working on Windows itself yet.  I don't have on Windows itself anymore and I wanted to make sure of this before getting it again.  

Which tools does the command `emsdk install latest-upstream` give you?  I want to try getting them manually.  And what's the compiler that Java is required for?  I'm asking these two things because I forgot since it's been a while.  Thanks in advance.

**Comment by kripken** [comment]
Yes, it should all work on windows. The emsdk repo has [CI for windows](https://circleci.com/gh/emscripten-core/emsdk/246?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) now, and so does our [chromium CI](https://ci.chromium.org/p/emscripten-releases/builders/ci/win) that creates releases. Both of those are green.

**Comment by DragonOsman** [comment]
Thanks.  I'll try it out.

**Comment by DragonOsman** [comment]
How's the support for Python 3 now?  Last I heard, it was being worked on but Python 2 was still better to use with Emscripten.

**Comment by kripken** [comment]
We probably use more python3 than 2 at this point.

**Comment by DragonOsman** [comment]
So is it okay for me to put the path to Python3 in the configuration file for Emscripten, then?

**Comment by DragonOsman** [comment]
I still don't have an answer on another question I asked in the OP: what tools does the command `emsdk install latest-upstream` give you?  I want to know so I can install everything except Python and Node manually through emsdk and just use the Python and Node I already have.  And I'd like a reminder on the name for the compiler Emscripten uses that requires Java.  Thanks.
