### ISSUE TITLE
Debugging WebAssembly - Can't see source map in Edge or Chrome

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emsdk#355]
I wrote some quick small practice C++ code and compiled it to WebAssemby with the command 
```
em++ -std=c++17 -Wall -pedantic -g main.cpp fib.cpp -s WASM=1 -o main.js
```
(I did add the additional flag right after `-g` that it asked for when I tried to do this; I just don't remember what it is exactly).  But after doing so, I couldn't see the program's output in the browser's console anymore and I also can't see the source map even mentioned anywhere in Edge or Chrome.  

This was in [here](https://medium.com/@tdeniffel/pragmatic-compiling-from-c-to-webassembly-a-guide-a496cc5954b8); the same site also talks about running the command `wasm-dis` to disassemble WebAssembly, but trying that gives me an error that pretty much means "command not found" on the Command Prompt.  In VS Code I can see the WebAssembly text format just fine by right clicking on a .wasm file and choosing "View WebAssembly" from the context menu, but knowing how to do this might also be helpful.

**Comment by kripken** [comment]
For source maps you need `-g4`, see https://emscripten.org/docs/tools_reference/emcc.html#emcc-g4 or https://emscripten.org/docs/porting/Debugging.html#debug-information

**Comment by DragonOsman** [comment]
I want to know how best to manually load a Wasm module in JavaScript and call functions from it.  The stuff I've seen seems outdated.  I tried to do as it shows on that site I linked above:
```html
<html>
<body>
<script>
function loadWasm(fileName) { 
  return fetch(fileName)
    .then(response => response.arrayBuffer())
    .then(bits => WebAssembly.compile(bits))
    .then(module => { return new WebAssembly.Instance(module) });
};
  
loadWasm('gen/hello.wasm')
  .then(instance => {
    let fib = instance.exports.__Z3fibi;
    console.log(fib(1));
    console.log(fib(20));
  });
  
</script>
</body>
</html>
```
But with a different Wasm file name because I'm using code that was already named differently from before.  My code:
```html
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello from WebAssembly</title>
</head>
<body>
    <script>
        function loadWasm(fileName) {
            return fetch(fileName)
                .then(response => response.arrayBuffer())
                .then(bits => WebAssembly.compile(bits))
                .then(module => { return new WebAssembly.Instance(module) });
        };

        loadWasm('main.wasm')
            .then(instance => {
                let fib = instance.exports._Z3fibi;
                console.log(fib(1));
                console.log(fib(20));
            });
    </script>
</body>
</html>
```
When I try to run it using emrun, I got this error:
```
0: Import is invalid
```
on line 14 which is this:
```html
.then(bits => WebAssembly.compile(bits))
```
On Chrome it says:
```
Uncaught (in promise) TypeError: WebAssembly.Instance(): Imports argument must be present and must be an object
    at main.html:15
```
Line 15 is this one:
```html
.then(module => { return new WebAssembly.Instance(module) });
```
What do I do to fix this?  Do I have to do `Instance.imports` or something like that?

**Comment by DragonOsman** [comment]
Okay, I'll open a new issue for those things and try to keep in mind what you said about `-g4` for source maps.  And I'll close this issue.  Thanks for the help.
