### ISSUE TITLE
"EAGAIN":11(in 1.38.42-fastcomp) "EAGAIN":6(in 1.38.47-fastcomp)

### ISSUE THREAD

**Issue by yjkhtddx** [emscripten-core/emsdk#374]
The value of "EAGAIN" is different in different versions of fastcomp.

./fastcomp/lib/wasm-obj/generated_struct_info.json
"EAGAIN":11 (in 1.38.42-fastcomp) 
"EAGAIN":6 (in 1.38.47-fastcomp)

The program compiled by the new version of fastcomp runs abnormally.

Temporarily use 1.38.42-fastcomp.

How to compile with the new version?

**Comment by kripken** [comment]
That's correct, we changed the numeric values of those constants, as an ABI change. Perhaps you have some object files or libraries built with the old version, being linked and compiled with the new one? (If so, rebuilding them all from source should fix it.)

**Comment by yjkhtddx** [comment]
Thank you. I agree with you. I will try to solve it.

**Comment by yjkhtddx** [comment]
Thank you. The problem has been solved through your help.
