### ISSUE TITLE
Upstream builds don't work on MacOS El Capitan

### ISSUE THREAD

**Issue by zstauber** [emscripten-core/emsdk#379]
I reinstalled emsdk and it didn't work.  Meaning, running "emcc" or "clang" gives me errors about dyld because it says the dylibs were compiled with MacOS X 12.  Well, that's a personal problem.  I have an older  mid-2009 MacBook Pro that Apple won't let move past MacOS X 11.6.

Does anyone know what is the latest version that was compiled against MacOS X 11.6?

**Comment by zstauber** [comment]
Nevermind, there's a workaround:
```
./emsdk install latest-fastcomp
./emsdk activate latest-fastcomp
```

**Comment by kripken** [comment]
I'm surprised this works, as we build fastcomp and upstream on the same systems, and in the same way, don't we? (not sure about the mac details) cc @dschuff @sbc100

**Comment by sbc100** [comment]
There was probably some upstream fix to avoid/fix the dependency?  Maybe CMAKE_OSX_DEPLOYMENT_TARGET doesn't work correctly with fastcomp?

**Comment by dschuff** [comment]
Except this is the other way around; fastcomp works but upstream doesn't? I'm surprised too, we do build them the same way AFAIK

**Comment by zstauber** [comment]
The book I'm going through, Learn WebAssembly by Packt, has an updated version, and in the new one it says to install **./emsdk install sdk-1.38.15-64bit** instead of **latest**.  So that works on both Windows 10 and MacOS X 11.6, and I can do that.  Eventually I'll be done with the book and want to use the latest, and then I just can't use MacOS X on an older machine, but for now at least I can get through the tutorials.

**Comment by zstauber** [comment]
I suppose this issue can be closed, since it was about which version works with El Capitan, and **sdk-1.38.15-64bit** is the answer, but I'd be OK if y'all want to keep it open as a placeholder for the fastcomp issue, since it should not be working with El Capitan if regular 1.39.0 does not.

**Comment by sbc100** [comment]
I don't think asking people to install an old SDK is the right answer.  We need to have support in latest for any version of OS X that still has significant users.

**Comment by sbc100** [comment]
Taking a closer look, it seems like we pass `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.12` when we do the builds which means our min version is 10.12.   El Capitan is 10.11 (https://en.wikipedia.org/wiki/MacOS).  So this is working as indented, we don't support macOS versions that old.

I'm not sure what you mean by referring to 11.6?

**Comment by zstauber** [comment]
Sorry, what I meant was 10.11.6.
