### ISSUE TITLE
How do I build upstream build from source?

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emsdk#384]
When trying to install sdk-incoming-64bit, it seems to build fastcomp instead of upstream. I'd like to build my own version of the upstream compiler (preferably from a given SHA revision of LLVM repository...). How do I do that?

**Comment by kripken** [comment]
Docs are here: https://emscripten.org/docs/building_from_source/index.html#building-llvm

**Comment by zeux** [comment]
Fantastic, thanks! This is easier than I thought :)
