### ISSUE TITLE
MSYS2: Exception: Duplicate sdk sdk-incoming-32bit! 

### ISSUE THREAD

**Issue by MayaPosch** [emscripten-core/emsdk#385]
Trying to run the emsdk script on current MSYS2 (Windows 7 x64) with Python 3.7.4:

```
$ ./emsdk install latest
Traceback (most recent call last):
  File "./emsdk.py", line 2991, in <module>
    sys.exit(main())
  File "./emsdk.py", line 2680, in main
    load_sdk_manifest()
  File "./emsdk.py", line 2230, in load_sdk_manifest
    add_sdk(sdk)
  File "./emsdk.py", line 1843, in add_sdk
    raise Exception('Duplicate sdk ' + str(sdk) + '! Existing:\n{' + ', '.join("%s: %s" % item for item in vars(find_sdk(str(sdk))).items()) + '}, New:\n{' + ', '.join("%s: %s" % item for item in vars(sdk).items()) + '}')
Exception: Duplicate sdk sdk-incoming-32bit! Existing:
{version: incoming, bitness: 32, uses: ['clang-incoming-32bit', 'node-12.9.1-32bit', 'python-2.7.13.1-32bit', 'java-8.152-32bit', 'emscripten-incoming-32bit', 'binaryen-master-32bit'], os: win, id: sdk, name: sdk-incoming-32bit, is_old: False, is_sdk: True}, New:
{version: incoming, bitness: 32, uses: ['clang-incoming-32bit', 'node-12.9.1-32bit', 'emscripten-incoming-32bit', 'binaryen-master-32bit'], os: linux, id: sdk, name: sdk-incoming-32bit, is_old: False, is_sdk: True}
```

Managed to install the SDK by commenting out the 'find_sdk()' check in the emsdk.py script (lines 1,842 & 1,843) and manually copying the contents of the binaries ZIP to the 'upstream' directory when the script died again while activating, as it couldn't handle UNIX style paths on Windows, apparently, and errored out during copying the unzipped files.

**Comment by TimMensch** [comment]
Same error here, but with 64 bits:

```
Traceback (most recent call last):
  File "./emsdk.py", line 3147, in <module>
    sys.exit(main())
  File "./emsdk.py", line 2847, in main
    load_sdk_manifest()
  File "./emsdk.py", line 2411, in load_sdk_manifest
    add_sdk(sdk)
  File "./emsdk.py", line 2024, in add_sdk
    raise Exception('Duplicate sdk ' + str(sdk) + '! Existing:\n{' + ', '.join("%s: %s" % item for item in vars(find_sdk(str(sdk))).items()) + '}, New:\n{' + ', '.join("%s: %s" % item for item in vars(sdk).items()) + '}')
Exception: Duplicate sdk sdk-upstream-master-64bit! Existing:
{is_sdk: True, id: sdk, os: win, version: upstream-master, is_old: False, name: sdk-upstream-master-64bit, uses: ['llvm-git-master-64bit', 'node-12.9.1-64bit', 'python-3.7.4-64bit', 'emscripten-master-64bit', 'binaryen-master-64bit'], bitness: 64}, New:
{is_sdk: True, id: sdk, os: linux, version: upstream-master, is_old: False, name: sdk-upstream-master-64bit, uses: ['llvm-git-master-64bit', 'node-12.9.1-64bit', 'emscripten-master-64bit', 'binaryen-master-64bit'], bitness: 64}
```

Also running from MSYS2. AND it also messes up the paths on the unzip, which I believe @MayaPosch also had to work around above.

**Comment by sbc100** [comment]
Perhaps MSYS2 is being detected as both windows and linux at the same time?   If you have time debugging would be much appreciated.   None of the core developers use MSYS and we have no testing for that environment (similarly WSL) so we really rely on the community for support here.

Perhaps we should make the clear in the docs somewhere? Or in a warning message?

Our of interest, in the environment you use which version of python is running?  Is it some MSYS version? or the normal windows python?

**Comment by TimMensch** [comment]
It certainly is adding both `linux` and `win` packages. It seems to be the `MSYS` `python` in my path. It does seem to work if I force 

It also works if you run from `cmd`, but ... I really never use `cmd`. Most developers I know prefer `MSYS`. It's the shell that comes with Git for Windows, for instance. Would really be nice to support `MSYS` since it's a very popular shell, especially among web developers.

Sorry that I don't have the time to put together a PR. As a short term patch maybe at least warn people that it needs `cmd` and Windows Python.

**Comment by BopItFreak** [comment]
Same issue here.

**Comment by francovp** [comment]
Any solution to this? I have the same problem :/

**Comment by sbc100** [comment]
We certainly have basic support for running the bash.exe that comes with git.. I believe we even run tests as part of our CI. 

Why to be clear, which version of python exactly is causes the failure?    Obviously we are not testing against the same version of python that you are.

**Comment by sbc100** [comment]
I sounds like this happens when you use the MSYS version of python... can you tell me how I would go about getting that installed?  It doesn't come with git for windows for example.

**Comment by francovp** [comment]
I installed Python using 
```
pacman -S python3
```

**Comment by gaekwad** [comment]
Any word on this? I recently upgraded from classic mingw to msys2 and the same thing is happening to me.  Somehow or other I had gotten it to work with the old mingw by making it think it was Windows (setting up the Windows environment within it was enough) but the same approach doesn't seem to work with msys2.  If I use the mingw32 that's part of msys2 and run emsdk_env.sh, I don't get the error above, but it doesn't set up the path correctly.
```
$ . emsdk_env.sh
Warning: MSYSTEM environment variable is present, and is set to "MINGW32". This shell has not been tested with emsdk and may not work.
Setting environment variables:
EMSDK = C:/emsdk
EM_CONFIG = C:/Users/user/.emscripten
```

**Comment by sbc100** [comment]
@gaekwad if your use case are you wanting the PATH to contain windows-style paths (`C:\emsdk`) or UNIX style paths (`/c/emsdk`)?

**Comment by sbc100** [comment]
What does `emsdk construct_env` output?   (This is what emsdk_env.sh uses internally but emsdk_env.sh set EMSDK_BASH which tells it you are using bash rather than windows shell).

**Comment by gaekwad** [comment]
Just as a side note, all of this is in mingw32 (which comes with msys2).  If I use actual msys2 I still get the original error in this bug.

I tried installing and activating the latest emsdk again and now the emsdk_env.sh script outputs what I would expect. However, even after running it, none of the things it says it's adding to my path are there.  `emsdk construct_env` has the same output

```
$ emsdk construct_env
Warning: MSYSTEM environment variable is present, and is set to "MINGW32". This shell has not been tested with emsdk and may not work.
Adding directories to PATH:
PATH += /c/emsdk
PATH += /c/emsdk/upstream/emscripten
PATH += /c/emsdk/node/12.18.1_64bit/bin
PATH += /c/emsdk/python/3.7.4-pywin32_64bit
PATH += /c/emsdk/java/8.152_64bit/bin

Setting environment variables:
EMSDK = C:/emsdk
EM_CONFIG = C:/emsdk/.emscripten
EM_CACHE = C:/emsdk/upstream/emscripten/cache
EMSDK_NODE = C:/emsdk/node/12.18.1_64bit/bin/node.exe
EMSDK_PYTHON = C:/emsdk/python/3.7.4-pywin32_64bit/python.exe
JAVA_HOME = C:/emsdk/java/8.152_64bit
export PATH="/c/emsdk:/c/emsdk/upstream/emscripten:/c/emsdk/node/12.18.1_64bit/bin:/c/emsdk/python/3.7.4-pywin32_64bit:/c/emsdk/java/8.152_64bit/bin:.:/c/msys/1.0/home/user/bin:/c/msys64/mingw32/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/msys64/usr/bin/site_perl:/c/msys64/usr/bin/vendor_perl:/c/msys64/usr/bin/core_perl:/c/msys/1.0/home/user/apache-ant-1.9.6/bin:/c/msys64/usr/i686-w64-mingw32/sys-root/mingw/bin:/c/msys64/mingw32/bin/";
export EMSDK="C:/emsdk";
export EM_CONFIG="C:/emsdk/.emscripten";
export EM_CACHE="C:/emsdk/upstream/emscripten/cache";
export EMSDK_NODE="C:/emsdk/node/12.18.1_64bit/bin/node.exe";
export EMSDK_PYTHON="C:/emsdk/python/3.7.4-pywin32_64bit/python.exe";
export JAVA_HOME="C:/emsdk/java/8.152_64bit";

$ echo $PATH
.:/c/msys/1.0/home/user/bin:/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/msys/1.0/home/user/apache-ant-1.9.6/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin
```

After adding it to my path manually, I'm able to get most of the way through my build, except that it's complaining about "_main" being undefined and I think that's because it's using SDL and I don't know how to pass it "-Dmain=SDL_main", but that's a separate issue.

**Comment by sbc100** [comment]
It looks like it should work if you do `eval $(emsdk construct_env)`.. can you try that and echo your $PATH afterwards?

**Comment by gaekwad** [comment]
That does the same as `. emsdk_env.sh`  It looks like it's trying to execute the warning line as a command and then stopping.  I didn't notice that before...

```
$ eval $(emsdk construct_env)
Adding directories to PATH:
PATH += /c/emsdk
PATH += /c/emsdk/upstream/emscripten
PATH += /c/emsdk/node/12.18.1_64bit/bin
PATH += /c/emsdk/python/3.7.4-pywin32_64bit
PATH += /c/emsdk/java/8.152_64bit/bin

Setting environment variables:
EMSDK = C:/emsdk
EM_CONFIG = C:/emsdk/.emscripten
EM_CACHE = C:/emsdk/upstream/emscripten/cache
EMSDK_NODE = C:/emsdk/node/12.18.1_64bit/bin/node.exe
EMSDK_PYTHON = C:/emsdk/python/3.7.4-pywin32_64bit/python.exe
JAVA_HOME = C:/emsdk/java/8.152_64bit
bash: Warning:: command not found

$ echo $PATH
.:/c/msys/1.0/home/user/bin:/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/c/msys/1.0/home/user/apache-ant-1.9.6/bin:/usr/i686-w64-mingw32/sys-root/mingw/bin
```

**Comment by sbc100** [comment]
Ah, lets if if redirecting that warning to stderr fixes that ..  I will upload a PR now (maybe you could try locally modifying to confirm?)

**Comment by gaekwad** [comment]
Yup it looks like that worked.  I just simply added ", file=sys.stderr" to the end of the print on line 65 in emsdk.py.  Thanks for the help :)
