### ISSUE TITLE
Exception handling is optimized out, even with -s DISABLE_EXCEPTION_CATCHING=0

### ISSUE THREAD

**Issue by 73UJ34** [emscripten-core/emsdk#387]
I have a simple emscripten 1.39.2 CMake html5 test app that throws an int within a try block and the catch block doesn't get called. I have added -s DISABLE_EXCEPTION_CATCHING=0 like this:

set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "-s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 --shell-file ${CMAKE_SOURCE_DIR}/emscripten_template.html -s EXPORTED_FUNCTIONS=\"['_main']\"")

Here's the output from Chrome:

trycatch_test.js:2004 main enter
trycatch_test.js:2004 main try
trycatch_test.js:2629 exception thrown: 5247016
callMain @ trycatch_test.js:2629
trycatch_test.html:1 Uncaught (in promise) 5247016

Here's the test app:

#include <stdio.h>
#include <emscripten.h>

int main(int argc, const char * argv[]) {

	printf("main enter\n");

	try
	{
		printf("main try\n");
		throw 0;
	} catch (int e) {
		printf("main catch(%d)\n", e);
	} catch (...) {
		printf("main catch(...)\n");
	}

	printf("main exit\n");
}

What am I doing wrong?

**Comment by kripken** [comment]
Note that with the upstream backend, codegen is done during compile, and not link as with fastcomp,

https://emscripten.org/docs/compiling/WebAssembly.html#backends

So you need to pass `-s DISABLE_EXCEPTION_CATCHING=0` during both compile and link. Maybe that's the issue here?

**Comment by 73UJ34** [comment]
Sorry for being dense but I can't figure out how to specify this in my 3.6.2 CMakeLists.txt file. I assume it has to go in the first file at the head of the directory tree, but I could be wrong. Here is what I tried there:

#	target_compile_options(target PRIVATE "-s DISABLE_EXCEPTION_CATCHING=0")
#	set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-s DISABLE_EXCEPTION_CATCHING=0")
#	set_property( TARGET ${PROJECT_NAME} PROPERTY COMPILE_FLAGS "-s DISABLE_EXCEPTION_CATCHING=0")
#	set_source_files_properties(*.* PROPERTIES COMPILE_FLAGS "-s DISABLE_EXCEPTION_CATCHING=0")
#	set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_OPTIONS "-s DISABLE_EXCEPTION_CATCHING=0")
#	target_compile_options(${PROJECT_NAME} PRIVATE "-s DISABLE_EXCEPTION_CATCHING=0")

I also tried these in the last file but no joy.

Any help would be appreciated.

**Comment by kripken** [comment]
I'm not a cmake expert, but it looks like in new enough cmake [you can do](https://stackoverflow.com/a/21561742)
```cmake
add_compile_options(-s DISABLE_EXCEPTION_CATCHING=0)
```
Might need quoting for two separate flags. You can also do
```
```cmake
add_compile_options(-fexceptions)
```
as that turns on exceptions in emscripten.

**Comment by 73UJ34** [comment]
That was what I needed. Thanks so much for your help.
