### ISSUE TITLE
Supporting source compilation for upstream? (ARM Linux etc)

### ISSUE THREAD

**Issue by brion** [emscripten-core/emsdk#391]
emsdk supports building from source, but as far as I know only for fastcomp -- the clang-* tools all point to fastcomp, not upstream.

This is ok on platforms with generated binaries to download, but there are niche users on ARM and Aarch64 Linux machines. If we can't get ARM & Aarch64 binaries in the near term, it would be nice to be able to build upstream locally through emsdk rather than having to manually manage a `~/.emscripten`, dependencies, and build setup.

I can confirm that upstream as of a few days ago builds manually and runs on Ubuntu 18.04 Aarch64, and will do some tests on 32-bit ARM systems as well soon. I'd be happy to put together a patch for this (I did some earlier patches to get fastcomp building on ARM/Aarch64, which was super useful for me in the past!), though will need some help and review on it.

Thanks!

**Comment by kripken** [comment]
@brion That would be great! The only reason it's not supported yet is no one has had time to do it, but definitely it would be good to have.

**Comment by brion** [comment]
Great, I've confirmed its working manually built for both 32 and 64 bit arm, will try this weekend to patch up emsdk...

**Comment by brion** [comment]
Didn't have a chance earlier, but in the meantime building the upstream LLVM SDK has come back. :)

Looks like binaryen isn't getting installed from source on ARM64 Linux though, so that still needs some work -- currently attempts to build with `emcc` complain that `BINARYEN_ROOT` is unset and barf out, but I can set it manually.

**Comment by brion** [comment]
My BINARYEN_ROOT problem is resolved by my patch for issue 434. I'll go ahead and close this one out.

**Comment by brion** [comment]
Hmm, actually I get  failure when running `emcc`:

```
shared:ERROR: error parsing binaryen version (wasm-opt version  (version_90-59-g9384ff68e)). Please check your binaryen installation (/home/brion/src/emsdk/binaryen/master_64bit_binaryen/bin/wasm-opt)
FAIL: Compilation failed!
```

**Comment by sbc100** [comment]
OK this is a different issue.   I can't repro that issue locally so maybe you can help me solve it.

This issue seems to imply that `CMAKE_PROJECT_VERSION` ends up being the empty string.   Which should never happen.

What version of cmake are you using?  Does a clean build solve it?

**Comment by brion** [comment]
cmake 3.10.2 on Ubuntu 18.04 (aarch64) running under Windows Subsystem for Linux.

Trying a fresh build now to make sure it's not just a broken build dir... WSL shouldn't be interfering, but if I can't resolve this I'll test on a fully native Linux box next week (I'm out of town atm so only have the one ARM machine with me)

**Comment by brion** [comment]
Aha, I think `CMAKE_PROJECT_VERSION` is new in 3.12 per the release notes https://cmake.org/cmake/help/latest/release/3.12.html

**Comment by brion** [comment]
Replacing one use of `CMAKE_PROJECT_VERSION` with the older `PROJECT_VERSION` seems to fix the build for me; see linked PR on binaryen: https://github.com/WebAssembly/binaryen/pull/2632

**Comment by brion** [comment]
Ok that's merged so this should be all working now. :D
