### ISSUE TITLE
emsdk update does fail with 403 from AWS

### ISSUE THREAD

**Issue by diegocr** [emscripten-core/emsdk#412]
```
$ emsdk update
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip': HTTP Error 403: Forbidden
Fetching all tags from Emscripten Github repository...
Done. 181 tagged releases available, latest is 1.39.4.
Fetching all tags from Binaryen Github repository...
Done. 90 tagged Binaryen releases available, latest is 1.39.1.
Fetching all precompiled tagged releases..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_32bit/index.txt': HTTP Error 403: Forbidden
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt': HTTP Error 403: Forbidden
```

**Comment by kripken** [comment]
This looks like https://github.com/emscripten-core/emscripten/issues/5291#issuecomment-308078622 but I can't quite understand what the issue was there - @juj do you remember?

**Comment by juj** [comment]
Is Mozilla's bucket even used anymore? @diegocr: Try `git pull`ing emsdk to latest?

**Comment by kripken** [comment]
Oh, right, the URL is old here... sorry I missed that before.

@diegocr updating the emsdk should work, as @juj said. Only old versions of the emsdk will use those old URLs, which are no longer valid.

**Comment by diegocr** [comment]
Thanks guys.

So, i have downloaded this repo files (_Download as ZIP_) and replaced those i had in `C: \emsdk`, then ran the update command:

```bash
$ emsdk update
Downloading: C:/emsdk/zips/master.zip from https://github.com/emscripten-core/emsdk/archive/master.zip
Unpacking 'C:/emsdk/zips/master.zip' to 'C:/emsdk'
Unzipping file 'C:/emsdk/zips/master.zip' failed due to reason: [Error 3] El sistema no puede encontrar la ruta especificada: '\\\\?\\C:unzip_temp\\'
```
^the Spanish message is about being unable to find the path where the zip should be extracted...

I am not very familiar with Python and whether `__file__` is expected to contain an UNC path or otherwise there is something funky from my side/OS, given:

https://github.com/emscripten-core/emsdk/blob/2546d5ab51e8c950e6301799efcdce64ef441667/emsdk.py#L141-L142

```bash
$ python
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.dirname(os.path.realpath(""))
'C:\\'
>>>
```

fwiw, `emsdk update` was working fine a couple of months ago or so, but i can see in the commit history here that there was some rewrite of the script, so looks like those recent changes is causing trouble.

While under Windows it might be better using `%TEMP%` as the destination where to extract the zips.

**Comment by diegocr** [comment]
Uhm, sorry inspecting further the script i can now see the UNC path comes from it, from the function `fix_potentially_long_windows_pathname`

https://github.com/emscripten-core/emsdk/blob/2546d5ab51e8c950e6301799efcdce64ef441667/emsdk.py#L501

...and well, the issue itself must be because i just did recall that i have network shares disabled, among a ton of other system services...

So, apart from preferably using the `TEMP` envar, i think it will also be good checking whether UNC paths can be accessed before attempting to use them.

**Comment by diegocr** [comment]
Any update - or further thoughts - on this please?

Should I perhaps attempt to fix this myself and submit a PR? (despite my overall lack of Python experience i could try to do it)

**Comment by kripken** [comment]
@diegocr yes! :smile: if you can fix this locally please submit a PR, that would be great. It may be a small fix and not need much python knowledge.

**Comment by diegocr** [comment]
Hi @kripken, here you go #438 

Cheers!

**Comment by sbc100** [comment]
I'm not sure what the problem is here exactly but I don't think that looks like the correct fix.

When updating emsdk the logic looks like it unzips to a folder alongside the existing emsdk with the name `unzip_temp`.   

It should be up the unzipping logic to create the `unzip_temp` directory before trying to write things there.

**Comment by diegocr** [comment]
Hi @sbc100, the issue has noting to do with creating a directory where to unzip, it's with accessing paths prefixed with `'\\\\?\\'`

**Comment by sbc100** [comment]
Are you totally sure about that?  Do those paths not work on some windows setups?  I've not seen that style before but I assume it works on all windows machines or none at all, no?

I sitll don't understand you fix though because can't fix_potentially_long_windows_pathname be used to construct paths that don't actually exists (like os.path.join()?).  i.e. so the inputs to these function need to exist on the disk, or is it just string manipulation?

**Comment by diegocr** [comment]
I do have a bunch of system services disabled, including network shares, that's why these paths are not useable/accessible here (I think)

>  ... be used to construct paths that don't actually exists

Fair point, actually i hadn't checked that. If that is a real/actual use case within the script, then my patch will defeat that behavior i'm afraid :(

**Comment by sbc100** [comment]
I'm afraid I don't know about about this UNC paths scheme that windows has.   Are you able to consistently reproduce this with the latest emsdk?   What makes you think its related to network shares?

Does it happen regardless of where you install emsdk or only if you install it in the root of C:?

**Comment by diegocr** [comment]
Er... well, i may be mistakenly calling "unc path" to anything that begins with "\\\\" 😅 

and yes, i am using the latest emsdk of course, i just performed a quick test, and `dir \\?\C:\\emsdk\\` does work fine, while `dir \\?\C:emsdk\\` does not. Therefore, the issue is with the removed slash as the issue here was with the path `\\\\?\\C:unzip_temp\\` 🤦‍

Interesting no other Windows user(s) noticed this, though 🤔 

Alright, i will adapt my PR accordingly...

**Comment by juj** [comment]
> I do have a bunch of system services disabled, including network shares, that's why these paths are not useable/accessible here (I think)

To my understanding UNC paths should not depend on whether network sharing is enabled - even though they can be used to reference paths on a network.

Emsdk uses UNC path names to work around Windows max path length limitation.

One limitation of UNC path names is that they cannot contain forward slashes `/`. Any path that contains a forward slash is not a valid UNC path. (even though Windows supports forward slashes in e.g. `C:/temp/`, as a UNC PATH `\\?\C:\temp/` would not be valid)

**Comment by diegocr** [comment]
Thanks @juj for enlightening us about that, and thanks @sbc100 for the brainstorming session that lead me to figure and fix the real issue :-)

I have now updated my PR, cheers!
