### ISSUE TITLE
emsdk activate clobbers path

### ISSUE THREAD

**Issue by shogerr** [emscripten-core/emsdk#414]
Let's say one needs to run a .bat to invoke the VS development environment in Windows, if a user then activates an emsdk environment, that use will lose the environment sourced previously.

This turns into a big headache if you need cl.exe, or nmake.exe, or any tools that emsdk does not provide.

It's sort of related to this issue, https://github.com/emscripten-core/emsdk/issues/175. I didn't notice this until I actually tried to compile. cmd.exe, pwsh.exe, cl.exe, nmake.exe have all been stripped from my path after activating emsdk.

Is there any other way to get emsdk into my path? this issue renders emsdk unuseable at the moment, because Qt requires the MSVC dev environment and emsdk to both be active.

**Comment by kripken** [comment]
Thanks for filing this @shogerr! Without that we may have forgotten this for a lot longer...
