### ISSUE TITLE
Running emcc for first time

### ISSUE THREAD

**Issue by cranei** [emscripten-core/emsdk#418]
Using Windows 10 Home Premium installed latest Emscripten. When I run emmcc -V (or anything) I get error:

shared:ERROR: BINARYEN_ROOT is set to empty value in C:\Users\Jim/.emscripten

the .emscripten file contains the lines:

LLVM_ROOT = os.path.expanduser(os.getenv('LLVM', '/usr/bin')) # directory
BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN', '')) # directory

I am unable to progress and none of the other issues seem to show this. Your help would be appreciated.

**Comment by cranei** [comment]
Sorry to be a nuisance everyone....
Got it working finally with the tot version - runs like a greyhound!
Please cancel any problem I reported.

**Comment by seisvelas** [comment]
I'm having the same problem on MacOS. What is the 'tot' version and how do I get it so I can resolve this?

**Comment by sbc100** [comment]
`tot` means tip-of-tree.   It means the latest emsdk package to have been tests with no failures.   Ever now and then we take the current tot verson promote it to an official release (after which it is then available via `latest`).

You can use either `tot` or `latest` by using `emsdk`.  e.g:

```
emsdk install tot
emsdk activate tot
```

**Comment by bradharms** [comment]
I'm getting this as well on WSL (windows subsystem for linux). Installing tot does NOT help.

What is BinaryEn?
Why is it not set in the .emscripten file?

**Comment by sbc100** [comment]
I'm not sure we have many WSL users, so there may be some issues there, although my understanding is that it would just work exactly like linux.   

Can you tell the commands you used to install emsdk.

Can you include the full command lines and the full output?

**Comment by sbc100** [comment]
binaryen is one of the dependencies of emscripten.  Its a tool for manipulating the WebAssembly binary and text format.  It should be packaged with the emsdk and setup for you when emsdk creates the config file for emscripten.

**Comment by bradharms** [comment]
I resolved it, sort of. I had to install and activate "latest-upstream."

```
./emsdk install latest-upstream
./emsdk activate latest-upstream
```

**Comment by fmoel** [comment]
Please use the emcmdprompt.bat in the emsdk root directory to start the command prompt. This will set up the command prompt correctly and emcc should work even with latest.

**Comment by bradharms** [comment]
I can't use emcmdprompt.bat because my environment is linux-based.

**Comment by sbc100** [comment]
On linux you should use `source ./emsdk_env.sh`.

**Comment by JCash** [comment]
I can confirm, that the `tot-upstream` didn't work (as suggested by the documentation), as it complained about BINARYEN.
The `latest-upstream` worked though. Thx @bradharms !

**Comment by sbc100** [comment]
Installing `tot-upstream` should certainly work.  Before you install any `tot` builds you need to first run `./emsdk update-tags`.  Maybe you didn't do that?  Also you don't need the `-upstream`... just `tot` is enough.

**Comment by Noah1989** [comment]
This happens when you try to run `emcc` after `./emsdk install` without activating the SDK through `./emsdk activate` first. It will try to generate the `.emscripten` file automatically, and just leaves BINARYEN_ROOT empty.

**Comment by kenorb** [comment]
On macOS, I've edited `/usr/local/Cellar/emscripten/*/libexec/.emscripten` file and replaced the line with BINARYEN_ROOT to `BINARYEN_ROOT = '.'` (as it was empty).

**Comment by DevAndromeda** [comment]
> On macOS, I've edited `/usr/local/Cellar/emscripten/*/libexec/.emscripten` file and replaced the line with BINARYEN_ROOT to `BINARYEN_ROOT = '.'` (as it was empty).

this worked on windows too

**Comment by denormative** [comment]
For future google-ers, I had this as well, and the solution was to delete my `~/.emscripten` file and recreate it since it was last edited in 2019 and must have had some severely outdated config. :/
