### ISSUE TITLE
[Feature Request, RFC] API for calling C++ command line program from Javascript with arguments and files.

### ISSUE THREAD

**Issue by marciot** [emscripten-core/emsdk#428]
I've used Emscripten for several projects and one issue I run into often is that it is very difficult to interact with command line programs from an HTML web app. I feel the capability is there somehow if you manage to make the correct bindings, but this is far from trivial and there isn't an easy API for doing so. If this feature does exist, please let me know where it is documented. If it does not, I would propose a set of requirements and get some feedback from devs on how feasible it would be make an API like this. Here are the requirements for the API:

- Allow a command-line program to be started using one or more command line arguments.
- Allow virtual "files" to be loaded from Javascript (i.e. they could be passed on as an array of bytes) prior to starting such program. 
- Either run the program on the current thread, or have it in a separate thread (maybe a web worker?)
- Have the ability to capture stdout and stderr and act on the output (possibly at real-time via a callback).
- Have the ability to load data into stdin (possibly in response to stdout).
- Have a means of detecting when the program has finished and get the status code.
- Allow multiple command line utilities to be packaged as one and executed individually.

If such an API existed, here is a hypothetical webpage that compressed a text string using the command-line "gzip" utility:

```
<html>
   <head>
      <script src="gzip.wasm.js">
      <script src="emscripten.js">
      <script>
           proc = new EmscriptenProcess("gzip");

           function doIt() {
               proc.addArgument("-c");
               proc.addArgument("-");
               proc.stdin = getElementById("in").text
               proc.onCommandExecuted = doneIt;
               proc.startAsWorker();
           }

           function doneIt() {
               if (proc.status == 0) {
                  getElementById("out").text = proc.stdout;
               } else {
                   alert("Error:" + proc.stderr);
               }
           }
      </script>
   </head>
   <body>
       Uncompressed Text: <textarea id="in">Hello world!</textarea>
       Compressed Text: <textarea id="out"></textarea>
       <button onClick="doIt();">Compress It</button>
   </body>
</html>
```

Anyhow, this is a pie in the sky idea. I know very little about how Emscripten works internally, so I do not know how difficult or whether it would be possible to do something like this at all. That said, from a user perspective, however, it would be fantastic; if something like this existed, I think it would make Emscripten a lot more approachable by a lot of people who simply wanted to run existing command line tools in their web pages without having to modify the original source.

**Comment by marciot** [comment]
Unclear whether this belongs in emsdk or emscripten. So this has been duplicated as #10277. I can close down one or the other once I learn where it belongs.

**Comment by juj** [comment]
Emscripten cannot bypass web security that browsers provide. It is not possible to open a native process from a web page, that would allow all sorts of attacks to your system if one visited a site that just went ahead and launched programs from your computer?

**Comment by juj** [comment]
Oh now I see the gzip.wasm.js in the proposal. So the intent would be to compile wasm programs and implement subprocess semantics on them.. that could be done if someone wanted to build such an ecosystem, but it would definitely not be a default build mode. Subprocesses could be modeled as web workers I think.

**Comment by kripken** [comment]
Let's close this one, as I think this makes more sense in emscripten.
