### ISSUE TITLE
No BINARYEN_ROOT in .emscripten for master branch SDKs

### ISSUE THREAD

**Issue by floooh** [emscripten-core/emsdk#434]
It seems like an ```emsdk activate sdk-upstream-master-64bit``` doesn't write BINARYEN_ROOT to the .emscripten config file (happens on macOS, but I think it's not OS specific).

This in turn causes compilations issues later when trying to build with this SDK:

```
shared:ERROR: BINARYEN_ROOT is not defined in /Users/floh/projects/fips-sdks/emsdk/.emscripten
```

Also see this thread:

https://groups.google.com/forum/#!topic/emscripten-discuss/fvmSMLFIj5c

I did some python debugging, and this line here:

https://github.com/emscripten-core/emsdk/blob/deaa7e4bfd79246f02f785c8f2174d1e74ab6c00/emsdk.py#L2498

Returns the following "tools_to_activate":

- llvm-git-master-64bit
- node-12.9.1-64bit
- emscripten-master-64bit
- sdk-upstream-master-64bit

None of those have BINARYEN_ROOT in their "activated_cfg":

- llvm-git-master-64bit: **LLVM_ROOT='%installation_dir%/%fastcomp_build_bin_dir%**
- node-12.9.1-64bit: **NODE_JS='%installation_dir%/bin/node%.exe%'**
- emscripten-master-64bit: **EMSCRIPTEN_ROOT='%installation_dir%';EMSCRIPTEN_NATIVE_OPTIMIZER='%installation_dir%%generator_prefix%_64bit_optimizer/%cmake_build_type_on_win%optimizer%.exe%'**
- sdk-upstream-master-64bit: no "activated_cfg" member, because it's not a "tool"

I think some dependency got lost during the incoming -> master transition. I tried adding "binaryen-master-64bit" as dependency to the right SDK entry (since those had been removed in the update), but this gives a warning about binaryen not being installed:

```
Warning: The SDK/tool 'binaryen-master-64bit' cannot be activated since it is not installed! Skipping this tool...
```

(so I think the proper solution is to add BINARYEN_ROOT to ```activated_cfgs``` of one of the 3 tools, e.g. llvm-git or emscripten)

**Comment by brion** [comment]
Possibly related, I'm unable to build `binaryen-master-64bit` via emsdk on macOS Catalina:

```
In file included from /Users/brion/src/emsdk/binaryen/master/src/cfg/Relooper.cpp:17:
/Users/brion/src/emsdk/binaryen/master/src/cfg/Relooper.h:29:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
```

etc

Either my Xcode broke or something's going weird?

**Comment by brion** [comment]
I removed the `binaryen/master` and `binaryen/master_64bit_binaryen` dirs and re-ran and it builds now. Something got messed up in the build dir I guess... if the same happened to you it might not have installed properly. I'm testing adding the `"binaryen-master-64bit"` into the `"uses"` sections to see if that helps

**Comment by brion** [comment]
@floooh can you test with my emsdk patch and a clean build dir? Seems to work for me now on macOS, haven't tested Linux yet.

**Comment by floooh** [comment]
@brion I'll try to test your fix tomorrow. Regarding the problem that cmake projects on macOS suddenly don't build, I think I've seen that too after Xcode updates, maybe cmake stores absolute paths in the generated build files, and when Xcode switches to a new SDK, the paths in the cmake build dir no longer match.

**Comment by brion** [comment]
Confirmed this patch also resolves my build on Linux/arm64.

@floooh yeah I've seen cmake store absolute paths and break after xcode or homebrew updates, could be that...

**Comment by floooh** [comment]
Ok, working fine here too (macOS Catalina 10.15.3 Beta (19D62e)).

**Comment by sbc100** [comment]
Sounds like we can close this now?

**Comment by brion** [comment]
I think we're good on this now yeah, macOS and both Linux/arm64 resolved. :D
