### ISSUE TITLE
SDK (emcc) suddenly broken after machine reboot

### ISSUE THREAD

**Issue by Toninoso** [emscripten-core/emsdk#442]
I was working with sdk just fine until yesterday.
Because of Windows 10 update my PC was rebooted.

Reentered SKD environment in Windows CMD prompt via  emsdk_env.bat.

A simple C file with one function that compiled fine yesterday doesn't compile anymore.

```
D:\Play\ChromiumIntercept>emcc -Os MovingAverage.c -s EXPORTED_FUNCTIONS='["_mavg"]' -o MovingAverage.wasm
Traceback (most recent call last):
  File "D:\Emscripten\emsdk-master\upstream\emscripten\emcc.py", line 3905, in <module>
    sys.exit(run(sys.argv))
  File "D:\Emscripten\emsdk-master\upstream\emscripten\emcc.py", line 1394, in run
    shared.Settings.EXPORTED_FUNCTIONS += ['_malloc', '_free']
TypeError: can only concatenate str (not "list") to str

```

Reinstalled and reactivated the sdk from scratch via:

```
emsdk install latest
emsdk activate lastest
```

No change, the same error keeps popping no matter the options and input to emcc.

```
D:\Play\ChromiumIntercept>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 11.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 9dc84e9b02d1e402503906099d42fbae4da7d8d9)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:/Emscripten/emsdk-master/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)

```

**Comment by Toninoso** [comment]
Strange :

Just changing from EXPORTED_FUNCTIONS='["_mavg"]' (which worked just fine before) to
EXPORTED_FUNCTIONS=["_mavg"] (no single quotes) fixed the issue.

I can't account for a change in behavior: maybe previously I was running from Powershell prompt instead of CMD prompt. Maybe I re-activated sdk and got Python 3 instead of Python 2 activated.

**Comment by Toninoso** [comment]
Closing the issue, although not understanding the cause.

**Comment by sbc100** [comment]
Hmm.. I still consider this a bug.  Bad user input should not lead to python crash like this.
