### ISSUE TITLE
How do I specify that wasm memory will be imported, rather than exported

### ISSUE THREAD

**Issue by Toninoso** [emscripten-core/emsdk#443]
Playing with various compilation flags for WASM output and then inspecting the S-expressions code in text format I found that memory is sometimes imported and sometimes exported. This introduces unpredictability if not using generated JS.

If I always want to allocate WASM memory on JavaScript side how do I **force** memory to be imported?

Whatever memory allocator I select via EMCC, it should be able to work both with imported and exported memory?

**Comment by Toninoso** [comment]
I don't understand all the issue with memory allocation but, even if I settle for Emscripten generated JS (very likely) I have an impression, working on one case, that I may want to decide if memory is imported or exported.

**Comment by kripken** [comment]
Emscripten will normally import the memory. The idea is that creating it early in JS (before the wasm even loads) allows us to do some work in parallel to the wasm being compiled (for example, we can preload files and other things).

However, if you use [standalone wasm mode](https://v8.dev/blog/emscripten-standalone-wasm) (`-s STANDALONE_WASM` or you specify an output file that is only `*.wasm`) then the wasm must stand by itself, and not depend on JS to create a memory for it. In that case the wasm creates the memory, and exports it.

**Comment by Toninoso** [comment]
I understand from the answer that, while it may be convenient to have an extra flag in some development use cases, user can always make generated WASM file import the memory by specifying *.js or *.html output as the last step in development. Closing this issue.
