### ISSUE TITLE
undocumented changes in emsdk 1.39.0 broke the compilation of SQLite in sql.js

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emsdk#446]
See https://github.com/kripken/sql.js/issues/353

[sql.js](https://github.com/kripken/sql.js) is compiled with emsdk v1.38.48 in master. Trying to compile it with emsdk v1.39.0 breaks the tests with the following error : *Unable to grow wasm table. Use a higher value for RESERVED_FUNCTION_POINTERS or set ALLOW_TABLE_GROWTH*. (sql.js is compiled with RESERVED_FUNCTION_POINTERS=16).

The [changelog for emsdk 1.39.0](https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md#v1390-10182019) does not mention any change related to RESERVED_FUNCTION_POINTERS. Could the changes be documented so that we can migrate to the latest emsdk ?

**Comment by kripken** [comment]
Sorry about this inconvenience! The change here is the big switch from the old fastcomp backend to the new upstream one. Those are almost interchangeable but not 100%.

Docs fix is in https://github.com/emscripten-core/emscripten/pull/10608 - you should just set `ENABLE_TABLE_GROWTH` in the new backend, as growth is easy and works well in wasm (but not in fastcomp, where the tables are fixed-size).

**Comment by lovasoa** [comment]
Does it mean that there is no sustainable way to continue to provide asm.js builds ? Either we use the old deprecated backend, or we switch to the new one, and must drop asm.js builds ?
asm.js builds are easier to setup for users, because they work out-of-the-box, whereas wasm builds require users to add the wasm file to their assets, and then manually setup the path to assets when they launch the library.

**Comment by lovasoa** [comment]
Oh, sorry, I should have read the docs more carefully. I see that both backends support emitting plain javascript.

**Comment by kripken** [comment]
Yes, the new backend can emit a JS build too. It isn't literal asm.js syntax, but it is more flexible (supports more wasm features) and smaller.

**Comment by lovasoa** [comment]
Maybe something that should be mentioned in [the page about the differences between backends](https://emscripten.org/docs/compiling/WebAssembly.html#backends) is the backwards-incompatible behavior of [addFunction](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html?highlight=addfunction#calling-javascript-functions-as-function-pointers-from-c)
