### ISSUE TITLE
Python version confusion (Assuming Python3)

### ISSUE THREAD

**Issue by trasherdk** [emscripten-core/emsdk#447]
Running on `Slackware64 14.2`, trying to compile [monero-javascript](https://github.com/monero-ecosystem/monero-javascript/tree/master_core_wallet) ...

After doing the `emsdk` install steps:
```
cd emsdk
git pull
./emsdk install latest-upstream
./emsdk activate latest-upstream
source ./emsdk_env.sh
export EMSCRIPTEN=/absolute/path/to/emsdk/upstream/emscripten
```
A build boost script, trying to build zlib:
```
cd $EMSCRIPTEN; ./embuilder.py build zlib
```
I see following error: `/usr/bin/env: ‘python3’: No such file or directory`
```
$ python --version
Python 2.7.17
```

Checking Python files in EMSCRIPTEN directory gives:
```
$ head -n 1 ${EMSCRIPTEN}/upstream/emscripten/*.py
==> upstream/emscripten/emar.py <==
#!/usr/bin/env python3

==> upstream/emscripten/embuilder.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emcc.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emcmake.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emconfigure.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emlink.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emmake.py <==
#!/usr/bin/env python3

==> upstream/emscripten/em++.py <==
#!/usr/bin/env python

==> upstream/emscripten/emranlib.py <==
#!/usr/bin/env python

==> upstream/emscripten/emrun.py <==
#!/usr/bin/env python

==> upstream/emscripten/emscons.py <==
#!/usr/bin/env python3

==> upstream/emscripten/emscripten.py <==
# Copyright 2010 The Emscripten Authors.  All rights reserved.

==> upstream/emscripten/emsize.py <==
#!/usr/bin/env python
```

**Comment by sbc100** [comment]
We should certainly update any scripts that don't call python3 directly.  I'm not sure how I missed some of those in #10357.

However, emscripten still supports both python2 and python3 so if you don't have a binary on your system called python3 you can still run `$ pyhon ./embuilder.py` to use your python2 binary.

All of the tools should use sys.executable for all subprocesses.

**Comment by trasherdk** [comment]
I was kinda expecting `#!/usr/bin/env python` to be the correct one, as that would be a symlink to whatever version is installed.

I could run a `sed` on those scripts, but think it should be a job for either `./emsdk install latest-upstream` or `./emsdk activate latest-upstream`

I'm aware of the `$ pyhon ./embuilder.py` trick, but building 3rd-party packages, that are downloaded, and build by scripts, leaves you (me) with a shitload of trial-error-debugging-patching.

**Comment by sbc100** [comment]
We want to make python3 the default and I'd rather be explicit.   We plan to drop python2 support ASAP.

Can you install python3 your system?

On debian and ubuntu at least, you run bare `python` you always get python2 (at last today).

**Comment by trasherdk** [comment]
Well, I'm running Slackware x86_64 14.2 on 14 boxes, and I'm sitting 7000+ Km away :)

Python3 is not an option, unless I bake an install package myself, and maintain that package forever.

**Comment by sbc100** [comment]
I don't understand.  python3 has been out for 12 years (https://www.python.org/download/releases/3.0/). How can there be no package available for slackware?

We are not planning on dropping python2 support right now, but we certainly want to do that at some point.

**Comment by trasherdk** [comment]
`Slackware 14.2` is a `stable` distribution. It's only upgraded with security patches.
ex. Kernel is at ver. 4.4.208 Not exactly bleeding edge :) On the other hand, it's rock solid,
perfect for servers. Take away all the GUI stuff, and it's even kinda lightweight.

I'll try to install a parallel Python3 on a test server, to see if it's possible to use both versions without breaking stuff.

There's a `Slackware Current` variant, keeping up with latest safe releases of pretty much everything available in the Slackware distribution. But then I would be spending all my time upgrading servers.

**Comment by trasherdk** [comment]
`Slackware 14.2` is a `stable` distribution. It's only upgraded with security patches.
ex. Kernel is at ver. 4.4.208 Not exactly bleeding edge :) On the other hand, it's rock solid,
perfect for servers. Take away all the GUI stuff, and it's even kinda lightweight.

I'll try to install a parallel Python3 on a test server, to see if it's possible to use both versions without breaking stuff.

There's a `Slackware Current` variant, keeping up with latest safe releases of pretty much everything available in the Slackware distribution. But then I would be spending all my time upgrading servers.
