### ISSUE TITLE
‘./emsdk install’ always fails

### ISSUE THREAD

**Issue by Sunzhuoyi** [emscripten-core/emsdk#454]
operating system: OS X
prerequisites are in place
all of these  failed
```
➜  emsdk git:(master) ./emsdk install sdk-incoming-64bit binaryen-master-64bit
Error: No tool or SDK found by name 'sdk-incoming-64bit'.
➜  emsdk git:(master) ./emsdk install sdk-fastcomp-incoming-64bit
Error: No tool or SDK found by name 'sdk-fastcomp-incoming-64bit'.
➜  emsdk git:(master) ./emsdk install sdk-upstream-incoming-64bit
Error: No tool or SDK found by name 'sdk-upstream-incoming-64bit'.
```

**Comment by sbc100** [comment]
To install binaries you can just use `./emsdk install latest`

To install from source the branch name is now just master so `./emsdk install sdk-fastcomp-master-64bit`  or `sdk-upstream-master-64bit` will work

**Comment by sbc100** [comment]
Are the `incoming` names still documented somewhere?  Perhaps we need to update some links/docs?

**Comment by Sunzhuoyi** [comment]
> Are the `incoming` names still documented somewhere? Perhaps we need to update some links/docs?
WA Chinese official website developer's guide.
https://webassembly.org.cn/getting-started/developers-guide/
On the other hand, if there is no maintenance, maybe I can offer some help.

**Comment by Sunzhuoyi** [comment]
> To install binaries you can just use `./emsdk install latest`
> 
> To install from source the branch name is now just master so `./emsdk install sdk-fastcomp-master-64bit` or `sdk-upstream-master-64bit` will work
Thanks, it works.

**Comment by sbc100** [comment]
Great!

**Comment by andycao** [comment]
./emsdk install latest
./emsdk activate latest

see readme of emsdk
