### ISSUE TITLE
error: undefined symbol: __syscall221 while building hello_world_file.cpp

### ISSUE THREAD

**Issue by njduck** [emscripten-core/emsdk#462]
![20200407115824](https://user-images.githubusercontent.com/9101673/78628727-94e3bf00-78c7-11ea-9d72-9f85ab56a430.png)
![20200407115724](https://user-images.githubusercontent.com/9101673/78628816-f441cf00-78c7-11ea-9601-b1a93b739288.png)

gcc works fine.
![20200407120322](https://user-images.githubusercontent.com/9101673/78628793-d5433d00-78c7-11ea-97d7-54df847366ee.png)

Any idea?

**Comment by sbc100** [comment]
Try clearing you cache (`emcc --clear-cache`).  Those symbols recently got renamed.
