### ISSUE TITLE
[bug]Latest version (26/04/2020) produces "No module named 'distutils.spawn'"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [emscripten-core/emsdk#480]
I have installed emsdk under Kubuntu 64 bit
`Linux fcaruso-VirtualBox 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
`emcc` produces "No module named 'distutils.spawn'"
```
fcaruso@fcaruso-VirtualBox:~/emsdk$ emcc -v
Traceback (most recent call last):
  File "/home/fcaruso/emsdk/upstream/emscripten/emcc.py", line 42, in <module>
    import emscripten
  File "/home/fcaruso/emsdk/upstream/emscripten/emscripten.py", line 25, in <module>
    from tools import shared
  File "/home/fcaruso/emsdk/upstream/emscripten/tools/shared.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
```

**Comment by sbc100** [comment]
I think this was fixed recently in #10948.

**Comment by Fabrizio-Caruso** [comment]
@sbc100 it is not fixed in the latest version as I am reporting now. So it was either never really fixed or it has been broken again. The fix probably never work.

**Comment by Fabrizio-Caruso** [comment]
Sorry, so it is fixed but not available yet in the latest realise? Which exact commands do I neef to run to install a fixed version?

**Comment by sbc100** [comment]
```
./emsdk update-tags
./emsdk install tot
```

Alternatively you could just `apt-get install python3-distutils`.    I'm really not sure why debian/ubuntu decided to split that out from the main python3 package.

**Comment by Fabrizio-Caruso** [comment]
Thanks, it does work now. Is this behavior the expected one. Should I close this issue?

**Comment by Fabrizio-Caruso** [comment]
I can now compile a trivial hello world example which runs under nodejs but won't run on the browser as reported in #481. Is this related to some missing packages?

**Comment by sbc100** [comment]
That looks unrelated.  Please go ahead and close this issue if the distutils problem is now fixed.

**Comment by Fabrizio-Caruso** [comment]
@sbc100 Thanks. I am assuming that it is fixed if the update-tags and install tot fixes it for me.
