### ISSUE TITLE
[bug?] Hello World won't run in browser

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [emscripten-core/emsdk#481]
If I compile a simple hello world example:
```
#include<stdio.h>

int main()
{
    printf("Hello world\n");
    return 0;
}
```
I get a working .js that I can run with nodejs but the hmll won't start and loop forever saying "Preparing..."

![image](https://user-images.githubusercontent.com/29057615/80315908-f1693880-87fa-11ea-8132-d8b1992eb6e1.png)

**Comment by sbc100** [comment]
wasm modules can't be loaded via the `file://` protocol.  You need to use some kind of http server.  See `https://emscripten.org/docs/getting_started/Tutorial.html#generating-html` and have a look at the `emrun` program.

**Comment by Fabrizio-Caruso** [comment]
Sorry. My fault.
