### ISSUE TITLE
construct_env with activate --embedded won't list paths to node and upstream/emscripten

### ISSUE THREAD

**Issue by nokotan** [emscripten-core/emsdk#497]
While creating docker image with emscripten, I got following error:
```sh
/bin/bash: em++: command not found
```
This appears to be because emsdk_set_env.sh (emitted with `./emsdk construct_env`) does not add path to node and upstream/emscripten.
```sh
# emsdk_set_env.sh
export PATH="/emsdk_portable:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export EMSDK="/emsdk_portable"
```
and content of .emscripten file is:
```txt
import os
emsdk_path = os.path.dirname(os.environ.get('EM_CONFIG')).replace('\\', '/')
CACHE = emsdk_path + '/.emscripten_cache'
NODE_JS = emsdk_path + '/node/12.9.1_64bit/bin/node'
LLVM_ROOT = emsdk_path + '/upstream/bin'
BINARYEN_ROOT = emsdk_path + '/upstream'
EMSCRIPTEN_ROOT = emsdk_path + '/upstream/emscripten'
```
While changes in [emsdk.py:1486](https://github.com/emscripten-core/emsdk/blob/master/emsdk.py#L1486), `emsdk_path + '` is still expected to be `' + emsdk_path + '` in [emsdk.py:1742](https://github.com/emscripten-core/emsdk/blob/master/emsdk.py#L1742)

**Comment by sbc100** [comment]
At yes, its does look like messed up line 1742 in my return change:  https://github.com/emscripten-core/emsdk/pull/495/.   Taking a look now.  Does reverting that change fix this issue?

**Comment by jeromelaban** [comment]
Reverting fixed the issue for me.

**Comment by jeromelaban** [comment]
Confirmed that your update works, thanks @sbc100!
