### ISSUE TITLE
error while using compiled library files, error: unknown file type .so 

### ISSUE THREAD

**Issue by ankitcsr** [emscripten-core/emsdk#511]
wasm-ld: error: unknown file type: /usr/local/lib/libopencv_dnn.so. (while converting c++ )

**Comment by sbc100** [comment]
You can use your system libraries and header files with emscripten.   `/usr/local/lib/libopencv_dnn.so` is almost certainly an x86 library and can't be linked into a wasm binary.

The solution is probably to avoid adding system include and library paths to you command line.
