### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by Stenli1** [emscripten-core/emsdk#520]
I tried to install, but an error occurred. I have virtual machine (VMware) with 64-bit CPU, but install proces write 

root@debian:/download/emsdk# ./emsdk install latest
Error: 'sdk-releases-upstream-9bc968c0e49b1c795ecddb87391b265911e2adcb-64bit' is only provided for 64-bit OSes.

CPU:

root@debian:/download/emsdk# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
stepping        : 0
microcode       : 0xb000022
cpu MHz         : 3199.997
cache size      : 25600 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 6399.99
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

please help. Thanks

**Comment by sbc100** [comment]
It looks like you have installed a 32-bit version of debian on your virtual machine.  Even though the CPU is 64-bit doesn't mean the linux installation is.   

What does `dpkg-architecture` say?

**Comment by Stenli1** [comment]
I am sorry. You're right. System is x86 architecture. It is beginner issue. Any solve for x86 architecture? Or I mus reinstall OS? Thanks.

**Comment by sbc100** [comment]
You should re-install.   x86 might work, but you would need to build everything from source, and we don't test the x86 toolchain (just like we don't test any other architectures like arm).    We don't really see much reason to support x86-32 for development.

**Comment by sbc100** [comment]
Please close this issue if you feel like you have a solution.

**Comment by Stenli1** [comment]
Of course I understand. I reinstall OS to x64. I apologize again and thank you.
