### ISSUE TITLE
docs: specify message locally or globally

### ISSUE THREAD

**Issue by TroyTae** [emscripten-core/emsdk#536]
When I run this command `./emsdk activate latest`, command prints like this:
```
To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.
```
It is written as if both are working globally.
But I 'source ./emsdk_env.sh' works locally.

In documentation page, descried about this:
<img width="440" alt="스크린샷 2020-06-30 오전 10 24 11" src="https://user-images.githubusercontent.com/20078201/86072148-e614e080-babb-11ea-80a9-edcd5d711416.png">

So my suggestion is "how about making message more clear?"

**Comment by sbc100** [comment]
You can also add `source ./emsdk_env.sh` to your .bashrc, and likwise add to your PATH in your bashrc.     So those can work globally if you add them in global place such as your startup files.  

But yes, we could make this more clear perhaps.   What wording do you suggest? 

We could add, `Add these in your bashrc or other startup scripts to have these permanently available.`

**Comment by TroyTae** [comment]
Ah I see, I misunderstood that `emsdk_env.sh` add it to PATH automatically.
How about print message like this?
```
To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH.
Or call 'source ./emsdk_env.sh' to do this for you. (Add these in your bashrc or other startup scripts to have these permanently available)
```
