### ISSUE TITLE
emsdk tool doesn't work at all on Windows

### ISSUE THREAD

**Issue by free-vbucks** [emscripten-core/emsdk#538]
I have absolutely no idea what's wrong. I'm on Windows 10 and have tried Command Prompt and Powershell, with Python 3.7.8 and Java installed. I've tried running emsdk.py, emsdk.bat, and emsdk.ps1, each with commands, and all of them return no output and don't install _anything_. They change absolutely nothing. I tried switching the emsdk tag to 1.39.18, the latest "stable release," and nothing changes. I need lots of help, because my computer doesn't have enough storage to build from source, so I need the pre-built binaries from this tool.

**Comment by sbc100** [comment]
Sounds like maybe your python install is not working correctly.

What does `where python` report? 

What does `python -v` report?

**Comment by sbc100** [comment]
Is this the same as https://github.com/emscripten-core/emscripten/issues/11423.

**Comment by free-vbucks** [comment]
`where python` in Powershell outputs nothing, in Command Prompt it outputs both an installation under "WindowsApps" and an installation under "Programs\Python\Python37", both in AppData. `python -v` outputs nothing in both terminals. And it's probably not the same as issue 11423, because this is an issue with the installer tool, and I haven't gotten around to seeing an exe yet.

**Comment by sbc100** [comment]
Sorry I meant.  If `python --version` doesn't output anything something is broken with the python installation.

**Comment by free-vbucks** [comment]
`python --version` outputs nothing (something is probably broken), but `py --version` returns "Python 3.7.8".

**Comment by sbc100** [comment]
emsdk relies on having a working `python` in your PATH so once you fix that it should start working.   I'm not sure what `py` is .. maybe a windows thing?

**Comment by free-vbucks** [comment]
Probably (it's in windows directory). It comes with Python, and it acted like a python installation and messed up python launching. After reinstalling Python and disabling a weird windows shortcut, it's working now. Thank you!
