### ISSUE TITLE
1.39.20 is not published on Docker

### ISSUE THREAD

**Issue by kleisauke** [emscripten-core/emsdk#567]
It looks like PR https://github.com/emscripten-core/emscripten/pull/11606 moved the `.emscripten_sanity` file to `upstream/emscripten/cache/sanity.txt`, causing a failure in the `publish-docker-image` pipeline, see:
https://app.circleci.com/pipelines/github/emscripten-core/emsdk/560/workflows/a0c9383c-5520-4acf-905c-7e4a35e1515c/jobs/2172

As a result, the 1.39.20 tag has not been published on Docker.
https://hub.docker.com/r/emscripten/emsdk/tags

Perhaps the `cat` here:
https://github.com/emscripten-core/emsdk/blob/9b405d313a22784bae731e7bd33af867d331532a/docker/Dockerfile#L60

Should be changed to `cat ${EMSDK}/upstream/emscripten/cache/sanity.txt` instead? If you want, I could open a PR.

**Comment by kripken** [comment]
@kleisauke can confirm, but I believe that's correct, thanks! PR would be great.
