### ISSUE TITLE
I need a version of 1.38.47 emsdk docker image/container, How to build it?

### ISSUE THREAD

**Issue by yunikoro** [emscripten-core/emsdk#575]
I try to start a container on docker image emscripten/emsdk, and run following command on the container:
 ./emsdk install 1.38.47
![image](https://user-images.githubusercontent.com/16117787/88750332-dd313080-d187-11ea-907c-d6cac3b5ed85.png)
 ./emsdk activate 1.38.47
![image](https://user-images.githubusercontent.com/16117787/88750502-3ef19a80-d188-11ea-9d0f-255565ba8562.png)
 source ./emsdk_env.sh
![image](https://user-images.githubusercontent.com/16117787/88750577-6ba5b200-d188-11ea-9c4b-bc8a3ab12d74.png)
and I check the verison with emcc -v
![image](https://user-images.githubusercontent.com/16117787/88750662-96900600-d188-11ea-8298-209379dedec4.png)

No version info output.

**Comment by yunikoro** [comment]
Any suggestion?

**Comment by sbc100** [comment]
You need to install `python`.    Maybe just `apt-get install python` if you using a debian/ubuntu-based linux?

**Comment by yunikoro** [comment]
figure it out, Thanks! @sbc100
