### ISSUE TITLE
Setting `NODE_JS` to an array breaks closure compiler invocation

### ISSUE THREAD

**Issue by surma** [emscripten-core/emsdk#583]
I set my `.emscripten` to contain

```diff
+NODE_JS=["/root/.nvm/versions/node/v14.7.0/bin/node", "--experimental-wasm-simd"]
```

(I needed an updated Node so `autoconf` tests can successfully detect SIMD support).

However, the build process now fails with:

```
em++: error: closure compiler ("[['/root/.nvm/versions/node/v14.7.0/bin/node', '--experimental-wasm-simd'],
 '--max_old_space_size=8192', '/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler'] --ver
sion") did not execute properly!
```

Seems like arrays are not handled correctly when invoking closure compiler

**Comment by surma** [comment]
(I just realized I opened this on `emsdk` not on `emscripten`. Apologies. LMK if I should move it)

**Comment by sbc100** [comment]
Hmm.. seems to work for me:

```
EMCC_DEBUG=1 ./emcc ~/test/hello.c -O3
shared:DEBUG: successfully executed /usr/local/google/home/sbc/dev/wasm/emsdk/node/12.18.1_64bit/bin/node --experimental-wasm-simd /usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js /tmp/emscripten_temp/tmp6iu7f_6f.txt
```

From my .emscripten:

NODE_JS = [os.path.expanduser(os.getenv('NODE', '~/dev/wasm/emsdk/node/12.18.1_64bit/bin/node')), "--experimental-wasm-simd"]

**Comment by sbc100** [comment]
Do you have `EM_NODE_JS` if your environment?

**Comment by surma** [comment]
Okay your command worked for me too. I dug a bit deeper and my Makefile invokes `emcc` with `--closure 1`, which causes the error from my original post.

> Do you have EM_NODE_JS if your environment?

No.
