### ISSUE TITLE
.emscripten file can be invalid when nodejs is not installed by emsdk

### ISSUE THREAD

**Issue by reosablo** [emscripten-core/emsdk#587]
If nodejs is not installed by `emsdk`, the output ".emscripten" file by `emsdk activate` will look like this.

```python
NODE_JS = ''/usr/bin/nodejs''
# too many quotes
```

`emcc` fails to execute by this syntax error.

I think fixing [this line](https://github.com/emscripten-core/emsdk/blob/1.40.1/emsdk.py#L1450) could be a solution.

```python
activated_config['NODE_JS'] = "'%s'" % node_fallback
# the value will be quoted later again
```

**Comment by kripken** [comment]
Thanks @reosablo , I think you're right! Would you like to open a PR with that?

**Comment by reosablo** [comment]
> Thanks @reosablo , I think you're right! Would you like to open a PR with that?

OK! I'll do that.
