### ISSUE TITLE
Running emsdk.bat activate latest fails

### ISSUE THREAD

**Issue by zimmermandonny** [emscripten-core/emsdk#598]
I followed the Windows installation instructions and the successfully complete the step "emsdk.bat install latest". I get the following error when I run the next step which is "emsdk.bat activate latest".

```
c:\emsdk>emsdk.bat activate latest
Traceback (most recent call last):
  File "c:\emsdk\\emsdk.py", line 13, in <module>
    import multiprocessing
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 16, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\context.py", line 6, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\reduction.py", line 16, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by zimmermandonny** [comment]
It works if I run the command "python emsdk.py activate latest". I must have a python issue?

**Comment by sbc100** [comment]
Its looks like there is some issue using the bundled version of python that we include in the emsdk.

Do you have any python environment variables set?   Perhaps `PYTHONPATH` or `PYTHONPATH`?   

Do you know what `D:\obj\windows-release\37amd64_Release\msi_python` is?  Is that where you python installation is?

**Comment by zimmermandonny** [comment]
You are correct in that there is an issue with the python bundled with the emsdk.

I tried to run the emsdk_env.bat file and get the same original errors. If I run:

c:\emsdk>"C:\Users\Donny Zimmerman\AppData\Local\Programs\Python\Python38-32\python.exe" emsdk.py construct_env

I get the following result:

Setting environment variables:
EMSDK = C:/emsdk
EM_CONFIG = C:\emsdk\.emscripten
EM_CACHE = C:/emsdk/upstream/emscripten\cache
EMSDK_NODE = C:\emsdk\node\12.18.1_64bit\bin\node.exe
EMSDK_PYTHON = C:\emsdk\python\3.7.4-pywin32_64bit\python.exe
JAVA_HOME = C:\emsdk\java\8.152_64bit

I get the same errors when running emcc -v in the upstream/emscripten folder unless I run it with the 3.8 version of Python.

Here are my env variables that pertain to emscripten or python:

EMSCRIPTEN=C:\Users\Donny Zimmerman\emsdk\emsdk.bat
EMSDK=C:/emsdk
EMSDK_NODE=C:\emsdk\node\12.18.1_64bit\bin\node.exe
EMSDK_PYTHON=C:\emsdk\python\3.7.4-pywin32_64bit\python.exe
EM_CACHE=C:/emsdk/upstream/emscripten\cache
EM_PY=python
PYTHONHOME=C:\Users\Donny Zimmerman\AppData\Local\Programs\Python\Python38-32

Funny thing is I don't have a D: drive on my machine.

**Comment by sbc100** [comment]
So when you run `emsdk.bat` on its own all it should be doing is running `emsdk.py` with the chosen version of python.

Can you edit `emsdk.bat` and see which version is it is selecting?

It looks like its choosing the raw python but it would be good to know for sure.    Can you `echo %EMSDK_PY%` and also run `where python` just before the call on line 51?

**Comment by sbc100** [comment]
Can you try removing `PYTHONHOME` from your environment?   I think on window you do this with `set PYTHONHOME=`.

**Comment by zimmermandonny** [comment]
The line "echo %EMSDK_PY%" returns:
"c:\emsdk\python\3.7.4-pywin32_64bit\python.exe"

The line "where python" returns:
C:\emsdk\python\3.7.4-pywin32_64bit\python.exe
C:\Users\Donny Zimmerman\AppData\Local\Programs\Python\Python38-32\python.exe
C:\Users\Donny Zimmerman\AppData\Local\Microsoft\WindowsApps\python.exe

When I removed PYTHONHOME from my environment, everything works correctly, including the emsdk_env.bat call.

**Comment by sbc100** [comment]
OK great!  I think we can fix that.
