### ISSUE TITLE
Lots of undefined symbol errors when using emsdk version greater then 1.39.15

### ISSUE THREAD

**Issue by oddball** [emscripten-core/emsdk#608]
refs https://github.com/CaptorAB/quantlib-wasm/issues/3

I should possibly asked this on Stackoverflow, but risking it and asking here.

https://github.com/CaptorAB/quantlib-wasm compiles fine with earlier emsdk versions, but with greater then 1.39.15

errors like 

``` 
/bin/bash ../libtool  --tag=CXX   --mode=link /emsdk_portable/upstream/emscripten/em++  -g -O2  -L/boost/lib/emscripten -o BasketLosses/BasketLosses BasketLosses/BasketLosses.o ../ql/libQuantLib.la
libtool: link: /emsdk_portable/upstream/emscripten/em++ -g -O2 -o BasketLosses/.libs/BasketLosses BasketLosses/BasketLosses.o  -L/boost/lib/emscripten ../ql/.libs/libQuantLib.so
em++: warning: ignoring dynamic library libQuantLib.so.0.0.0 because not compiling to JS or HTML, remember to link it when compiling to JS or HTML at the end [-Wemcc]
error: undefined symbol: _ZN5boost16assertion_failedEPKcS1_S1_l (referenced by top-level compiled C/C++ code)
error: undefined symbol: _ZN8QuantLib10IntegratorC2Edm (referenced by top-level compiled C/C++ code)
error: undefined symbol: _ZN8QuantLib11EURCurrencyC1Ev (referenced by top-level compiled C/C++ code)
...
````
show up. 

Could not see that I should have changed anything in the release notes of emsdk.

Any advice?

**Comment by sbc100** [comment]
I believe this issue was addressed in #11823 which means that updating to 2.0.0 may solve your problem.

However the real solution is probably to configure your project without shared libraries.  This makes the build more likely work with emscripten where we have only emulation of shared library support. Try passing `--disable-shared` to your configure command.

**Comment by oddball** [comment]
Thanks for your reply. 

There seems to be a typo in your referenced issue, cause it is not a link, could you correct it?

I did try 
```
emscripten/emsdk:2.0.2
```
but had the described issue.

I will try to pass --disable-shared to configure, and report if it fixes the issue.

**Comment by sbc100** [comment]
Are you sure you installed `2.0.2` correctly?  (`emsdk install 2.0.2`).   It should not show the `gnoring dynamic library libQuantLib.so.0.0.0 because not compiling to JS or HTML` warning?  does it?

**Comment by oddball** [comment]
I used the docker image https://hub.docker.com/r/emscripten/emsdk/tags version 2.0.2

"emsdk --version" does not show the version, but "emsdk list" suggest to me it is running 2.0.2

```bash
docker run -it emscripten/emsdk:2.0.2 /bin/bash
root@1f4517e1dc35:/src# emsdk list

The *recommended* precompiled SDK download is 2.0.2 (ede25d889a0abe63360d4c5d420087c8753b8bbe).

To install/activate it, use one of:
         latest                  [default (llvm) backend]
         latest-fastcomp         [legacy (fastcomp) backend]

Those are equivalent to installing/activating the following:
         2.0.2             INSTALLED
         2.0.2-fastcomp

All recent (non-legacy) installable versions are:
         2.0.2    INSTALLED
```

It does however do show "ignoring dynamic library libQuantLib.so.0.0.0 because not compiling to JS or HTML"

**Comment by sbc100** [comment]
`emcc --version` will show you the version.

Did you run `emsdk activate 2.0.2`?

**Comment by oddball** [comment]
It works now. 

https://github.com/CaptorAB/quantlib-wasm/commit/ce52200e98ab215c035e0698d6added1f9e7a6e5#diff-3254677a7917c6c01f55212f86c57fbf

Unsure if I originally failed to get  emscripten/emsdk:2.0.2 or if " --disable-shared " solved it. In either case, I am happy.

Much obliged for your swift help!
