### ISSUE TITLE
Please release a new version to include the Bazel toolchain

### ISSUE THREAD

**Issue by attilaolah** [emscripten-core/emsdk#618]
Would it be possible for future versioned releases to include the `bazel` subdirectory?

Alternatively, it could be provided as a separate download, e.g. `emsdk-bazel.tar.gz`, so that we can fetch it with Bazel and reference all the goodness inside. (We can still do that via Git but using HTTP is prettier.)

**Comment by attilaolah** [comment]
Oh I just realised that the directory was only added four days ago in #603, but the latest release is five days old.

I guess then, please tag a new release :)

**Comment by kripken** [comment]
2.0.4 has just been tagged!

Good to hear this will be useful @attilaolah :smile:
