### ISSUE TITLE
sdk-upstream-master-32bit cmake error

### ISSUE THREAD

**Issue by Juanot** [emscripten-core/emsdk#623]
Everything went okay up to this point...
```
Running CMake: ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '$HOME/Apps/emsdk-master/emscripten/master/tools/optimizer']
CMake Error: The source directory "$HOME/Apps/emsdk-master/emscripten/master/tools/optimizer" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake invocation failed due to exception!
Working directory: $HOME/Apps/emsdk-master/emscripten/master_32bit_optimizer
Command '['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '$HOME/Apps/emsdk-master/emscripten/master/tools/optimizer']' returned non-zero exit status 1
Installation failed!
```

The installation seems to be missing some files.
Is this a bug?

**Comment by sbc100** [comment]
I believe this was recently fixed in https://github.com/emscripten-core/emsdk/pull/622.   Can you try updating emsdk and try again?

**Comment by Juanot** [comment]
I have updated, but I'm now getting this error:
Failed to run "npm ci" in installed Emscripten root directory /emsdk-master/emscripten/master! Please install node.js first!
Installation failed!

This despite having nodejs and npm installed.

**Comment by sbc100** [comment]
Oh that message is a little misleading.  Looking that code it doing this :

```
  node_tool = find_latest_installed_tool('node')                                 
  if not node_tool:                                                              
    print('Failed to run "npm ci" in installed Emscripten root directory ' + tool.installation_path() + '! Please install node.js first!')                        
    return False    
```

So I I guess this is due to the fact that we don't have a any 32-bit node binaries available for x86 linux... because upstream node stopped supported 32-bit x86 binaries (see https://nodejs.org/en/download/).

You could hack the script such that `find_latest_installed_tool` return `/path/to/your/node/binary`?

I'm tempted to say that we simply don't support 32-bit linux because this 1/2 support is clearly not working.

Remind me again (sorry if we have been over this already) exactly why you can't run x86 linux?    

If we do decide to drop support for 32-bit linux in emsdk it wouldn't mean you can't make emscripten work, it just means you would need to download and build your own copies of binaryen and llvm, and build them yourself, without the help of emsdk.

**Comment by sbc100** [comment]
Or perhaps you would be interesting we writing a patch to the `emscripten_npm_install` to use the system version of node on 32-bit linux?   Its seems a little nasty to add extra complexity here, but if you really it perhaps its worth it?

**Comment by Juanot** [comment]
> You could hack the script such that find_latest_installed_tool return /path/to/your/node/binary?
Okay, so do you think I could do this easily, or would I need to alter a number of scripts, as well?
Which script am I altering?

> Remind me again (sorry if we have been over this already) exactly why you can't run x86 linux?
Not sure I understand your question. Sorry.

> If we do decide to drop support for 32-bit linux in emsdk it wouldn't mean you can't make emscripten work, it just means you would need to download and build your own copies of binaryen and llvm, and build them yourself, without the help of emsdk.
I did try building llvm, but it failed at 83%.
I'm not sure if that is because I interrupted it, because it had my system stalled for hours, after building for hours.

Is there somewhere I can get an earlier version of emscripten that works with llvm 3.8, or 6.0, both of which I have on my system? 
The emscripten version I have on my system is old, and complains for llvm 3.4. 
I downloaded both llvm-3.4, and clang-3.4 with intent on installing them. Do you think I should go that route?

**Comment by sbc100** [comment]
I think the most important question is:  can you use 64-bit linux binaries here?   If not why not exactly? 

As you can tell we don't really support 32-bit linux here.

**Comment by Juanot** [comment]
I don't have a 64 bit system. However, if you gave me one, I won't refuse. :)

**Comment by sbc100** [comment]
I see :)

Are you totally sure your CPU is not 64-bit capable?  (sometime people install 32-bit linux on a 64-bit CPU for some reason).  (What does /proc/cpuinfo say?)

**Comment by Juanot** [comment]
Completely positive. It's an old system.
I already tried installing x86_64 app, to no avail, so I have proof.
However, to convince you... 16.04.1-Ubuntu... i686 i686 i686 GNU/Linux

**Comment by Juanot** [comment]
@sbc100 Thanks.
