### ISSUE TITLE
Installation breaks on Windows

### ISSUE THREAD

**Issue by donno2048** [emscripten-core/emsdk#661]
When I tried to run the command `emsdk install latest` I got this error:
```bat
Installing SDK 'sdk-releases-upstream-d8e430f9a9b6e87502f826c39e7684852f59624f-64bit'..
Installing tool 'node-12.18.1-64bit'..
Downloading: C:/Users/Elisha/Desktop/emsdk-master/zips/node-v12.18.1-win-x64.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-win-x64.zip, 57957332 Bytes
Unpacking 'C:/Users/Elisha/Desktop/emsdk-master/zips/node-v12.18.1-win-x64.zip' to 'C:/Users/Elisha/Desktop/emsdk-master/node/12.18.1_64bit'
Unzipping file 'C:/Users/Elisha/Desktop/emsdk-master/zips/node-v12.18.1-win-x64.zip' failed due to reason: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\C:\\Users\\Elisha\\Desktop\\emsdk-master\\node\\unzip_temp\\node-v12.18.1-win-x64/'
Installation failed!
```

**Comment by sbc100** [comment]
Interesting, other windows users don't seem to experience that.  What version of python are you using?   (what does `where python` say?)

**Comment by donno2048** [comment]
I'm using Python version 2.7.2

**Comment by sbc100** [comment]
Given that this doesn't happen on other windows machines I wonder if you would mind helping out with debugging.

Fir example, perhaps you could try with a more recent version of python?  also what versions of windows are you using?   Basically anything that might help is reproduce it or figure out why you in particular are experiencing this would be useful.

Looking at the code, the function in question seems to be `fix_potentially_long_windows_pathname`.  I wonder why do don't just apply this fix for long pathnames?  Regardless we need to figure out why that kind of path doesn't seem to work on your machine

**Comment by donno2048** [comment]
When I tried to do the same thing using Python 2.7.8 it worked, I guess that means that the
> python: Version 2.7.0 or above.

in the requirements should be changed to a more recent version of Python...
