### ISSUE TITLE
question: python3 not found when emsdk install

### ISSUE THREAD

**Issue by johnzhu12** [emscripten-core/emsdk#662]
![88D3BF54-BACD-4806-9577-F251D2BAB4BE](https://user-images.githubusercontent.com/11485619/100691715-3f16d680-33c4-11eb-90c4-a7ecb3f1e531.png)

johnzhudeMacBook-Pro:emsdk johnzhu$ which python
/usr/bin/python
johnzhudeMacBook-Pro:emsdk johnzhu$ which python3
/usr/local/bin/python3
johnzhudeMacBook-Pro:emsdk johnzhu$

**Comment by sbc100** [comment]
Would you mind running with `sh -x` at the beginning of the command to see that actions that shell script is taking to find that version of python?  (i.e. `./sh -x emsdk install latest`)

Maybe you have EMSDK_PYTHON set in you environment?  What does `echo $EMSDK_PYTHON` say?

**Comment by johnzhu12** [comment]
johnzhudeMacBook-Pro:emsdk johnzhu$ echo $EMSDK_PYTHON
/Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3
johnzhudeMacBook-Pro:emsdk johnzhu$ ./sh -x emsdk install latest
-bash: ./sh: No such file or directory
johnzhudeMacBook-Pro:emsdk johnzhu$ sh -x emsdk install latest
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ exec /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 emsdk.py install latest
emsdk: line 42: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3: No such file or directory
emsdk: line 42: exec: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3: cannot execute: No such file or directory
johnzhudeMacBook-Pro:emsdk johnzhu$

**Comment by johnzhu12** [comment]
johnzhudeMacBook-Pro:emsdk johnzhu$ echo $EMSDK_PYTHON
/Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3
johnzhudeMacBook-Pro:emsdk johnzhu$ ./sh -x emsdk install latest
-bash: ./sh: No such file or directory
johnzhudeMacBook-Pro:emsdk johnzhu$ sh -x emsdk install latest
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ '[' -z /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 ']'
+ exec /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3 emsdk.py install latest
emsdk: line 42: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3: No such file or directory
emsdk: line 42: exec: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/bin/python3: cannot execute: No such file or directory
johnzhudeMacBook-Pro:emsdk johnzhu$ 

@sbc100

**Comment by sbc100** [comment]
By having `EMSDK_PYTHON` in your environment you are essentially telling emsdk to use that version.

If you don't have it there you need to `unset EMSDK_PYTHON`.

**Comment by johnzhu12** [comment]
@sbc100 
 thanks,that works,but new error occurred

johnzhudeMacBook-Pro:emsdk johnzhu$ unset EMSDK_PYTHON
johnzhudeMacBook-Pro:emsdk johnzhu$ ./emsdk install latest
Installing SDK 'sdk-releases-upstream-d8e430f9a9b6e87502f826c39e7684852f59624f-64bit'..
Installing tool 'node-12.18.1-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-darwin-x64.tar.gz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
Installation failed!
johnzhudeMacBook-Pro:emsdk johnzhu$

**Comment by johnzhu12** [comment]
> johnzhudeMacBook-Pro:emsdk johnzhu$ pip install certifi
-bash: pip: command not found
johnzhudeMacBook-Pro:emsdk johnzhu$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/lib/python3.7/site-packages/certifi/cacert.pem
  CApath: none
johnzhudeMacBook-Pro:emsdk johnzhu$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/lib/python3.7/site-packages/certifi/cacert.pem
  CApath: none
johnzhudeMacBook-Pro:emsdk johnzhu$ unset EMSDK_PYTHON
johnzhudeMacBook-Pro:emsdk johnzhu$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /Users/johnzhu/Desktop/githubRepos/emsdk/python/3.7.4-2_64bit/lib/python3.7/site-packages/certifi/cacert.pem
  CApath: none
johnzhudeMacBook-Pro:emsdk johnzhu$ echo $EMSDK_PYTHON

johnzhudeMacBook-Pro:emsdk johnzhu$ 

@sbc100  **error setting certificate verify locations**,how to fix this, I need to install pip first,then `pip install certifi` to fix the other issue

**Comment by johnzhu12** [comment]
> johnzhudeMacBook-Pro:emsdk johnzhu$ 
johnzhudeMacBook-Pro:emsdk johnzhu$ pip --version
pip 20.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
johnzhudeMacBook-Pro:emsdk johnzhu$ ./emsdk install latest
Installing SDK 'sdk-releases-upstream-d8e430f9a9b6e87502f826c39e7684852f59624f-64bit'..
Installing tool 'node-12.18.1-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-darwin-x64.tar.gz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
Installation failed!
johnzhudeMacBook-Pro:emsdk johnzhu$ 

need help,I 've runned `pip install certifi`

**Comment by sbc100** [comment]
Can you confirm which version of python is bring used by emsdk?  (run it with `sh -x`)

**Comment by sbc100** [comment]
If you google for CERTIFICATE_VERIFY_FAILED and macOS should get see a bunch of sites that can help you out:

e.g.:

 https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by johnzhu12** [comment]
@sbc100  yup, python version conflicted。`brew reinstall python` fixed all ! thanks, will close this☺

**Comment by sashamc** [comment]
Hello,
the following could be helpful:
- download and install Python 3.9.2 from python.org (optionally)
- go to folder with latest Python app "/Applications/Python 3.9"
- run ./Install\ Certificates.command from that folder

my os version=10.15.7; without homebrew installed

**Comment by sashamc** [comment]
I see the same was suggested in

[https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)
