### ISSUE TITLE
Wrong clang path in Bazel toolchain

### ISSUE THREAD

**Issue by Volcomix** [emscripten-core/emsdk#699]
After upgrading my project Bazel toolchain to 2.0.13 based on [this directory](https://github.com/emscripten-core/emsdk/tree/master/bazel), I got the following error:

```
[258 / 1,769] Compiling org_tensorflow/tensorflow/lite/tools/optimize/sparsity/format_converter.cc; 11s processwrapper-sandbox ... (8 actions, 7 running)
ERROR: /root/.cache/bazel/_bazel_root/7c8212d09d20008d9ab2f5e31ef362d8/external/XNNPACK/BUILD.bazel:3512:19: undeclared inclusion(s) in rule '@XNNPACK//:wasm_ukernels':
this rule is missing dependency declarations for the following files included by 'XNNPACK/src/f32-dwconv2d-chw/gen/3x3p1-minmax-wasmsimd-arm-1x4-acc3.c':
  '/root/.cache/bazel/_bazel_root/7c8212d09d20008d9ab2f5e31ef362d8/sandbox/processwrapper-sandbox/58/execroot/__main__/external/emscripten/lib/clang/13.0.0/include/wasm_simd128.h'
Target //:tflite-simd failed to build
```

I fixed the issue in my repo by changing `clang` paths from `12.0.0` to `13.0.0`:
* https://github.com/Volcomix/virtual-background/blob/8e3c7fa732765027533f29b94328c5873be4c2ce/tflite/toolchain/crosstool.bzl#L902
* https://github.com/Volcomix/virtual-background/blob/8e3c7fa732765027533f29b94328c5873be4c2ce/tflite/toolchain/crosstool.bzl#L1048

I guess the same change should be applied here in [crosstool.bzl](https://github.com/emscripten-core/emsdk/blob/master/bazel/emscripten_toolchain/crosstool.bzl), what do you think?

Let me know if you'd like that I provide a PR.

**Comment by sbc100** [comment]
Thanks for tracking that down.  I PR would be most welcome.


@walkingeyerobot

**Comment by Volcomix** [comment]
I think the issue can be closed (sorry I forgot to use the `fixes` syntax to link the PR correctly). Thanks for your help and feedbacks.
