### ISSUE TITLE
BINARYEN_ROOT not set after building from source

### ISSUE THREAD

**Issue by sandeep-gh** [emscripten-core/emsdk#702]
I checked out the emsdk from git and build from source using ` ./emsdk install --build=Release sdk-upstream-master-64bit`. When executing ` ./emscripten/master/emcc` I get error 
```emcc: error: BINARYEN_ROOT is set to empty value in /media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/.emscripten```
Not sure if I am missing an step.

**Comment by sbc100** [comment]
I think you need to run `emsdk activate` after you run `emsdk install`

**Comment by sandeep-gh** [comment]
I tried ./emsdk activate binaryen-master-64bit and also put the `<root>/emsdk/binaryen/master_64bit_binaryen/bin` to the PATH variable. Didn't help. Setting up BINARYEN to `<root>/emsdk/binaryen/master` helped past that point.

**Comment by sbc100** [comment]
You also need to do `source ./emsdk_env.sh`  to inject the environment variables in to the current shell.
