### ISSUE TITLE
How to change the module namespace ("env") of a wasm file? 

### ISSUE THREAD

**Issue by liushuaidi** [emscripten-core/emsdk#703]
When I used emcc to compile a C program to wasm, I found that the default module namespace is "env". Can I customize it? If so, how can I modify the "env"? If not,  can I add my own namespace.

**Comment by sbc100** [comment]
There is currently no way to change the default module from which C/C++ symbol are imported.

However, for a given symbol you have use llmv "import_module" attribute to change it. e.g.:

```
__attribute__((import_module("module"), import_name("foo)))  void foo(void);
```

You have completely control over the modules that you support when you instantiate a given was module.    If you build you module with emscripten and use emscripten-generated JS to load the module then all imports will be from the "env" module by convention.

**Comment by liushuaidi** [comment]
OK, Thank you. After I compile C2wasm by using emcc/emscripten, the wasm file include the "env", which the wasm's module name/namespace. I want to chang it.

**Comment by sbc100** [comment]
As I say there is no easy way to do that.  As with any was mfile you could decompile it to text format, modify it and then re-compiler it (using was2wasm and wasm2wat tools).   I guess the more interesting questions is why do you want to to this?

**Comment by liushuaidi** [comment]
Because my company has this requirement, but I don’t have a feasible idea.The way(wasm to text, edit it, to wasm) looks good. Thank you very much.
