### ISSUE TITLE
wrong clang version when emsdk installed from source

### ISSUE THREAD

**Issue by sandeep-gh** [emscripten-core/emsdk#709]
I cloned emsdk (from emscripten-core/emsdk.git) and build the tools (include fastcomp-clang-master-64bit). When I run the test `./emcc tests/hello_world.cpp`, I get 
```clang: error: unknown argument: '-flegacy-pass-manager'```
Should I install/build latest llvm separately outside of emsdk?

**Comment by sbc100** [comment]
Fastcomp has not been supported for a long time.   If you want to build clang from source you can try `llvm-git-master-64bit`. 

Better still just install `latest` to avoid building from source at all.   Do you need to build from source for some reason?

**Comment by sandeep-gh** [comment]
I tried compiling `llvm/llvm-project` as described in [docs]( https://emscripten.org/docs/building_from_source/index.html). Also tried downloading the latest from llvm repos. Both gave same error. Compiling llvm-git-master-64bit acually worked.

**Comment by sbc100** [comment]
You should not need to compile llvm from source to use emscripten.   That should only be necessary if you want to modify llvm itself.

**Comment by sbc100** [comment]
`./emsdk install latest && ./emsdk activate latest` will give you the latest llvm version pre-built.
