### ISSUE TITLE
Is the docker image available without signing up to docker?

### ISSUE THREAD

**Issue by MarkCallow** [emscripten-core/emsdk#725]
I followed the link for the [emsdk docker image](https://hub.docker.com/u/emscripten/emsdk) given in the `docker` folder's `README.md` and I am confronted by a basically empty page that tells me to sign in or sign up to docker.com. Is there a way to get the image without having to register for docker.com?

I need to use the image in the CI to build an organization's software and having to have an account significantly increases the management burden of both setting up the CI to use the image and ensuring it continues to work in future.

Also, while I'm here, does the image contain `cmake` & `cpack`?

**Comment by MarkCallow** [comment]
To answer my own question. Yes. If you visit https://hub.docker.com/u/emscripten and click on the emsdk image it takes you to https://hub.docker.com/r/emscripten/emsdk (note the "r" not "u") which shows details of the image. You should probably change the link in `docker/README.md`. Thanks to @oddhack for setting me on the right path.

**Comment by kleisauke** [comment]
I've noticed this too, PR https://github.com/emscripten-core/emsdk/pull/934 should fix the link.
