### ISSUE TITLE
Update CMake in docker image.

### ISSUE THREAD

**Issue by MarkCallow** [emscripten-core/emsdk#726]
Please update the CMake version in the docker image. It is 3.13 which is pretty old now. Latest is 3.19.5 and 3.20 is in RC mode. I don't know if it is better way to do this is by modifying the dockerfile to install a different cmake than the one in Debian Buster or modifying it to base the image on a more recent version of Debian than Buster. I'm also not set up to build and test docker images. For those reasons I am not creating a PR.

My project needs CMake 3.15 at least but would prefer to use 3.19.

**Comment by sbc100** [comment]
We could consider choosing a different base image perhaps?    Perhaps Ubuntu Focal which was just released?

Alternatively you could use the official image is a starting point build on it by installing whatever cmake version you want, and then use that new image when you do your build?

If you would like to try the former idea feel free to upload a PR.

**Comment by MarkCallow** [comment]
I've created PR #747 to update the image to Focal. The CMake in that is 3.16.3 which is recent enough for my project. Installing an updated CMake in the existing image proved impossible.

**Comment by Taytay** [comment]
I think this issue can be closed thanks to the merging of #747
