### ISSUE TITLE
emscripten docker command doesn't work on windows

### ISSUE THREAD

**Issue by sufiblues** [emscripten-core/emsdk#737]
I am using visual studio code and trying to run a test case for emscripten on windows. I am trying to compile the helloworld.cpp program on the documentation using `docker` and whenever i run this command in powershell 
`docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) emscripten/emsdk emcc helloworld.cpp -o index.html`

I get the following error 
`id : The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:39
+ docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) emscripten/emsd ...
+                                       ~~
    + CategoryInfo          : ObjectNotFound: (id:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by sbc100** [comment]
The example command there uses the bash syntax for running subprocesses `id` and `pwd` to supply extra paramaters to the docker command.    I would not expect that exact command to under powershell. 

Its also just an example so you get the idea of how it could be used.  It expectation is that you would modify it to your needs.

If you would like to convert the command to powershell we could include a powershell example too.

**Comment by sufiblues** [comment]
Sorry if the question is too basic. I am not familiar with emscripten or docker. If you could include a powershell example that would be extremely helpful.

**Comment by sbc100** [comment]
Have you tried just installing emsdk?     Its generally easier to use, especially for windows users I imagine.   I would not advise trying to use the docker image unless you already have a pretty good grasp of the basic concepts of docker.

**Comment by sufiblues** [comment]
Thanks, I followed the instructions without using docker and it was a lot easier to get it running.

**Comment by kleisauke** [comment]
In case you want to use Docker in the future, see: https://github.com/emscripten-core/emscripten/issues/12350#issuecomment-700571741.
