### ISSUE TITLE
docker/README.md mistakenly claims an argument is necessary

### ISSUE THREAD

**Issue by MarkCallow** [emscripten-core/emsdk#748]
In its *Building Dockerfile* section, `docker/README.md` says

------
This image requires to specify following build arguments:

arg | description
-- | --
EMSCRIPTEN_VERSION | One of released version of Emscripten. For example 1.39.17 Minimal supported version is 1.39.0

------

and gives the example

```
# using docker
docker build \
    --network host \
    --build-arg=EMSCRIPTEN_VERSION=1.39.17 \
    -t emscripten/emsdk:1.39.17 \
    -f docker/Dockerfile \
    .
```

The argument appears to be optional not required. This build succeeds.

```
# using docker
docker build \
    --network host \
    -t emscripten/emsdk \
    -f docker/Dockerfile \
    .
```

Furthermore if you build in the described way, the run example will fail because when you use just `emscripten/emsdk` as the image name, as the example does, docker will report ``emscripten/emsdk:latest not found`.

I do not know the correct fix so have not attempted to create a PR.

**Comment by kleisauke** [comment]
The Docker image is built against the tip-of-tree build of Emscripten when the `EMSCRIPTEN_VERSION` build argument is not specified, see:
https://github.com/emscripten-core/emsdk/blob/1fe80678a90230bf060147164859d0d1064ef5db/docker/Dockerfile#L3

So we could rephrase that sentence to include that information. I'm not sure about that second issue, maybe the locally built image conflicts with [the image from Docker hub](https://hub.docker.com/r/emscripten/emsdk/tags)?

**Comment by MarkCallow** [comment]
> So we could rephrase that sentence to include that information.

Yes. This is what I have in mind. I just didn't know the correct phrasing. You've now explained it.

> I'm not sure about that second issue

I miswrote. What happens when I try the run example from `README.md` is that docker tells me it can't find emscripten/emsdk:latest locally and then downloads it from docker.com. This will not be an issue with suitable rephrasing of the EMSCRIPTEN_VERSION explanation.

**Comment by trzecieu** [comment]
Hello! Yes, you're right about that. I've created a small tweak proposal to the documentation.
