### ISSUE TITLE
LLVM and Binaryen binaries

### ISSUE THREAD

**Issue by Jillinger** [emscripten-core/emsdk#763]
Just a question.
I've had emscripten on my computer for a while now, but had not used it, until now.
_Please see attachment._ From there, it seems I have what I need. However, I have LLVM. and Binaryen, in a separate folder to emscripten.
I don't remember what I did (It's been four years). I just want to know if the LLVM. and Binaryen, files belong in the emscripten directory, or do I need to link them somehow, or other.
Can anyone, by looking at the file structure, help me with how I might have acquired these files (LLVM. and Binaryen), and what is the best procedure in using them together with emscripten. 
Thanks

![emsdk](https://user-images.githubusercontent.com/24792498/111524129-eb30c300-8710-11eb-9ffa-b4572c67e75f.jpg)
![emsdk1](https://user-images.githubusercontent.com/24792498/111524188-fdaafc80-8710-11eb-8572-980c47992f7b.jpg)

**Comment by sbc100** [comment]
The SDK structure has changed since 1.37.

Unless you really need that version I suggest you install `latest` instead via `emsdk install latest`.    Your best be might be to completely remove emsdk directly and start again.

To answer your specific question, no neither llvm nor binaryen need to live alongside emscripten itself.    The location of binaryen and llvm is specified to emscripten via the `.emscripten` config file (which itself normally lives in the emsdk directory).

**Comment by Jillinger** [comment]
> The SDK structure has changed since 1.37.
> 
> Unless you really need that version I suggest you install `latest` instead via `emsdk install latest`. Your best be might be to completely remove emsdk directly and start again.
> 
> To answer your specific question, no neither llvm nor binaryen need to live alongside emscripten itself. The location of binaryen and llvm is specified to emscripten via the `.emscripten` config file (which itself normally lives in the emsdk directory).

Thank you.

**Comment by Jillinger** [comment]
@sbc100 just a quick question.
I have started from scratch and installed the latest. Would you recommend I install clang and llvm in this environment? I already have llvm with clang on my system.

**Comment by sbc100** [comment]
Emscripten depends on the latest tip of tree version of llvm/clang.   Specifically when you install a given release of emscripten it include clang.   `emsdk install lastest` takes care of this for you.

**Comment by Jillinger** [comment]
Oh. I see.
