### ISSUE TITLE
Error downloading URL

### ISSUE THREAD

**Issue by Jillinger** [emscripten-core/emsdk#764]
Trying to install a specific tool, I got this error : 
```
Fetching all tags from Emscripten Github repository...
Done. 215 tagged releases available, latest is 2.0.15.
Fetching all tags from Binaryen Github repository...
Done. 90 tagged Binaryen releases available, latest is 1.39.1.
Fetching all precompiled Nightly versions..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/win_32bit/index.txt': HTTP Error 403: Forbidden
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/win_64bit/index.txt': HTTP Error 403: Forbidden
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten/nightly/win/index.txt': HTTP Error 403: Forbidden
Fetching all precompiled tagged releases..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_32bit/index.txt': HTTP Error 403: Forbidden
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt': HTTP Error 403: Forbidden
Installing SDK 'sdk-tag-1.38.20-64bit'..
Installing tool 'clang-tag-e1.38.20-64bit'..
Error downloading URL 'https://github.com/kripken/emscripten-fastcomp/archive/1.38.20.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Installation failed!
```
I googled the error, and I found [this recommendation](https://github.com/emscripten-core/emsdk/commit/4c8ea1b10be7ab59ec0bb5a63934372cb4c2bcff) given as the solution, since the problem seems to be with python 2.7.5.3
After editing my files I now get this : 
```
Fetching all tags from Emscripten Github repository...
Done. 215 tagged releases available, latest is 2.0.15.
. . . Same as previous . . .
Error: No tool or SDK found by name 'sdk-tag-1.38.20-64bit'.
```
The reason the matching tool or SDK was not found, is because no 64bit tools are available, whereas previously they were.

I'm now getting other errors about not finding clang, so I'm going to do a system restore, and come back here.
However, since the solution I tried, did not work out, is there another suggestion to correct the previous error?

``Error downloading URL 'https://github.com/kripken/emscripten-fastcomp/archive/1.38.20.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL `routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>`

I was able to manually download the file from the link https://github.com/kripken/emscripten-fastcomp/archive/1.38.20.zip. Why does it fail to do so from the command?

**Comment by sbc100** [comment]
This first thing I notice is that "Fetching all tags from Emscripten" is message the emsdk hasn't output in a long time.  I think it was removed back in #262.    I would recommand first updating emsdk to that latest version.  hopefully these issues will be fixed by that.

Failing that you could follow the advice given to other folks who have issues with python and SLL on macOS: 
 https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify/57614113#57614113

**Comment by Jillinger** [comment]
Thanks. I'll probably try one of those suggestions if my plan fails.
I just came across the explanation to the problem, it looks like.
https://emscripten.org/docs/getting_started/downloads.html

```
Platform-specific notes
Windows
Install Python 3.6 or newer (older versions may not work due to a GitHub change with SSL).
```

So I 'm going to try python 3.8, and see if that works.
That page also linked to a [workaround](https://github.com/emscripten-core/emscripten/issues/6275), so I have another option.
If all fails. . . Well it doesn't appear I can update, but I'll take another look at that.
Regards

**Comment by Jillinger** [comment]
Okay, so I edited emsdk to use python 3.8, but it returned an error and did not work. So I edited it to use 2.7.13 and used the workaround, placing the emscripten zip file in the zips folder, and that worked.
```
Done installing tool 'emscripten-tag-1.38.20-64bit'.
Done installing SDK 'sdk-tag-1.38.20-64bit'.
```

However, when I try to activate a tool, I am getting this error : 
```
Failed to read environment variable PATH:
No module named win32api
Traceback (most recent call last):
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 2255, in <module>
    sys.exit(main())
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 2194, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate
=permanently_activate)
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 1768, in set_active_tool
s
    env_string = construct_env(tools_to_activate, False)
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 1848, in construct_env
    newpath, added_path = adjusted_path(tools_to_activate)
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 1818, in adjusted_path
    existing_path = win_get_environment_variable('PATH', system=True)
  File "E:\PATH_DIR\emsdk-64bit-installed\\emsdk", line 210, in win_get_environm
ent_variable
    win32api.RegCloseKey(folder)
UnboundLocalError: local variable 'win32api' referenced before assignment
```

The win32api file exists in two places on my system...
```
E:\PATH_DIR\emsdk-64bit-installed\python\3.9.1.0_64bit\Lib\site-packages\win32ctypes
E:\PATH_DIR\emsdk-64bit-installed\python\3.9.1.0_64bit\Lib\site-packages\win32ctypes\pywin32
```

What is the cause of the error, and how might I correct it?

**Comment by Jillinger** [comment]
I went ahead and installed the latest emsdk - https://github.com/emscripten-core/emsdk and it's working fine. It's possible it can download and install the earlier tool I was looking for, because I was able to install a tool that was not available, by using the workaround, after a failed install.
```
Installing tool 'emscripten-1.38.30'..
Error: Downloading URL 'https://github.com/emscripten-core/emscripten/archive/1.38.30.zip': 
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Installation failed!
```
```
Installing SDK 'sdk-fastcomp-1.38.30-64bit'..
Skipped installing fastcomp-clang-e1.38.30-64bit, already installed.
Skipped installing node-8.9.1-64bit, already installed.
Skipped installing python-2.7.13.1-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Installing tool 'emscripten-1.38.30'..
Downloading: C:/emsdk/zips/1.38.30.zip from https://github.com/emscripten-core/emscripten/archive/1.38.30.zip
Unpacking 'C:/emsdk/zips/1.38.30.zip' to 'C:/emsdk/emscripten/1.38.30'
Done installing tool 'emscripten-1.38.30'.
Done installing SDK 'sdk-fastcomp-1.38.30-64bit'.
```
So this is good.
Just a thought though. Why are they still using node 8, when it has been declared insecure and strongly recommended to remove and update to later versions, due to vulnerabilities?

**Comment by sbc100** [comment]
node 8 is selected because you are installing a old version of the SDK (1.38.30).

If you install a recent version (`latest` or `2.0.15` for example) you will see it used node 14.15.5.   You will also get the new upstream clang compiler and host of other benefits.

**Comment by Jillinger** [comment]
I'll follow your recommendation. Thanks

**Comment by Jillinger** [comment]
@sbc100 
I reopened this because after following your recommendation, I still get the same problem.
Python crashes, when I try to permanently register this environment.

```
Adding directories to PATH:
PATH += C:\emsdk
PATH += C:\emsdk\node\14.15.5_64bit\bin
PATH += C:\emsdk\upstream\emscripten

Setting environment variables:
PATH = C:\emsdk;C:\emsdk\node\14.15.5_64bit\bin;C:\emsdk\upstream\emscripten;
...
EMSDK = C:/emsdk
EM_CONFIG = C:\emsdk\.emscripten
EMSDK_NODE = C:\emsdk\node\14.15.5_64bit\bin\node.exe
EMSDK_PYTHON = C:\emsdk\python\3.9.2-1_64bit\python.exe
EM_CACHE = C:/emsdk/upstream/emscripten\cache
The changes made to environment variables only apply to the currently running shell instance. 
Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently 
register this environment permanently, rerun this command with the option --permanent.

```
C:\emsdk>emsdk activate latest --permanent
![python-crash](https://user-images.githubusercontent.com/24792498/112708669-31e89080-8e68-11eb-807a-fb4e22b8cb93.jpg)

**Comment by Jillinger** [comment]
I just decided to manually set my environment.
I achieved what I wanted. UE4 successful generated the project.
