### ISSUE TITLE
Duplicates Being Added to Path from two SDKs?

### ISSUE THREAD

**Issue by Jillinger** [emscripten-core/emsdk#768]
Having what appears to be issues with path environment and directories added to PATH  by emsdk.
I am about to permanently add emscripten to user environment.

The results look like this... (A)
```
Adding directories to PATH:
PATH += C:\emsdk\fastcomp-clang\e1.38.30_64bit

Setting environment variables:
PATH = C:\emsdk\fastcomp-clang\e1.38.30_64bit;C:\emsdk;C:\emsdk\emscripten\1.38.30;
E:\PATH_DIR\emsdk-64bit-installed;E:\PATH_DIR\emsdk-64bit-installed\clang\e1.37.22_64bit;
E:\PATH_DIR\emsdk-64bit-installed\node\4.1.1_64bit\bin;E:\PATH_DIR\emsdk-64bit-installed\python\2.7.5.3_64bit;
E:\PATH_DIR\emsdk-64bit-installed\java\7.45_64bit\bin;E:\PATH_DIR\emsdk-64bit-installed\emscripten\1.37.22;
C:\Python27\;C:\Python27\Scripts;E:/PATH_DIR/emsdk-64bit-installed/java/7.45_64bit\bin;
```

(1) The directory 'E:\PATH_DIR\emsdk-64bit-installed' (which has not permanently been added to PATH) is from a previous SDK, which I no longer want to use, as I will be using the 'C:\emsdk' directory.
I **don't** want it to be the case that while permanently setting the path 'C:\emsdk', the 'E:\PATH_DIR\emsdk-64bit-installed' path be set also.
Do I have to reboot my computer, in order to completely remove the 'E:\PATH_DIR\emsdk-64bit-installed' path. I have closed and reopened the shell.

(2) Previously, when I activated emscripten, the result was this... (B)
```
EMSDK = C:/emsdk
EM_CONFIG = C:\emsdk\.emscripten
EM_CACHE = C:/emsdk/emscripten/1.38.30\cache
EMSCRIPTEN = C:\emsdk\emscripten\1.38.30
```
...which looks like the common setup I saw on Linux system.

However, when I activated emscripten another time, the EMSCRIPTEN variable is not evident, but the result is, as shown above (A).
Will the variable EMSCRIPTEN always be given a vale to emscripten's path, or will it be added to PATH - C:\emsdk;C:\emsdk\emscripten\1.38.30?

Does it need to be added to PATH, or would the variable EMSCRIPTEN=path-to-emscripten suffice?

**Comment by sbc100** [comment]
The idea is that we at the emscripten directory to the PATH.   This is how most users find emscripten.

`EMSCRIPTEN` is also added the environment for historical reasons and some folks rely on this I believe.

When you activate the sdk it will only print things that it is added to the environment... so most likely `EMSCRIPTEN` is already set in your environment.

Are using the very latest version of emsdk from github? 

Do you really want be using that very old version of emscripten and the old fastcomp compiler?  

When modifying the PATH environment variable emsdk will try to remove old emsdk directories from the path before adding new ones, but if you have two different emsdk installations is won't recognize the old ones and you might need to manually remove them from your PATH.

**Comment by Jillinger** [comment]
Yes. I did manually remove those paths after I realized they were actually there. I made the mistake of thinking they were not physically there because while I though I was looking at the values in the user environment path, It was the system path. So, my mistake. Sorry.

Yes, I am using the latest emsdk from the github page.
Why have I opted to use an old tool? Let me explain.
The reason I got back to emscripten, after so long, is because I have now gotten back to building UE4, after putting it on hold, due to uncontrolled events.

I tried using the latest UE4s, but my graphics card is not up to par, so I am forced to build below 4.23. I know 4.19 works, but I wanted to see how high I could get for certain plugins.
While building UE4, everything was working fine, since my emscripten environment was perfect (Arrrrghhhh). Until I  got this...

> Setting up Unreal Engine 4 project files...
> EMSDK enviroment variable is set to point to E:/PATH_DIR/emsdk-64bit-installed but needed tools were not found:
> EMSCRIPTEN_ROOT: E:\PATH_DIR\emsdk-64bit-installed\emscripten\1.37.22, exists: True
> LLVM_ROOT: E:/PATH_DIR/emsdk-64bit-installed\Win64\clang\e**1.38.20**_64bit, exists: **False**
> NODE_JS: E:/PATH_DIR/emsdk-64bit-installed\Win64\node\8.9.1_64bit\bin\node.exe,exists: False
> PYTHON: E:/PATH_DIR/emsdk-64bit-installed\Win64\python\2.7.13.1_64bit\python.exe, exists: False
> *** NODE_JS NOT FOUND: E:/PATH_DIR/emsdk-64bit
> installed\Win64\node\8.9.1_64bit\bin\node.exe
> *** LLVMROOT directory **NOT FOUND**: E:/PATH_DIR/emsdk-64bit-installed\Win64\clang\e**1.38.20**_64bit
> *** PYTHON NOT FOUND: E:/PATH_DIR/emsdk-64bit-installed\Win64\python\2.7.13.1_64bit\python.exe
> EMSDK enviroment variable is set to point to E:/PATH_DIR/emsdk-64bit-installed but needed tools were not found:
> EMSCRIPTEN_ROOT: E:\PATH_DIR\emsdk-64bit-installed\emscripten\1.37.22, exists: True
> LLVM_ROOT: E:/PATH_DIR/emsdk-64bit-installed\Win64\clang\e**1.38.20**_64bit, exists: **False**
> NODE_JS: E:/PATH_DIR/emsdk-64bit-installed\Win64\node\8.9.1_64bit\bin\node.exe,exists: False
> PYTHON: E:/PATH_DIR/emsdk-64bit-installed\Win64\python\2.7.13.1_64bit\python.exe, exists: False
> *** NODE_JS NOT FOUND: E:/PATH_DIR/emsdk-64bit-installed\Win64\node\8.9.1_64bit\bin\node.exe
> *** LLVMROOT directory NOT FOUND: E:/PATH_DIR/emsdk-64bit-installed\Win64\clang\e1.38.20_64bit
> *** PYTHON NOT FOUND: E:/PATH_DIR/emsdk-64bit-installed\Win64\python\2.7.13.1_64bit\python.exe
> Binding IntelliSense data... 100%
> Writing project files... 100%

That's when I set out to find 1.37.22. Not realizing it wouldn't be so easy (forgetting how quickly things in the computer world keep updating and evolving).
That's where my problems deepened. I probably should have dropped back a notch with the UE4 version.
Anyway, what's done, is done.
I didn't want to go with the latest emscripten, because I figured it might be too new for an older UE4.
However, you might be able to convince me that it's just what I need for any version of UE4. :)

In the meantime, I have another issue for you. Python crashes every time I try to activate fastcomp-clang-e1.38.30-64bit. 
Why might that happen?
