### ISSUE TITLE
emsdk install failed: No tool or SDK found

### ISSUE THREAD

**Issue by justin-himself** [emscripten-core/emsdk#769]
I'm current using MacOS Bigsur Arm.  
I cloned the repo first,

```bash
$ git clone https://github.com/emscripten-core/emsdk.git
$ cd emsdk
```

And I want to install version 1.39.8 for Qt 5.15, so I run the command below, but got an error.

```bash
$ ./emsdk install 1.39.8
Error: No tool or SDK found by name 'sdk-releases-upstream-9e60f34accb4627d7358223862a7e74291886ab6-64bit'.
```

So I tried to install the latest version, but still not working

```bash
$ ./emsdk install latest
Error: No tool or SDK found by name 'sdk-releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit'.
```

It's highly possible that I misunderstood something, but I can't know. Please help me   😰

**Comment by kripken** [comment]
Maybe there are local changes? A fresh checkout of the emsdk to a fresh directory should work with those commands (I just verified - even the old 1.39.8 version works).

**Comment by sbc100** [comment]
The problem is the M1 CPU.   See #671 for the progress there.

**Comment by alvas** [comment]
Resolving SDK alias 'latest' to '2.0.34'
Resolving SDK version '2.0.34' to 'sdk-releases-upstream-d8fc1b92dbc0ce8d740a7adb937c5137ba4755e0-64bit'
error: tool or SDK not found: 'sdk-releases-upstream-d8fc1b92dbc0ce8d740a7adb937c5137ba4755e0-64bit'
