### ISSUE TITLE
emmake failing due to internal method missing

### ISSUE THREAD

**Issue by sakuntalle** [emscripten-core/emsdk#780]
Hey!

I'm working on Windows and when running the emmake make command I get the following output
```
emmake make -v
Traceback (most recent call last):
  File "D:\Work\EmscriptenSDK_Windows\upstream\emscripten\emmake.py", line 70, in <module>
    sys.exit(run())
  File "D:\Work\EmscriptenSDK_Windows\upstream\emscripten\emmake.py", line 51, in run
    mingw32_make = building.which('mingw32-make')
AttributeError: module 'tools.building' has no attribute 'which'
```
I've installed Emscripten using the latest param and my emcc version is 
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.16 (52ed04f424ff0db7d8085c35df3afd7f7b1c9eb7)`

Indeed, when I have a look at the *building.py* script there is no *which* method.
I've fixed this issue by changing the code in the emmake.py on line 51 to 
```
utils.which('mingw32-make')
```
But obviously I can't maintain it like this.
Thanks!

**Comment by sakuntalle** [comment]
Hi @sbc100! 
How can I get this merge on my side through the emsdk command? Would latest grab it?

**Comment by sbc100** [comment]
You can use `emsdk install tot` to get a tip of tree build until that change makes it into an official release.

**Comment by sakuntalle** [comment]
Cheers!
