### ISSUE TITLE
Can't install emsdk 2.0.16

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emsdk#781]
Hi, I just wanted to update from emsdk 2.0.1. to 2.0.16. on Win10 with

```
emsdk install 2.0.16
Error: No tool or SDK found by name '2.0.16'.
```

With
`emsdk install latest`

I get only the 2.0.15. version.

What I'm doing wrong? Thks...

**Comment by kripken** [comment]
Did you do `git pull` before?

**Comment by PowerNow** [comment]
No, I don't have GitHub installed. Do I have to reinstall emscripten 2.0.16 before and then use
`emsdk install latest`
I'm wondering because the last time I think I updated without reinstalling the newest version...

**Comment by kripken** [comment]
Oh, if you installed without git then you can do `emsdk update`.

**Comment by PowerNow** [comment]
Thank you very much! I forgot it...

**./emsdk update**
./emsdk install latest
./emsdk activate latest

# Activate PATH and other environment variables in the current terminal
source ./emsdk_env.sh
