### ISSUE TITLE
is not a function

### ISSUE THREAD

**Issue by Crusoekid** [emscripten-core/emsdk#784]
my test.js code
```
function loadWebAssembly (path, imports = {}) {
    return fetch(path)
      .then(response => response.arrayBuffer())
      .then(buffer => WebAssembly.compile(buffer))
      .then(module => {
        imports.env = imports.env || {}
  
        // 开辟内存空间
        imports.env.memoryBase = imports.env.memoryBase || 0
        if (!imports.env.memory) {
          imports.env.memory = new WebAssembly.Memory({ initial: 256 })
        }
  
        // 创建变量映射表
        imports.env.tableBase = imports.env.tableBase || 0
        if (!imports.env.table) {
          // 在 MVP 版本中 element 只能是 "anyfunc"
          imports.env.table = new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
        }
  
        // 创建 WebAssembly 实例
        return WebAssembly.instantiate(module, imports)
      })
  }

let func;
loadWebAssembly('./helloworld.wasm')
  .then(instance => {
    func = instance.exports.add;
    console.log('Function =', func());
  })
```

my hello.cpp code
```
#include <iostream>

extern "C"
{
	int add()
	{
		std::cout << "Hello, World" << std::endl;
		return 10;
	}
}
```

my html 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script src="test.js"></script>
  </body>
  </body>
</html>
```

i use commond 'emcc -Os hello.cpp -o helloworld.js -s WASM=1' to compile.But show me ```Uncaught (in promise) TypeError: func is not a function``` please ,what`s wrong.thanks!!
as well, i use -O0,-O1,-O2,O3show me different wrong.waooo

**Comment by sbc100** [comment]
Normally the JS code for loading the webassembly file will be generated by emscripten.  What you are doing is possible, but requires a lot more work.   Just FYI.

First thing I would do is debug what `instance.exports.add` actually is if its not a function.   You can just send `instance.exports.add` to console to log or attach the debugger to find out.   You can also try logging `instance.exports` to find out what exports you do have.

Have did you compile you module exactly?  Did you build with `EXPORTED_FUNCTIONS=[add]`?   You need to either build with EXPORTED_FUNCTIONS or attach EMSCRIPTEN_KEEPALIVE to the function declaration in order to export it.

**Comment by Crusoekid** [comment]
if i use ```emcc -O3 hello.cpp -o helloworld.js -s WASM=1 -s EXPORTED_FUNCTIONS='["_add"]'``` to build .it show me ```Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function``` error!

my commond wrong?

**Comment by Crusoekid** [comment]
i show instance is a ```Promise {<fulfilled>: Instance}```, but instance.exports show me ```undefined```

**Comment by sbc100** [comment]
Does it work if you load via `helloworld.js` rather than your own custom loading code (loadWebAssembly) ?

**Comment by Crusoekid** [comment]
Yes, i use ```EMSCRIPTEN_KEEPALIVE``` to keep and load ```helloworld.js``` and ```helloworld.wasm ``` .
but show warning ```wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.``` , is this warning not important?
so every code i must load js and wasm both?

**Comment by Crusoekid** [comment]
i just code in html , but now my html code is 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script src="helloworld.js"></script>
    <script src="test.js"></script>
  </body>
  </body>
</html>
```

and test.js
```
let func;
func = loadWebAssembly('./helloworld.wasm')
```

show me ```Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function```, what`s wrong?

**Comment by sbc100** [comment]
You don't need the `loadWebAssembly` function.   helloworld.js should do all that for you already.    You should just be able call `Module.onRuntimeInitialized(func)`.. and then from `func` you can call `Module.add`.

**Comment by sbc100** [comment]
To fix the mime type issue you need to run a webserver that serves wasm files with the correct mime type.  `emrun` will do this for example.

**Comment by Crusoekid** [comment]
i use 
```
function init() {
    console.log("init over");
}
function run() {
    Module._add();
}
var Module = {
    onRuntimeInitialized:[
        init
    ],
    preRun: [
    ],
    postRun: [run]
}
```
but ```Uncaught (in promise) TypeError: Module._add is not a function```

**Comment by sbc100** [comment]
Can you see if `Module._add` exists at all at the time?  (can you inspect the Module object in the debugger?)

I would call your `run` function from `onRuntimeInitialized` if I were you, unless you have a `main` function in your code and you want to wait for it to be done (that is what `postRun` is for).

Also I think `onRuntimeInitialized` needs to be single function.   So `onRuntimeInitialized: init`

**Comment by Crusoekid** [comment]
but i call add fuction in html is ok,
```
<script>
        Module = {}
        Module.onRuntimeInitialized = function() {
            Module._add();
        }
    </script>
```

but in js is not correct.
```
function run() {
    Module._add();
}
var Module = {
    onRuntimeInitialized:[
        run
    ]
}
```

**Comment by sbc100** [comment]
You would need to make sure that JS code comes before helloworld.js.

**Comment by Crusoekid** [comment]
i change the JS code before helloworld.js, but ```Uncaught (in promise) TypeError: Module.onRuntimeInitialized is not a function```..

**Comment by Crusoekid** [comment]
<body>
    <script src="test.js"></script>
    <script src="helloworld.js"></script>
  </body>

**Comment by sbc100** [comment]
```
var Module = {
    onRuntimeInitialized: run
}
```

(onRuntimeInitialized is expected to be function, not an array)

**Comment by Crusoekid** [comment]
very THX!! it work!!

**Comment by Crusoekid** [comment]
hey， man.
i use cmakelists.txt to build js and wasm.```emcmake cmake .. && emmake make``` 
```
cmake_minimum_required(VERSION 3.10)

project(CTest)
set (EMCC_LINKER_FLAGS "-s WASM=1 -O3")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fdata-sections -fPIE -fstrict-aliasing -ffunction-sections -ffast-math -flax-vector-conversions -O3 -Wall -fsigned-char -fno-stack-protector -fopenmp -g")

include_directories(${CMAKE_CURRENT_LIST_DIR}/src)
file(GLOB srcpp src/*.cpp)

add_executable(CTest ${srcpp})
```
but show ```Uncaught (in promise) RuntimeError: abort(TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function) at Error```.cmakelists.txt need anything else?

**Comment by Crusoekid** [comment]
i fixed my cmakelists.txt but also show me not a func.
```
cmake_minimum_required(VERSION 3.10)

project(CTest)
set( CMAKE_CXX_STANDARD 11 )
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif(NOT CMAKE_BUILD_TYPE)


include_directories(${CMAKE_CURRENT_LIST_DIR}/src)
include_directories(${CMAKE_CURRENT_LIST_DIR}/include)
file(GLOB srcpp src/*.cpp)

add_executable(CTest ${srcpp})
set_target_properties( CTest PROPERTIES LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} --bind" )

set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s WASM=1")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -std=c++1z -O3 --llvm-lto 1")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ASSERTIONS=2")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} --memory-init-file 0 -s TOTAL_MEMORY=134217728 -s ALLOW_MEMORY_GROWTH=1")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} --bind")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s ENVIRONMENT=web")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s MODULARIZE")
set(EMSCRIPTEN_LINK_FLAGS "${EMSCRIPTEN_LINK_FLAGS} -s EXPORT_ES6")
```

```
#include <emscripten/bind.h>
#include "emscripten.h"

using namespace emscripten;

float lerp(float a, float b, float t) {
    return (1 - t) * a + t * b;
}

EMSCRIPTEN_BINDINGS(my_module) {
    function("lerp", &lerp);
}
```
