### ISSUE TITLE
wasm-ld: error: Target feature 'atomics

### ISSUE THREAD

**Issue by Crusoekid** [emscripten-core/emsdk#787]
```
wasm-ld: error: Target feature 'atomics' used in detectBase.cpp.o is disallowed by alloc.cpp.o. Use --no-check-features to suppress.
```
 should i use ```-Wl,--shared-memory,--no-check-features``` to fixed my error??

but i use this show me ```error: undefined symbol: _ZNK3OAL6Tensor16getDimensionTypeEv (referenced by top-level compiled C/C++ code```

my project has ```a.a``` ,and ```b.a``` import ```a.a``` ,then my project import ```b.a``` some function to code .cpp.Do I should export ```a.a``` and ```b.a``` functions??

**Comment by sbc100** [comment]
The error meas that at least one of your object files was build with `-pthread` (detectBase.cpp.o) but another object file (alloc.cpp.o) was not build with that flag.

You should take a look at the commands line used to build those two object files and make them agree (either both using `-pthread` or neither).

The missing symbol error demangles to `OAL::Tensor::getDimensionType() const`  .. which object file is supposed to contain that symbol?   Can you verify that that object file exists in one you libraries and that it contains that specific symbols (you can use `llvm-nm` on object files and archives to list symbols).

**Comment by Crusoekid** [comment]
yes! is in my ```a.a```, should i export this function??

**Comment by Crusoekid** [comment]
Can i nodejs code call cpp code , and cpp code return a struct or  a float array?
