### ISSUE TITLE
wasm-ld: error: --shared-memory is disallowed by pointer.cc.o because it was not compiled with 'atomics' or 'bulk-memory' features.

### ISSUE THREAD

**Issue by engineer1109** [emscripten-core/emsdk#790]
When add flag:
-Os -s WASM=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8 -s USE_WEBGL2=1 -s USE_GLFW=3 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s INITIAL_MEMORY=2147418112 -s MAXIMUM_MEMORY=4GB --bind --preload-file ${PROJECT_SOURCE_DIR}/data@/data

It causes ld error:
wasm-ld: error: --shared-memory is disallowed by pointer.cc.o because it was not compiled with 'atomics' or 'bulk-memory' features.

It is caused by "-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8".

**Comment by sbc100** [comment]
If you want to use `-s USE_PTHREADS` you need to compiler all your object files with this flag too (or `-pthread` which is equivalent).    In this case it looks like you didn't use this flag when you compiled `pointer.cc`

**Comment by oregu1** [comment]
> If you want to use `-s USE_PTHREADS` you need to compiler all your object files with this flag too (or `-pthread` which is equivalent). In this case it looks like you didn't use this flag when you compiled `pointer.cc`

Ok. And how to do that? I have the same issue. Spent several days to figure it out how to do that. Still no success. 
Can you help me?(

**Comment by sbc100** [comment]
@oregu1 can you show the full failing link command?  (not just the error from wasm-ld).   If you are using `ninja` it should just show up in the output.  If you using `make` you may need to add `VERBOSE=1` to the make command otherwise it hides the command lines.

Also, what version of emscripten are you using?
