### ISSUE TITLE
google-closure-compiler-linux version not properly pinned when installing Emscripten

### ISSUE THREAD

**Issue by akien-mga** [emscripten-core/emsdk#802]
Since yesterday we're getting CI build issues for Godot ([example](https://github.com/akien-mga/godot/runs/2455400498?check_suite_focus=true)) due to an incompatibility between the old Emscripten version we use on CI (`1.39.20`, context below) and the apparently unbounded version of [google-closure-compiler-linux](https://www.npmjs.com/package/google-closure-compiler-linux) (which was updated yesterday on npm, probably introducing this compatibility breakage).

Here's the error we get:
```
/home/akien/Projects/godot/emscripten/emsdk/node/14.15.5_64bit/bin/node /home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --externs /home/akien/Projects/godot/godot-3.x/platform/javascript/js/engine/engine.externs.js --js /home/akien/Projects/godot/godot-3.x/platform/javascript/js/engine/preloader.js --js /home/akien/Projects/godot/godot-3.x/platform/javascript/js/engine/config.js --js /home/akien/Projects/godot/godot-3.x/platform/javascript/js/engine/engine.js --js_output_file /home/akien/Projects/godot/godot-3.x/bin/godot.javascript.opt.engine.js
Building compilation database compile_commands.json
progress_finish(["progress_finish"], [])
Linking Program        ==> bin/godot.javascript.opt.js
building:ERROR: Closure compiler run failed:

building:ERROR: /home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:80:4: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable MemoryDescriptor declared more than once. First occurrence: externs.zip//webassembly.js
  80| var MemoryDescriptor;
          ^^^^^^^^^^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:87:4: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable TableDescriptor declared more than once. First occurrence: externs.zip//webassembly.js
  87| var TableDescriptor;
          ^^^^^^^^^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:287:4: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable BigInt declared more than once. First occurrence: externs.zip//es3.js
  287| var BigInt;
           ^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:293:9: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable Worklet declared more than once. First occurrence: externs.zip//w3c_worklets.js
  293| function Worklet() {}
                ^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:306:9: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable AudioWorklet declared more than once. First occurrence: externs.zip//w3c_audio.js
  306| function AudioWorklet() {}
                ^^^^^^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:315:9: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable AudioWorkletProcessor declared more than once. First occurrence: externs.zip//w3c_audio.js
  315| function AudioWorkletProcessor() {}
                ^^^^^^^^^^^^^^^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:324:9: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable AudioWorkletNodeOptions declared more than once. First occurrence: externs.zip//w3c_audio.js
  324| function AudioWorkletNodeOptions() {}
                ^^^^^^^^^^^^^^^^^^^^^^^

/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js:344:9: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable AudioWorkletNode declared more than once. First occurrence: externs.zip//w3c_audio.js
  344| function AudioWorkletNode(context, name, options) {}
                ^^^^^^^^^^^^^^^^

8 error(s), 0 warning(s)

em++: error: closure compiler failed (rc: 8. the error message may be clearer with -g1 and EMCC_DEBUG=2 set)
```

**Steps to reproduce:**
- Install Emscripten 1.39.20 today on Linux, see it pull `google-closure-compiler-linux` version `20210406.0.0`
- Clone https://github.com/godotengine/godot, checkout branch `3.x`
- Build with `scons p=javascript tools=no target=release use_closure_compiler=yes`

The problem seems to be that `upstream/emscripten/package-lock.json` doesn't properly lock `google-closure-compiler-linux` to a version that matches Emscripten at the time of release, or that matches `google-closure-compiler` itself.

Relevant part of `upstream/emscripten/package-lock.json` after installing Emscripten 1.39.20 with current emsdk:
```
    "google-closure-compiler": {
      "version": "20200224.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler/-/google-closure-compiler-20200224.0.0.tgz",
      "integrity": "sha512-V81dRYygdHbZtOtU16VX26xAdJBB1UZyfSg3OTzdNl3l/xEIx1D/L7TYUqjeTXsxcy+JruJ/UfUlIJAOaMRTog==",
      "requires": {
        "chalk": "2.x",
        "google-closure-compiler-java": "^20200224.0.0",
        "google-closure-compiler-js": "^20200224.0.0",
        "google-closure-compiler-linux": "^20200224.0.0",
        "google-closure-compiler-osx": "^20200224.0.0",
        "google-closure-compiler-windows": "^20200224.0.0",
        "minimist": "1.x",
        "vinyl": "2.x",
        "vinyl-sourcemaps-apply": "^0.2.0"
      },
      "dependencies": {
        "google-closure-compiler-linux": {
          "version": "20200224.0.0",
          "resolved": "https://registry.npmjs.org/google-closure-compiler-linux/-/google-closure-compiler-linux-20200224.0.0.tgz",
          "integrity": "sha512-/BaE889EPrXWOKJVolA9++e99xBDMzeFBf7zF7nBB8PUmU5DlvtsoLL82xnT6nbZC1ktHaETlVx+vYGju8zKBQ==",
          "optional": true
        }
      }
    },
    "google-closure-compiler-java": {
      "version": "20200224.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler-java/-/google-closure-compiler-java-20200224.0.0.tgz",
      "integrity": "sha512-palFcDoScauZjWIsGDzMK6h+IctcRb55I3wJX8Ko/DTSz72xwadRdKm0lGt8OoYL7SKEO+IjgD7s8XrAGpLnlQ=="
    },
    "google-closure-compiler-js": {
      "version": "20200224.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler-js/-/google-closure-compiler-js-20200224.0.0.tgz",
      "integrity": "sha512-70VKN0kbnTRtu2dqxDjWZQGfEQIHj7b7oUUCsYPO5oEXCDfgxNc13oYUJXvrTONLRWlHCNl/I8FNrVOwZ3gY/g=="
    },
    "google-closure-compiler-linux": {
      "version": "20210406.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler-linux/-/google-closure-compiler-linux-20210406.0.0.tgz",
      "integrity": "sha512-KzE39AD3OOZMkR1TtE3nwPBhB3eEJwH8w4Jm3vx2k4veFhryWASFAnDMfHcASzlzjk05tPjecuFtGrHhVafL+w=="
    },
    "google-closure-compiler-osx": {
      "version": "20200224.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler-osx/-/google-closure-compiler-osx-20200224.0.0.tgz",
      "integrity": "sha512-WXVNW9nPUqjvCe38mUIlBGEPVPCTKLtdaXC+q+kQdonkJFHNrpdyYWa746Y8cNP/byQyDNpPsqcKseZTLh17sQ==",
      "optional": true
    },
    "google-closure-compiler-windows": {
      "version": "20200224.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler-windows/-/google-closure-compiler-windows-20200224.0.0.tgz",
      "integrity": "sha512-l6w2D8r9+GC9CQTAYEMAuNI996Zb6YV5qG7+FR0gCoL6h6S3Mc7mi87bafgwaicsVcmmHE/9kCBuW4ZyTMs5Fg==",
      "optional": true
    },
```

`google-closure-compiler-linux` is seen twice, once as dependency of `google-closure-compiler` and properly locked to version `20200224.0.0`, but a second time standalone with version `20210406.0.0`.

That seems to contradict what is defined in Emscripten 1.39.20's original `package-lock.json`: https://github.com/emscripten-core/emscripten/blob/1.39.20/package-lock.json#L111-L154

Happens on GitHub Actions' Ubuntu 20.04 image, and reproduced locally on Mageia 9.

I could also reproduce the issue (unbound `google-closure-compiler-linux` version) with Emscripten `2.0.15`, though this one links properly, so it doesn't seem incompatible with version `20210406.0.0`.

<details>
<summary>Why we use Emscripten 1.39.20</summary>

That's just an arbitrary "old" version as we still need to support down to 1.39.9 for compatibility with Mono 6.12.x:
https://github.com/mono/mono/blob/581e5827f469ca214f42ca94b4e1f79859281e20/sdks/builds/wasm.mk#L4

(It's actually pinned to 1.39.7 in Mono but that really was broken so we've upgraded to 1.39.9 - but going beyond requires reviewing and cherry-picking changes from Mono `master` that ensure compatibility with newer Emscripten versions, and that's a significant amount of work we haven't been able to put in yet - so we're stuck with old Emscripten for our Mono support.)

</details>

**Comment by sbc100** [comment]
Did this happen even before #793?

Is you go into `upstream/emscripten` and just run `npm ci` or `npm install` does that work?

**Comment by sbc100** [comment]
I think the problem relates to https://github.com/emscripten-core/emsdk/blob/16ee884464be3bdd99b496bb6e9f4118324abfd8/emsdk.py#L1367 which tries to be clever and runs `npm ci --no-optional` followed by a specific npm install of the native closure compiler.

**Comment by juj** [comment]
Emsdk runs
```
npm ci --production --no-optional
npm install --production --no-optional google-closure-compiler-<windows/linux/osx>
```
in the Emscripten root directory to install npm packages. This just changed in PR #793. Before that PR, emsdk would instead run
```
npm ci --production --no-optional
npm install google-closure-compiler-<windows/linux/osx>
```
but there the second command line was actually not doing what it looks like it would. Instead of installing just e.g. `google-closure-compiler-windows` package, it would install all development packages as well (escheck and eslint), resulting in a 125MB node_modules directory. (as opposed to 64MB when one omits the dev packages).

The reason why we don't simply run
```
npm ci --production
```
is that `google-closure-compiler@20200920.0.0` has a massive dependency chain
```
+-- google-closure-compiler@20200920.0.0
| +-- google-closure-compiler-java@20200920.0.0 (9.25MB)
| +-- google-closure-compiler-linux@20200920.0.0 (287MB)
| +-- google-closure-compiler-osx@20200920.0.0 (272MB)
| +-- google-closure-compiler-windows@20200920.0.0 (40.2MB)
```
and people creating developer packages using emsdk do not appreciate needing to package a huge 664MB node_modules in their redistributables.

That background information aside, testing out locally, I can see that the second command
```
npm install --production --no-optional google-closure-compiler-windows
````
does indeed install latest Closure compiler `google-closure-compiler-windows@20210406.0.0`, and not the version 20200920.0.0 that is specified in both package.json and package-lock.json.

Trying out
```
npm ci --production --no-optional google-closure-compiler-windows
```
does the same, and installs the latest Closure compiler and not the pinned version.

Trying out the `--no-package-lock` flag does not seem to help here.

Also searching e.g.
 - https://stackoverflow.com/questions/52786695/npm-install-always-installs-everything-from-package-json
 - https://stackoverflow.com/questions/49732031/npm-install-single-package-without-rest-of-dependencies
 - https://stackoverflow.com/questions/22420564/install-only-one-package-from-package-json
 - https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json
 - https://docs.npmjs.com/cli/v7/commands/npm-ci and https://docs.npmjs.com/cli/v7/commands/npm-install

comes up short of good ways to achieve this.

The only thing I can think of is to actually specify the Closure version that we depend on also in emsdk.py, but that will require maintaining the version numbers in lockstep, and won't have proper versioning history for installing old Emscripten packages that would have used an older Closure, unless we create some kind of `npm_install.bat/.sh` script in the Emscripten repo itself.

**Comment by juj** [comment]
Actually, now I realize that if I run just the first install command, I get
```
E:\code\emsdk\emscripten\main>npm ci --production --no-optional
added 47 packages in 0.82s

E:\code\emsdk\emscripten\main>npm list
E:\code\emsdk\emscripten\main
+-- acorn@7.3.1
+-- google-closure-compiler@20200920.0.0
| +-- chalk@2.4.2
| | +-- ansi-styles@3.2.1
| | | `-- color-convert@1.9.3
| | |   `-- color-name@1.1.3
| | +-- escape-string-regexp@1.0.5
| | `-- supports-color@5.5.0
| |   `-- has-flag@3.0.0
| +-- google-closure-compiler-java@20200920.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-linux@20200920.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-osx@20200920.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-windows@20200920.0.0
| +-- minimist@1.2.5
| +-- vinyl@2.2.1
| | +-- clone@2.1.2
| | +-- clone-buffer@1.0.0
| | +-- clone-stats@1.0.0
| | +-- cloneable-readable@1.1.3
| | | +-- inherits@2.0.4
| | | +-- process-nextick-args@2.0.1
| | | `-- readable-stream@2.3.7
| | |   +-- core-util-is@1.0.2
| | |   +-- inherits@2.0.4 deduped
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@2.0.1 deduped
| | |   +-- safe-buffer@5.1.2
| | |   +-- string_decoder@1.1.1
| | |   | `-- safe-buffer@5.1.2 deduped
| | |   `-- util-deprecate@1.0.2
| | +-- remove-trailing-separator@1.1.0
| | `-- replace-ext@1.0.1
| `-- vinyl-sourcemaps-apply@0.2.1
|   `-- source-map@0.5.6 deduped
+-- google-closure-compiler-windows@20200920.0.0
+-- html-minifier-terser@5.0.2
| +-- camel-case@3.0.0
| | +-- no-case@2.3.2
| | | `-- lower-case@1.1.4
| | `-- upper-case@1.1.3
| +-- clean-css@4.2.2
| | `-- source-map@0.6.1
| +-- commander@4.1.0
| +-- he@1.2.0
| +-- param-case@2.1.1
| | `-- no-case@2.3.2 deduped
| +-- relateurl@0.2.7
| `-- terser@4.6.3
|   +-- commander@2.20.3
|   +-- source-map@0.6.1
|   `-- source-map-support@0.5.16
|     +-- buffer-from@1.1.1
|     `-- source-map@0.6.1
+-- source-map@0.5.6
`-- wasm2c@1.0.0
```
which is quite peculiar, since it has this:
```
+-- google-closure-compiler@20200920.0.0
| +-- UNMET OPTIONAL DEPENDENCY google-closure-compiler-windows@20200920.0.0
+-- google-closure-compiler-windows@20200920.0.0
```
which suggests that the native closure compiler package is at the same time both installed and not installed? I don't know enough about npm to understand why this happens, but looking at the files under `node_modules`, that does look like everything is in order in for closure.

Should we be good if we just remove the second line `npm install --production --no-optional google-closure-compiler-<windows/linux/osx>` altogether? That was added in #636 though the PR does suggest otherwise. CC @curiousdannii

**Comment by curiousdannii** [comment]
I probably won't have time to test anything sorry. But it shouldn't be hard to get the python to parse package.json to find the version number.

**Comment by sbc100** [comment]
That sounds like great solution if it work!  Lets give it a try.
