### ISSUE TITLE
Bazel toolchain does not work on Windows

### ISSUE THREAD

**Issue by mattsoulanille** [emscripten-core/emsdk#814]
The Bazel toolchain does not work on Windows. There are, as far as I can tell, two reasons for this, although there may be more:
1. The Windows URLs are incorrect. The actual files end in `.zip` (e.g. https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.zip) (Thanks, @walkingeyerobot, for pointing me to them!) but they're [listed as `.tar.bz2`](https://github.com/emscripten-core/emsdk/blob/main/bazel/emscripten_deps.bzl#L54) in `emscripten_deps.bzl`. This can be fixed by changing the `type` argument passed to `http_archive` to `"zip"` and the formatting of the [`emscripten_url` variable](https://github.com/emscripten-core/emsdk/blob/main/bazel/emscripten_deps.bzl#L22) to allow for replacing the file extension with `.zip`.
2. The bash scripts used for Mac and Linux don't run on Windows. The fix for this is likely more difficult since it probably requires equivalent powershell scripts to be written (or maybe there's some way to have Bazel download bash for Windows).

Here's the output of building the hello world demo after applying the fix described in 1. Running in Git bash.
```
$ ~/AppData/Local/Yarn/bin/bazel build :hello-world-wasm
INFO: Analyzed target //hello-world:hello-world-wasm (202 packages loaded, 18554 targets configured).
INFO: Found 1 target...
ERROR: C:/users/matthew/projects/emsdk/bazel/hello-world/BUILD:4:10: Compiling hello-world/hello-world.cc failed: (Exit -1
): emcc.sh failed: error executing command external/emsdk/emscripten_toolchain/emcc.sh --sysroot=external/emscripten_bin_w
in/emscripten/cache/sysroot -fdiagnostics-color -fno-exceptions -fno-strict-aliasing -funsigned-char ... (remaining 32 arg
ument(s) skipped). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\ma
tthew\_bazel_matthew\2zysnvbj\execroot\emsdk\external\emsdk\emscripten_toolchain\emcc.sh" --sysroot=external/emscripten_bi
n_win/emscripten/cache/sysroot -fdiagnostics-color -fno-exceptions -fno-strict-aliasing -funsigned-char -no-canonical-pref
ixes -std=gnu++17 -nostdinc -nostdinc++ -fomit-frame-pointer -O2 -Wall -iquote . -iquote bazel-out/wasm-fastbuild-ST-95dcf
5f511a2/bin -iquote external/emsdk -iquote bazel-out/wasm-fastbuild-ST-95dcf5f511a2/bin/external/emsdk -iwithsysroot/(...)
): %1 is not a valid Win32 application.
 (error: 193)
Target //hello-world:hello-world-wasm failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 146.715s, Critical Path: 0.11s
INFO: 8 processes: 7 internal, 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by DLGL99GL** [comment]
Hello, have you solved this problem? @mattsoulanille

**Comment by sbc100** [comment]
Sounds like maybe don't do any CI testing of the window bazel toolchain.

**Comment by mattsoulanille** [comment]
I haven't solved this or found a workaround, @DLGL99GL. I may take another look at it, but that would probably be later rather than sooner.

**Comment by zaucy** [comment]
I made an earnest attempt at fixing the issue here: #929. I didn't add a CI configuration for testing. I would love for some feedback/review.
