### ISSUE TITLE
Build fails after updating from 2.0.15 to 2.0.21

### ISSUE THREAD

**Issue by narveer-rathore** [emscripten-core/emsdk#820]
Recently we decided to upgrade emsdk from `2.0.15` to `2.0.21` and after that build started failing.

Build works if we downgrade to `2.0.15`
Running on - MacOS (GNU Make 3.81)

With 2.0.21 make command have parameters that are not present when running with 2.0.15. Adding screenshots of the output. Are there any additional steps required before upgrade?

Version 2.0.21 (not working)
<img width="1259" alt="Screenshot 2021-05-19 at 3 56 33 PM" src="https://user-images.githubusercontent.com/19947715/118798473-4f136b80-b8bb-11eb-84f9-41702211e974.png">

Version 2.0.15 (working)
<img width="1259" alt="Screenshot 2021-05-19 at 3 59 19 PM" src="https://user-images.githubusercontent.com/19947715/118798637-7d914680-b8bb-11eb-84d9-c1298b32115f.png">

**Comment by sbc100** [comment]
You should not be using `emcmake` except for the fist command the actually runs `cmake`.   For the second command to actually build your project you can/should just run `make`.

I guess in the past this was allowed, but it never really made sense to run `emcmake make` (because emcmake was always designed to run cmake itself, not to actually build your project).

**Comment by narveer-rathore** [comment]
Thanks, that works perfectly.

**Comment by kripken** [comment]
@sbc100 Why did this change? That's not obvious to me. Is it mentioned in the changelog?

**Comment by sbc100** [comment]
In this case its not running `emmake` before `make`.. that works.   In this case OP as running `emcmake` with `make`.  (Note the `c` in `emcmake`.

**Comment by sbc100** [comment]
`emcmake` is assuming it can pass cmake-style args.. which make doesn't understand.

**Comment by sbc100** [comment]
We could add a message to emcmake if it sees that arg1 doesn't look like cmake?

**Comment by kripken** [comment]
Oh... I missed the "c", sorry :rofl: 

A warning might make sense, but it might have false positives, so I'm not sure...
