### ISSUE TITLE
ASYNCIFY breaks wasm-opt

### ISSUE THREAD

**Issue by Photosounder** [emscripten-core/emsdk#825]
I added `-s ASYNCIFY=1` to my `emcc` build command so that I could use `emscripten_sleep()`, and it makes `wasm-opt` go wild with disk reads and writes for half a minute (which doesn't happen without ASYNCIFY, and to be clear it's the virtual machine's disk, so it's the local Linux filesystem) and ultimately fails with this:

```
 "/home/user/emsdk/upstream/bin/wasm-opt" --strip-dwarf --asyncify --pass-arg=asyncify-asserts --pass-arg=asyncify-imports@env.invoke_*,env.__call_main,env.emscripten_sleep,env.emscripten_wget,env.emscripten_wget_data,env.emscripten_idb_load,env.emscripten_idb_store,env.emscripten_idb_delete,env.emscripten_idb_exists,env.emscripten_idb_load_blob,env.emscripten_idb_store_blob,env.SDL_Delay,env.emscripten_scan_registers,env.emscripten_lazy_load_code,env.emscripten_fiber_swap,wasi_snapshot_preview1.fd_sync,env.__wasi_fd_sync,env._emval_await --strip-debug --strip-producers /home/user/emcc_output/spacewar.wasm -o /home/user/emcc_output/spacewar.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-simd --enable-bulk-memory --enable-sign-ext
emcc: error: '/home/user/emsdk/upstream/bin/wasm-opt --strip-dwarf --asyncify --pass-arg=asyncify-asserts --pass-arg=asyncify-imports@env.invoke_*,env.__call_main,env.emscripten_sleep,env.emscripten_wget,env.emscripten_wget_data,env.emscripten_idb_load,env.emscripten_idb_store,env.emscripten_idb_delete,env.emscripten_idb_exists,env.emscripten_idb_load_blob,env.emscripten_idb_store_blob,env.SDL_Delay,env.emscripten_scan_registers,env.emscripten_lazy_load_code,env.emscripten_fiber_swap,wasi_snapshot_preview1.fd_sync,env.__wasi_fd_sync,env._emval_await --strip-debug --strip-producers /home/user/emcc_output/spacewar.wasm -o /home/user/emcc_output/spacewar.wasm --mvp-features --enable-threads --enable-mutable-globals --enable-simd --enable-bulk-memory --enable-sign-ext' failed (-9)
profiler:DEBUG: block "binaryen" took 24.24 seconds
```

Here's my build command:
```
EMCC_DEBUG=2 emcc -v rl.c commands.c drawobjects.c game.c geometry.c graphics.c gui.c main.c opencl.c science.c sinogram.c sound.c util.c \
	--post-js ../rouziclib/libraries/emscripten.js \
	--embed-file ../vector_type \
	-Wno-dangling-else -Wno-pointer-sign -Wno-incompatible-pointer-types -Wno-parentheses -ferror-limit=1 \
	-s USE_SDL=2 -s ENVIRONMENT=web,worker -s ASYNCIFY=1 -s ALLOW_MEMORY_GROWTH=0 -s INITIAL_MEMORY=268435456 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8 \
	-msimd128 -O0 -s WASM_BIGINT -s ASSERTIONS=1 -g0 \
	--source-map-base https://photosounder.com/emscripten/src/spacewar/ -o ~/emcc_output/spacewar.html
```
I wondered if it could be a conflict with options (I didn't see anything about this being documented) but removing the memory and pthread options didn't change the outcome. I am of course using the latest github version.

**Comment by kripken** [comment]
I think this is likely a matter of machine resources. Asyncify will flatten the IR, which requires a lot more memory (10x as a general estimate). So I'd guess it is running out and starting to swap.

You can try to reduce memory usage by using fewer threads, with `BINARYEN_CORES=1` in the env. But that will compile more slowly.

**Comment by Photosounder** [comment]
But is it what causes the failure? That's the real problem here, the failure, not the hard drive usage.

**Comment by sbc100** [comment]
The ` failed (-9)` means the process was killed with SIGKILL, so it looks like the OS eventually killed the process because it ran out of resources.

We should probably do better at showing when subprocess dies due a signal.

**Comment by Photosounder** [comment]
Ah yes you're right, my virtual machine had only 2 GB of RAM, increasing it to 4 GB solved the problem (including the disk usage due to swap).
