### ISSUE TITLE
Call to emscripten_async_run_in_main_runtime_thread intermittently hangs in postMessage

### ISSUE THREAD

**Issue by DConmy** [emscripten-core/emsdk#842]
There may no be enough information here for action, and I plan on gathering more info, but wanted to document what is known.   For this specific hang, it will always hang.   Prior calls to emscripten_async_run_in_main_runtime_thread/postMessage had not hung.

This is a pthread environment, with a call on one pthread getting processed on the browser main thread.
This last worked without a hang in 2.0.20.
This hangs in 2.0.21 - 2.0.24 (latest at the time of this issue).
I did a cursor review of the PRs merged between the 2 into emscripten, and nothing jumped out

Here are the 2 call stacks.
![image](https://user-images.githubusercontent.com/4826107/122123297-d4773680-cdfb-11eb-844d-88675b2d5507.png)

In reviewing the relevant code (dlfree and emscripten_notify_thread_queue), it does not appear that the 2 threads are working on the same futex.
Given that postMessage is a browser function, it is not apparent how that is deadlocking the 2 threads.

**Comment by sbc100** [comment]
Certainly looks like something that was broken by an emscripten change.  If would be great if you could find out exactly which change was responsible.  We have instructions for bisecting here: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by DConmy** [comment]
emscripten-releases dconmy$ git bisect bad
dffb50d01b33a2690e4d61452cea88647353cff8 is the first bad commit
commit dffb50d01b33a2690e4d61452cea88647353cff8
Author: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Date:   Wed May 12 18:41:57 2021 +0000

 From bisecting, this PR introduced the regression https://github.com/emscripten-core/emscripten/pull/14046
 
    Roll emscripten from 0c41fab4162d to ef56539faa31 (1 revision)
    
    https://chromium.googlesource.com/external/github.com/emscripten-core/emscripten.git/+log/0c41fab4162d..ef56539faa31
    
    2021-05-12 sbc@chromium.org Enable string merging in wasm-ld (#14046)
    
    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/emscripten-emscripten-releases
    Please CC wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
    is aware of the problem.
    
    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
    
    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
    
    Tbr: wasm-waterfall@grotations.appspotmail.com
    Change-Id: Ibac287c6fedbe63e07a530c47aac65c776f43c6e
    Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/2892954
    Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
    Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>

:100644 100644 e4b402b703c42fe367dc8c70c3b008d8c4076153 681cd71cdcde79ad7841ddcf8ade60b692ad172b M      DEPS

**Comment by sbc100** [comment]
Well that is odd.  If that is true can you see if disabling string merging fixes the issue?   You can do this with `-Wl,-O0` passed to emcc.  (This pass `-O0` to the wasm-ld).

**Comment by DConmy** [comment]
I added -Wl to the link line with emcc.   I was already passing -O0, and it still hung.   (That is, I did not pass -Wl,-O0)
I reverted back to the previous commit ff62645491f8bc03af71a1501da284c9e754e0da and it did not hang.

I then added -Wl,-O0 (together, not realizing that it was one arg) and switched back to commit dffb50d01b33a2690e4d61452cea88647353cff8.   It did not hang.   

Note:   Between the emsdk install, I did not recompile any of our code, just merely relinked, in case that is relevant.

**Comment by sbc100** [comment]
So if I understand correctly you can't work around the issue by passing `-Wl,-O0`.. even with the latest emsdk (2.0.24)?

It would make sense that re-linking is all that is needed since it appears that either:
a) there is bug in the string de-duplication logic 
b) there is a bug somewhere in your code (or the emscripten library code) that is confused about string constants overlapping (perhaps is not honoring the const'ness of string constants?)

The effect of not passing `-Wl,-O0` is that string constants don't all have unique addresses and can be overlapping. e..g

```
const char* a = "foobar";
const char* b = "bar";
```

String tail merging means that these two strings are merged and b is pointer into the middle of a.

**Comment by DConmy** [comment]
Sorry I was not clear.

I can and will work around the issue by passing -Wl,-O0 in both the intermediate 2.0.20x and 2.0.24
If there is anything specific I can gather to understand the problem, I am willing to do so.   With a workaround, this issue is not of immediate importance to us.

**Comment by sbc100** [comment]
Reducing the test case to smallest possible thing is probably way to track this down.

**Comment by DConmy** [comment]
From a more recent internal occurrence, we suspect an overwrite that is affecting the alloc/free mutex.
So, we suspect that the workaround moved things in memory slightly, making the overwrite not cause a hang.

For the more recent occurrence, the sole inclusion of a function, which was never called, prevented the hang.

**Comment by rickg-hcl** [comment]
This turned to be a red herring of sorts in that the hang was caused by attempting to free memory that was not malloc-ed on a secondary thread.  The resulting crash on the secondary thread stopped execution with the global lock held.  Therefore any malloc or free operations will hang, and we don't get our normal crash handling behavior.

It would be nice if dlmalloc could somehow release the lock before crashing, but looking at the code, I don't see how that's possible.
