### ISSUE TITLE
Python "SyntaxError: invalid syntax" on latest HEAD

### ISSUE THREAD

**Issue by rsms** [emscripten-core/emsdk#851]
Repro:
- launch a docker image with bitnami/minideb:jessie (or really any linux with Python 3.4)
- install python 3 (e.g. `apt-get install -y --no-install-recommends python3`)
- fetch HEAD `https://github.com/emscripten-core/emsdk/archive/master.tar.gz` and unarchive
- Run `./emsdk update`, `./emsdk install latest`, `./emsdk activate latest`
- `source /whereyouinstalled-emsdk/emsdk_env.sh`
- `echo 'int main(){return 0;}' > hello.c`
- `emcc hello.c -s WASM=1 -o hello.js -O0`

Expected: success

Actual:

```
$ emcc hello.c -s WASM=1 -o hello.js -O0
  File "/whereyouinstalled-emsdk/upstream/emscripten/emcc.py", line 162
    logger.debug(f'(not saving intermediate {name} because not generating JS)')
                                                                             ^
SyntaxError: invalid syntax
```

Env:

```
$ python --version
Python 3.4.2
$ python3 --version
Python 3.4.2
$ uname -a
Linux hostname 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 GNU/Linux
$ emsdk activate latest | head -n1
Resolving SDK alias 'latest' to '2.0.25'
```

**Comment by rsms** [comment]
Tried with  Python 3.7 and it works, so likely the particular features used in the Python scripts are specific to a Python 3  version later than 3.4. AFAIK most Debian-y Linux distros ship with Python 3.4

**Comment by sbc100** [comment]
We currently require python 3.6:   https://github.com/emscripten-core/emscripten/blob/eb07a9d2b9c7ca9331e98a73f31aabbb8191ec57/tools/shared.py#L23-L26

Its a shame ones doesn't get a better error message here.  I was thinking of perhaps injecting something into our launcher scripts to improve this error.

I'm not sure what you mean about Debian though, it looks to me like Debian/stable (buster) ships 3.7.3: https://packages.debian.org/buster/python3.  Which version are you referring to?

**Comment by rsms** [comment]
> We currently require python 3.6: https://github.com/emscripten-core/emscripten/blob/eb07a9d2b9c7ca9331e98a73f31aabbb8191ec57/tools/shared.py#L23-L26
>
> Its a shame ones doesn't get a better error message here. I was thinking of perhaps injecting something into our launcher scripts to improve this error.

Ya. Since it's a syntax error I assume python never attempts to evaluate any part of the script so you'll never get to your check with the nice error message.

> I'm not sure what you mean about Debian though, it looks to me like Debian/stable (buster) ships 3.7.3: https://packages.debian.org/buster/python3. Which version are you referring to?
Oh, my bad. Must have been just the distros I tried. With the bitnami/minideb docker images I was able to install Python 3.7 manually to solve the issue.

**Comment by rsms** [comment]
Thanks for you help!
