### ISSUE TITLE
show .wasm info

### ISSUE THREAD

**Issue by crisgol** [emscripten-core/emsdk#852]
I have a .wasm I want to know which version of emscripten it was compiled on.

Do you have any command that displays the .wasm information?

**Comment by sbc100** [comment]
That information is not (in the general case) stored in the wasm binaries that emscripten produces.

wasm-objdump (part of wabt) is probably the best way to take a look at the contents of a wasm, and you may be able to figure out something about where it came from, but there is nothing explictit.
