### ISSUE TITLE
document.currentScript can't be used in module

### ISSUE THREAD

**Issue by yangfengzzz** [emscripten-core/emsdk#863]
I use embind to generate js and wasm binary. But it can't load wasm binary automatically. I find out in js:
`
var _scriptDir = typeof document !== "undefined" && document.currentScript ? document.currentScript.src : undefined;
`

But I use it in a module so it should be [import.meta](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript)

Is there any compile option for such situation and generate proper js files automatically.

**Comment by sbc100** [comment]
Are you trying to use the emscripten-generated JS file as a JS module?  If so, I think the options you want are `-sMODULARIZE` and `-sEXPORT_ES6`.  Are you specifying these option?

**Comment by yangfengzzz** [comment]
Thank you very much! I miss -sEXPORT_ES6, But It find noting about this flag in the document, maybe it is good to add some description in that.
