### ISSUE TITLE
ccache not working with emsdk_env.sh

### ISSUE THREAD

**Issue by rth** [emscripten-core/emsdk#876]
Follow up to ccache support added in https://github.com/emscripten-core/emsdk/pull/711 and https://github.com/emscripten-core/emscripten/pull/13498 

The current instructions to use ccache don't seem work as expected with emsdk_env.sh
```
./emsdk install 2.0.16 ccache-git-emscripten-64bit
./emsdk activate  2.0.16 ccache-git-emscripten-64bit
```
which outputs in my case,
```
Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    emsdk/emsdk
    emsdk/emsdk/node/14.15.5_64bit/bin
    emsdk/emsdk/upstream/emscripten
    emsdk/emsdk/ccache/git-emscripten_64bit/bin
- This can be done for the current shell by running:
    source "emsdk/emsdk/emsdk_env.sh"
```

**First issue**: running `source emsdk_env.sh` adds the other elements to `$PATH` but not `ccache/git-emscripten_64bit/bin`.  

This isn't done in https://github.com/emscripten-core/emsdk/pull/711#issue-573117537, but then I don't understand how that example worked. As far as I can tell `emsdk activate` adds nothing to the path and ccache wasn't there, so it shouldn't have worked. I also don't see any related envs after activating: `env | grep CCACHE` produces nothing. How can I check that ccache was correctly activated? 

**Second issue**: after running,
```bash
source "emsdk/emsdk/emsdk_env.sh"
emcc --clear-cache
ccache -z # clean stats
python embuilder.py build libc
ccache -s
```
I'm getting,
```
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                       554
cache size                          53.4 MB
```
so the ccache isn't used. Now ccache is not in the path, I would expect an error about `ccache not found` instead of silently not working.

If I manually add,
```bash
export PATH="<full_path>/emsdk/emsdk/ccache/git-emscripten_64bit/bin:$PATH"
export EMCC_CCACHE=1  # for good measure
```
ccache now can be found, however I'm still getting 0 cache hits.

Any suggestions on how to debug this? Thanks!

xref: https://github.com/emscripten-core/emscripten/issues/11974

cc @juj

**Comment by rth** [comment]
Closing as outdated and probably no longer relevant.

**Comment by Ghabry** [comment]
I have the same issue as described above.

```
./emsdk install 3.1.56
./emsdk activate 3.1.56
./emsdk install ccache-git-emscripten-64bit
./emsdk activate ccache-git-emscripten-64bit
source ./emsdk_env.sh
```

After doing this ccache is not added to the PATH automatically.

Your old workaround still works:

```
export _EMCC_CCACHE=1
export PATH="$PWD/ccache/git-emscripten_64bit/bin:$PATH"
```

However when attempting to compile something (my test is zlib) I get

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
```

**Comment by kleisauke** [comment]
> However when attempting to compile something (my test is zlib) I get
> 
> ```
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string: construction from null is not valid
> ```

It looks like https://github.com/juj/ccache/pull/3 might fix this.
