### ISSUE TITLE
Starting with tags/2.0.16, emsdk no longer works on El Capitan (dyld errors)

### ISSUE THREAD

**Issue by ngara** [emscripten-core/emsdk#894]
The main thing I want to highlight is that any run of ./emsdk results in dyld errors in version 2.0.16 and above.

Example with tags/2.0.16 (and later tags)
```
$ git checkout tags/2.0.16
Previous HEAD position was f03f1dc 2.0.17 (#786)
HEAD is now at 6162e2e 2.0.16 (#773)

$ ./emsdk activate latest
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /path/to/emsdk/python/3.9.2-1_64bit/bin/python3 (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /path/to/emsdk/python/3.9.2-1_64bit/bin/python3 (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

Example with tags/2.0.15
```
$ git checkout tags/2.0.15
Previous HEAD position was 6162e2e 2.0.16 (#773)
HEAD is now at 7cba2e0 2.0.15 (#743)

$ ./emsdk activate latest
Warning: The SDK/tool 'node-14.15.5-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'python-3.7.4-2-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit' cannot be activated since it is not installed! Skipping this tool...
Warning: The SDK/tool 'sdk-releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit' cannot be activated since it is not installed! Skipping this tool...
Next steps:
- To conveniently access emsdk tools from the command line,
  consider adding the following directories to your PATH:
    /path/to/emsdk
- This can be done for the current shell by running:
    source "/path/to/emsdk/emsdk_env.sh"
- Configure emsdk in your bash profile by running:
    echo 'source "/path/to/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
No tools/SDKs found to activate! Usage:
   emsdk activate tool/sdk1 [tool/sdk2] [...]
```

**Comment by ngara** [comment]
I'm closing this, as I now see the issue after tags/2.0.4 and need to do more research

**Comment by sbc100** [comment]
BTW, with emsdk you should not ever need to checkout a tagged version.   You can use `git checkout origin/main` and then install any version you want using the main branch.  e.g. `./emsdk install 2.0.20`

(also you do need to do the `install` part..`activate` on its own is not enough).

**Comment by ngara** [comment]
Thanks, I was thinking that “emsdk” was committed into the repo and that was why Python was throwing the error, but it turned out to be the Python version itself. Since the included version is compiled for macOS 10.12 and I’m running 10.11, the dyld errors occur. I don’t know how to run the install and activate script, but use my own working version of Python. I’ll look into it more when I get time.

**Comment by sbc100** [comment]
It looks like @juj updated the python-building script to supported older versions of macOS recently in #819.  @juj I guess we now need to actually re-built and re-upload the python binaries?

**Comment by sbc100** [comment]
Also, out of interest is there some reason you can't update your macOS version?

**Comment by ngara** [comment]
I’m on an old 2012 Mac Pro. But it’s tempting...
