### ISSUE TITLE
GLFW linking issues

### ISSUE THREAD

**Issue by hoangngan-nguyen** [emscripten-core/emsdk#899]
Hello everyone,

I used emscripten to build my code with GLFW.
I met the linking error same with this issue:
https://github.com/emscripten-core/emscripten/issues/11514
However, when I used **emcmake cmake "-DCMAKE_EXE_LINKER_FLAGS=-s USE_GLFW=3"**.
The linking issue still happened.

How do I solve this problem? Thanks!

**Comment by sbc100** [comment]
Does `-s USE_GLFW=3` appear in your link command?   Can you show the full failing command (if you are using the `UNIX Makefiles` cmake generator you may need to run `make V=1` for it to show you the full failing command) along with the full error message it produces?

**Comment by hoangngan-nguyen** [comment]
Hello @sbc100,

I am using Windows operating system.
I built code with 2 steps: 
Step 1: emcmake cmake .. "-DCMAKE_EXE_LINKER_FLAGS=-s USE_GLFW=3" -> It works well
Step 2: emmake make verbose=1

I met this error:
`[ 20%] Linking CXX executable hello-webgpu.html
error: undefined symbol: glfwCreateWindow (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _glfwCreateWindow may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: glfwInit (referenced by top-level compiled C/C++ code)`

I also attached my CMakeLists.txt
[CMakeLists.txt](https://github.com/emscripten-core/emsdk/files/7231628/CMakeLists.txt)

**Comment by sbc100** [comment]
I seems like `-s USE_GLFW=3` isn't being passed the linker correctly.

cmake's make generator is hiding the actual link command here.   Can you run `make VERBOSE=1`?   (or you can run cmake with `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` if you want this by default).

I think it will show that `-s USE_GLFW=3` is not on the link line.

**Comment by hoangngan-nguyen** [comment]
Hi @sbc100,

This is the log:
`[ 40%] Linking CXX executable hello-webgpu.html
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\hello-webgpu.dir\link.txt --verbose=1
C:\Users\nguyenhn\Documents\CS248\lab\emsdk\upstream\emscripten\em++.bat -s ASSERTIONS=0 -s EVAL_CTORS=1 -s USE_GLFW=3 -s WASM=1 -s USE_WEBGPU=1 -s NO_EXIT_RUNTIME=1 -s STRICT=1 --shell-file C:/Users/nguyenhn/Documents/CS248/lab/WebGPU-dawn/src/ems/shell.html  -s USE_GLFW=3 -s ENVIRONMENT=web -s MINIMAL_RUNTIME=2 -s TEXTDECODER=2 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=0 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s NO_FILESYSTEM=1 --output_eol=linux @CMakeFiles\hello-webgpu.dir\objects1.rsp -o hello-webgpu.html`

**Comment by sbc100** [comment]
Ah!  I see the problem.   `library_glfw.js` is not automatically included when running in `STRICT` mode.  This is because `STRICT` mode disabled `AUTO_JS_LIBRARIES`.    

We should fix that on the emscripten side so that `USE_GLFW` signals the inclusion of that library. 

For now, you  have several options to get this library included (IMHO in order of best to worst):

1. Add `-lglfw` to your link command
2. Add `-sAUTO_JS_LIBRARIES` to your link command
3. Remove -sSTRICT` from your link command.

**Comment by sbc100** [comment]
Actually, I think you need to use `-lglfw` and `-lGL` at link time

**Comment by hoangngan-nguyen** [comment]
Hi @sbc100,

I tried all the recommendations that you mentioned.
1. Add -lglfw and -lGL to link command, keep -sSTRICT: nothing happened, the error is the same
2. Add -lglfw and -lGL to link command, remove -sSTRICT: nothing happened, the error is the same
3. Add -lglfw and -lGL to link command, remove -sSTRICT, add -sAUTO_JS_LIBRARIES: nothing happened, the error is the same
4. Add -sUSE_GLFW=3 -sAUTO_JS_LIBRARIES,  remove -sSTRICT: 
I met another error:

`"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\hello-webgpu.dir\link.txt --verbose=1
C:\Users\nguyenhn\Documents\CS248\lab\emsdk\upstream\emscripten\em++.bat -s ASSERTIONS=0 -s EVAL_CTORS=1 -s WASM=1 -s USE_WEBGPU=1 -s NO_EXIT_RUNTIME=1 -s USE_GLFW=3 -sAUTO_JS_LIBRARIES --shell-file C:/Users/nguyenhn/Documents/CS248/lab/WebGPU-dawn/src/ems/shell.html -s ENVIRONMENT=web -s MINIMAL_RUNTIME=2 -s TEXTDECODER=2 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=0 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s NO_FILESYSTEM=1 --output_eol=linux @CMakeFiles\hello-webgpu.dir\objects1.rsp -o hello-webgpu.html
error: undefined symbol: $Browser (referenced by $GLFW__deps: ['emscripten_get_now','$GL','$Browser','$GLFW_Window','$GLFW'], referenced by glfwCreateWindow__deps: ['$GLFW'], referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: Browser may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library`

**Comment by sbc100** [comment]
Are you sure you added `-lglfw -lGL` correctly?   In my local testing this definitely fixed the issue.     Can you show the failing command and error message for (1)?

**Comment by hoangngan-nguyen** [comment]
Please see the error in below:
`[100%] Linking CXX executable hello-webgpu.html
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\hello-webgpu.dir\link.txt --verbose=1
C:\Users\nguyenhn\Documents\CS248\lab\emsdk\upstream\emscripten\em++.bat -s ASSERTIONS=0 -s EVAL_CTORS=1 -s WASM=1 -s USE_WEBGPU=1 -s NO_EXIT_RUNTIME=1 -lglfw -lGL  -sSTRICT --shell-file C:/Users/nguyenhn/Documents/CS248/lab/WebGPU-dawn/src/ems/shell.html -s ENVIRONMENT=web -s MINIMAL_RUNTIME=2 -s TEXTDECODER=2 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=0 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s NO_FILESYSTEM=1 --output_eol=linux @CMakeFiles\hello-webgpu.dir\objects1.rsp -o hello-webgpu.html
error: undefined symbol: glfwCreateWindow (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _glfwCreateWindow may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: $Browser (referenced by $GLFW__deps: ['emscripten_get_now','$GL','$Browser','$GLFW_Window','$GLFW'], referenced by glfwInit__deps: ['$GLFW'], referenced by top-level compiled C/C++ code)`

**Comment by sbc100** [comment]
Did you remove `-sUSE_GLFW=3`?  You need that if you want to use version 3 of the library since the default is version 2.

**Comment by hoangngan-nguyen** [comment]
If I add -sUSE_GLFW=3,  I still met the error same with the error at (4):
`[100%] Linking CXX executable hello-webgpu.html
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\hello-webgpu.dir\link.txt --verbose=1
C:\Users\nguyenhn\Documents\CS248\lab\emsdk\upstream\emscripten\em++.bat -s ASSERTIONS=0 -s EVAL_CTORS=1 -s WASM=1 -s USE_WEBGPU=1 -sUSE_GLFW=3 -s NO_EXIT_RUNTIME=1  -lglfw -lGL -sAUTO_JS_LIBRARIES --shell-file C:/Users/nguyenhn/Documents/CS248/lab/WebGPU-dawn/src/ems/shell.html -s ENVIRONMENT=web -s MINIMAL_RUNTIME=2 -s TEXTDECODER=2 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=0 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s NO_FILESYSTEM=1 --output_eol=linux @CMakeFiles\hello-webgpu.dir\objects1.rsp -o hello-webgpu.html
error: undefined symbol: $Browser (referenced by $GLFW__deps: ['emscripten_get_now','$GL','$Browser','$GLFW_Window','$GLFW'], referenced by glfwCreateWindow__deps: ['$GLFW'], referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: Browser may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library`

**Comment by sbc100** [comment]
Now I think your problem is that you are using the `MINIMAL_RUNTIME`.   Have you had success this this setting before?  This settings does not yet have widespread usage and I wouldn't recommend it today unless you really need it.    Can you build with out this setting?

**Comment by hoangngan-nguyen** [comment]
Without adding GLFW, I built code successfully. Remove **MINIMAL_RUNTIME**, I met another error:

https://gyazo.com/ff04a46d710b34f8485203d883ae71e2

**Comment by sbc100** [comment]
It looks like the format of the html shell file is somewhat different with `MINIMAL_RUNTIME`.    Do you need a custom html shell?  If not than just remove the `--shell-file`.      If you do need it then you will need to make a change .. it looks like you need `{{{ SCRIPT }}}` in there rather than `{{{ DOWNLOAD_JS_AND_WASM_FILES }}}`.   

Can I ask where that project comes from and why it uses `MINIMAL_RUNTIME`?   As I say, that features gets less testing and I wouldn't consider it as mature as the default mode.

**Comment by hoangngan-nguyen** [comment]
The project comes from this github:
https://github.com/cwoffenden/hello-webgpu
I changed {{{ DOWNLOAD_JS_AND_WASM_FILES }}} into {{{ SCRIPT }}} and removed MINIMAL_RUNTIME, now I can link code.
Thank you for your help.
