### ISSUE TITLE
Error through MSYS2

### ISSUE THREAD

**Issue by MilkMan1093** [emscripten-core/emsdk#911]
[Errno 22] Invalid argument: '\\\\?\\\\home\\revan\\emsdk\\node\\unzip_temp'

What is this? Can you help me on this? Running on Windows 10, MSYS2 MINGw64

**Comment by MilkMan1093** [comment]
None of those 2 worked, sadly..

**Comment by farvelocity** [comment]
if MSYS2/MinGW or other  subsystems, the function fix_potentially_long_windows_pathname in emsdk.py  mabye do config ,return the normalized paths with backslashes,but the "//?/" returned .
maybe  return path directly donothing ,can resolve the error,like this
  return pathname
