### ISSUE TITLE
tool or SDK not found: 'sdk-releases-upstream-d8fc1b92dbc0ce8d740a7adb937c5137ba4755e0-64bit'

### ISSUE THREAD

**Issue by alvas** [emscripten-core/emsdk#926]
Can't install emsdk.

$./emsdk install latest
Resolving SDK alias 'latest' to '2.0.34'
Resolving SDK version '2.0.34' to 'sdk-releases-upstream-d8fc1b92dbc0ce8d740a7adb937c5137ba4755e0-64bit'
error: tool or SDK not found: 'sdk-releases-upstream-d8fc1b92dbc0ce8d740a7adb937c5137ba4755e0-64bit'

**Comment by sbc100** [comment]
What OS are you using and what architecture?    Can you install previous releases, e.g. `./emsdk install 2.0.33`?

**Comment by minoki** [comment]
I encountered the same issue on Linux/AArch64.

**Comment by sbc100** [comment]
We do not create pre-built binaries for linux/aarch64.  You can using emsdk to install from source. There are ongoing efforts to try to provide prebuilt binaries.  See https://github.com/emscripten-core/emsdk/issues/547 for more info on that.

@alvas if you are also using aarch64 then I think we can close this issue as a duplicate..

**Comment by alvas** [comment]
I am using ubuntu on a raspberry pi 4 B.

Linux qingyun-desktop 5.11.0-1007-raspi #7-Ubuntu SMP PREEMPT Wed Apr 14 22:08:05 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Thanks for this update.

**Comment by sbc100** [comment]
Closing as duplicate
