### ISSUE TITLE
libclang missing in upstream/bin (3.0.0)

### ISSUE THREAD

**Issue by radekdoulik** [emscripten-core/emsdk#942]
The `libclang.dll` is missing in `upstream/bin` directory. The library was still present in emsdk version `2.0.34` and is missing in `3.0.0`. I tried to find whether it was removed intentionaly, but didn't find anything about it.

Was it removed intentionally?

**Comment by sbc100** [comment]
I believe that the dll files are only present in the non-LTO versions of emsdk.  So I think it will be present in `3.0.0-asserts`.  With LTO builds the code is all built directly into the clang binary.
 
Are you using this DLL for something?  I don't think it was ever indended as a part of the emsdk that folks would use.

**Comment by radekdoulik** [comment]
> I believe that the dll files are only present in the non-LTO versions of emsdk. So I think it will be present in 3.0.0-asserts. With LTO builds the code is all built directly into the clang binary.

I keep forgetting what LTO version of emscripten mean, is that related to link time optimization? Is `2.0.34` non-LTO version?

> Are you using this DLL for something? I don't think it was ever indended as a part of the emsdk that folks would use.

We use it for one of our tools, through python bindings.

**Comment by dschuff** [comment]
Maybe we could? I'd rather not, given that the LTO builds already have larger archives and consume more bandwidth and users' disk space. As @sbc100 said we don't think of emsdk as being a general-purpose distribution of LLVM; use for purposes other that with emscripten are out of scope (there are other distributions of LLVM that might be better suited). Having said that, if this *is* a use for emscripten I'd be interested in hearing more about it.

**Comment by radekdoulik** [comment]
Thanks for looking into this.

I checked with our team, and it looks like we might not need the same version as emscripten. So I will try to make it part of one of our packages instead.
