### ISSUE TITLE
png files get corrupted in chrome browser 

### ISSUE THREAD

**Issue by RavikumarTulugu** [emscripten-core/emsdk#943]
I am trying to port a game to emscripten , the game works fine in firefox but it fails to load in chrome, the reason is an assertion failure in libpng library. The libpng library is taken from emscripten-ports repository and unmodified. i am using emsdk-2.0.32 unmodified.  
my emcc command line : 
-g -s STB_IMAGE=1 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1  --preload-file data
data directory contains png files and other assets. 
Also the png rendering is very poor in chrome but it is perfect in firefox. 
the libng runs in to the error :  libpng error: Not a PNG file
The png file gets corrupted and the library fails to find the ping signature. I am clueless on how to debug this further.

**Comment by RavikumarTulugu** [comment]
I noticed it only on latest chrome , i am on linux. The problem is it disappeared after adding more files. There is problem but it got masked by some thing else. you can close it.

**Comment by kripken** [comment]
Ok, closing.
