### ISSUE TITLE
How to run emsdk_env.sh without printing stuff to stdout

### ISSUE THREAD

**Issue by jcubic** [emscripten-core/emsdk#946]
So I just wanted to run tmux and this how it looks like:

![tmux](https://user-images.githubusercontent.com/280241/146077840-9ab15b6b-7ae1-4f9c-8591-cd3419a6717b.png)

that came from .bash_profile line:

```
source "/mnt/ssd/projects/jcubic/wasm/emsdk/emsdk_env.sh"
```

The common rule in Unix is not not print anything to stdout if you don't have nothing to say.

I know that I can modify the code to not print anything to stdout, that most of the time is ignored. But I would like to have this fixed in the tool, since other users may as well need to fix the file them self.

**Comment by sbc100** [comment]
I agree it should be easy to make this script silent.   We could add an environment variable perhaps.

For now does just adding `2> /dev/null` work for you?   (BTW all these message go to stderr since stdout is the actual bash script that the `source` command executes).

**Comment by jcubic** [comment]
I was trying `> /dev/null`. `2>` redirect works fine.
