### ISSUE TITLE
Node 16

### ISSUE THREAD

**Issue by swnf** [emscripten-core/emsdk#947]
The current node version installed with the SDK is node 14. Compiling a library with pthread support using tools like `emconfigure` and `emmake` might fail because the configuration script cannot run the compiled binaries. Node 14 requires the flag `--experimental-wasm-threads` for that which _cannot_ be passed using `NODE_OPTIONS`. The following warning appears in the output:

```
(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)
```

Node 16 is the current LTS version of node and _does not_ require this flag. Adding Node 16 support to emsdk should solve this problem.

**Comment by sbc100** [comment]
Sadly we have some reasons to stick with (or at least to continue to support) an older version node, at least for our internal tooling.  See #877.

I agree it would be nice one to upgrade.

In the mean time the issue you are facing with `emconfigure` not passing the correct argument I believe was addressed in a recent emscripten commit: https://github.com/emscripten-core/emscripten/pull/15590.   You you try it out today using `emsdk install tot` or it will be part of the 3.0.1 when it comes out (hopefully later today).

You are also free to install whatever version of node you like of course, and configure via the `.emscripten` config file or the EM_NODE_JS environment variable.

**Comment by swnf** [comment]
Thanks for your answer. I understand you cannot upgrade yet. NODE_OPTIONS is a nodejs environment variable. The problem I have is that it is not possible to add arguments directly to NODE_JS because emcc assumes it is only a path to an executable [here](https://github.com/emscripten-core/emscripten/blob/edeae2dfa31ed4f281a66ae7b2a473af976a52f5/tools/shared.py#L353). The PR you linked seems to be CMake-specific?

**Comment by swnf** [comment]
Considering that you cannot upgrade my best solution is probably to change NODE_JS. I'm closing this issue for now.
