### ISSUE TITLE
emsdk.py help message typo

### ISSUE THREAD

**Issue by gregbuchholz** [emscripten-core/emsdk#957]
When invoking `emsdk help` it seems like there is a typo in the [last paragraph](https://github.com/emscripten-core/emsdk/blob/4764bfa8483e225bd5e7c09e7203300536e5a483/emsdk.py#L2925-L2929).

> Note: When overriding a custom build type,
       be sure to match the same --build= option to both 'install' and
       'activate' commands and the invocation of 'emsdk_env', or otherwise
       these commands will default to operating on the default build type
       **which in and RelWithDebInfo**.

...is that supposed to be: "which is RelWithDebInfo" or maybe "which is Release"?  Since before that in the help message there is a [section](https://github.com/emscripten-core/emsdk/blob/4764bfa8483e225bd5e7c09e7203300536e5a483/emsdk.py#L2840-L2843) stating:

>--build=&lt;type>: Controls what kind of build of LLVM to
                 perform. Pass either 'Debug', 'Release',
                 'MinSizeRel' or 'RelWithDebInfo'. **Default:
                 'Release'**.

**Comment by sbc100** [comment]
I think its supposed to say `which is RelWithDebInfo`.   If you have time could you send a PR to fix?

**Comment by gregbuchholz** [comment]
[Done](https://github.com/gregbuchholz/emsdk/commit/48f774f1b2fb3edb539fcfa61811825f11807ee8).
