### ISSUE TITLE
macOS Python doesn't run -  dyld issue, /usr/local/opt/gettext/lib/libintl.8.dylib not found

### ISSUE THREAD

**Issue by tangobravo** [emscripten-core/emsdk#980]
It looks like the current python-3.9.2-64bit for macOS was linked on a system with gettext installed via brew or macports. The binary doesn't run for me, on a pretty vanilla M1 Pro MacBook Pro on the latest 12.1 macOS.

```
% python/3.9.2_64bit/bin/python3
dyld[64115]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/xxxxx/Development/Tools/emsdk/python/3.9.2_64bit/bin/python3.9
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file)
zsh: abort      python/3.9.2_64bit/bin/python3
```

**Comment by tangobravo** [comment]
This seems to have been introduced with the recent rebuild from #975 - I just downloaded the previous 3.9.2-1 archive that runs without issue.

Here's the difference in the linked libraries from tool - the previous 3.9.2-1:
```
% otool -L ~/Downloads/python-3.9.2-1/bin/python3
/Users/xxxxx/Downloads/python-3.9.2-1/bin/python3:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1770.106.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

And the current revision 2 build:
```
% otool -L python/3.9.2_64bit/bin/python3
python/3.9.2_64bit/bin/python3:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by tangobravo** [comment]
Just trying again with some checkouts into clean folders.

An `emsdk install latest` is picking up python-3.9.2-1-macos-arm64.tar.gz which is still working OK.

I'm needing to install 2.0.16 which is the most recent version which doesn't lead to issues on iOS Safari with our codebase. That version predates arm64 binaries, so I'm running `emsdk install 2.0.16` in a shell started with `arch -x86_64 zsh` (in another clean checkout). That one pulls in the revision 2 build from above that fails to run.

**Comment by sbc100** [comment]
I guess this is likely a issue with the particular machine that was used to build python.

I'll see if I can create `-3` revision that doesnn't link against that library.

In the mean time, can you work around the issue by checking out emsdk prior to #975 ?

**Comment by tangobravo** [comment]
Yes, it works when checking out the 3.1.2 tag (the commit before #975 was merged).

**Comment by tangobravo** [comment]
Thanks, I can confirm both architectures now run, and give the same wasm output from a simple test main.cpp. The (default) arm64 arch still pulls in revision 1 - does that mean it still has the known issue of missing lzma support?

**Comment by sbc100** [comment]
I'm afraid I don't have access to arm64 hardware.   Perhaps and M1 user could confirm?
