### ISSUE TITLE
./emsdk activate latest cant use

### ISSUE THREAD

**Issue by asqarkababi** [emscripten-core/emsdk#991]
Hi 
I installed the programm but i cant use this command ./emsdk activate latest neither in cmd nor Powershell nor Visualstudio 
I need help and i very appereciate your help

**Comment by sbc100** [comment]
What does `./emsdk activate latest` show?     Are you in the emsdk directory?   Can you try without the leading `./` (its not needed on windows).

**Comment by asqarkababi** [comment]
> What does `./emsdk activate latest` show? Are you in the emsdk directory? Can you try without the leading `./` (its not needed on windows).
<img width="343" alt="Screenshot 2022-02-22 200008" src="https://user-images.githubusercontent.com/96051597/155200497-9e9e2ce7-7caf-4562-968e-83816b94737b.png">
Im in the directory it says the command is either false or doesnt exist sorry thats in German

**Comment by sbc100** [comment]
You still need the `emsdk` part.  So `emsdk install latest` .. then `emsdk activate latest`

**Comment by asqarkababi** [comment]
> You still need the `emsdk` part. So `emsdk install latest` .. then `emsdk activate latest`
<img width="402" alt="Screenshot 2022-02-22 200645" src="https://user-images.githubusercontent.com/96051597/155201459-10aa378d-24cf-4ba4-8d92-5d7fb71069b9.png">
I did that before

**Comment by sbc100** [comment]
You need to type the leading `emsdk` in your commands.  e.g. `emsdk install latest`.. you need type all three of those words.

**Comment by asqarkababi** [comment]
> 

Thank you very much for your help  its working so i will try to build the wasm one question can i know use the ecmake command on visual studio ?

**Comment by sbc100** [comment]
I don't think you can because we use a cross compiler.   I recommend `-G Ninja` (the ninja build tool).

**Comment by asqarkababi** [comment]
Ok thank you even i dont know what -G Ninja is nvm but thank you
